### ISSUE TITLE
plutus-pab/pab-blockfrost: Blockfrost version incompatible with Preprod environment

### ISSUE THREAD

**Issue by minolinpwork** [input-output-hk/plutus-apps#1035]
### Summary

**plutus-apps v1.2.0** is using **cardano-wallet 2022/08/10** which requires **blockfrost < 0.5** which does not cater for the **preprod** environment.

The following error occurs:
_plutus-pab-examples: Unknown environment: `preprod` expecting one of `ipfs`, `mainnet`, `testnet`, `localhost`
CallStack (from HasCallStack):
  error, called at src/Blockfrost/Auth.hs:45:21 in blockfrost-api-0.4.0.1-A9W5au7R2kOUA8M8hTMe9:Blockfrost.Auth_

Part of the diff code with later version of blockfrost:
![Screenshot from 2023-03-26 09-46-45](https://user-images.githubusercontent.com/82283148/227762367-7c085751-79d5-421a-be3d-ac46bc403172.png)

### Steps to reproduce the behavior

Following the [plutus-pab-executables readme](https://github.com/input-output-hk/plutus-apps/tree/main/plutus-pab-executables) with changes from [pab-blockfrost readme](https://github.com/input-output-hk/plutus-apps/blob/main/pab-blockfrost/README.md)

On running the webserver:
**cabal exec -- plutus-chain-index --config testnet/chain-index-config.json start-index**

the following error occurs:
_plutus-pab-examples: Unknown environment: `preprod` expecting one of `ipfs`, `mainnet`, `testnet`, `localhost`
CallStack (from HasCallStack):
  error, called at src/Blockfrost/Auth.hs:45:21 in blockfrost-api-0.4.0.1-A9W5au7R2kOUA8M8hTMe9:Blockfrost.Auth_

### Actual Result

When running the webserver in plutus-pab-executables, the chain index sync from blockfrost does not work for the preprod environment

### Expected Result

That it should work for preprod

### Describe the approach you would take to fix this

Upgrade cardano-wallet to a later version

### System info

plutus-apps: v1.2.0

**Comment by ak3n** [comment]
Thanks for the issue!

Unfortunately, the next release of cardano-wallet [v2022-12-14](https://github.com/input-output-hk/cardano-wallet/releases/tag/v2022-12-14) has [the same constraints for blockfrost libraries](https://github.com/input-output-hk/cardano-wallet/blob/v2022-12-14/lib/wallet/cardano-wallet.cabal#L65).

And [cardano-wallet dropped blockfrost](https://github.com/input-output-hk/cardano-wallet/pull/3679) at all and it won't be available in the newer versions.

You can try to tweak the dependencies in your local `cabal.project` with `allow-newer` to try to use the newest `blockfrost` libraries.
