### ISSUE TITLE
ghcid encounters error of "GHC Core to PLC plugin: E043:Error: Reference to a name which is not a local, a builtin, or an external INLINABLE function:  Variable PlutusTx.Eq.$fEqBuiltinByteString"

### ISSUE THREAD

**Issue by chrissound** [input-output-hk/plutus-apps#106]
## Summary

`ghcid` does not report success. It reports an error of:
```
<no location info>: error:
    GHC Core to PLC plugin: E043:Error: Reference to a name which is not a local, a builtin, or an external INLINABLE function: 
Variable PlutusTx.Eq.$fEqBuiltinByteString
            [DFunId(nt)]
            No unfolding

```

It seems to be the same issue mentioned here: https://cardano.stackexchange.com/questions/459/haskell-ide-inlinable-error-help however I'm not sure which module is responsible for the error.

## Steps to reproduce

This is from the latest commit on `main`.

```
git clone https://github.com/input-output-hk/plutus-apps.git
git reset --hard fac42e9bf4ea8b91a51ee666292e1f7da2584000
nix-shell
ghcid
```

## Expected behavior

ghcid to report success

## System info (please complete the following information):

- OS: Nixos 20.09
- Plutus version or commit hash (not sure how to determine this)

**Comment by ak3n** [comment]
Have you checked the troubleshooting section https://github.com/input-output-hk/plutus/blob/master/doc/plutus/troubleshooting.rst#L28? It mentions the ghc flags and other practices that might help.

Also it's not clear how exactly `ghcid` is being used. Following steps to reproduce give me

```
Loading ghci -fno-code -fno-break-on-exception -fno-break-on-error -v1 -ferror-spans -j ...
GHCi, version 8.10.4.20210212: https://www.haskell.org/ghc/  :? for help

No files loaded, GHCi is not working properly.
Command: ghci -fno-code -fno-break-on-exception -fno-break-on-error -v1 -ferror-spans -j
```

**Comment by chrissound** [comment]
Apologies I think I mistook this with a different repo - `plutus-starter`.
