### ISSUE TITLE
Wen inline datum?

### ISSUE THREAD

**Issue by jonathanfishbein1** [input-output-hk/plutus-apps#1065]
https://github.com/input-output-hk/plutus-apps/blob/ed276adafb96757dc4bb8e090aefc303f86a5dff/plutus-contract/src/Plutus/Contract/StateMachine/OnChain.hs#L137

**Comment by berewt** [comment]
It doesn't look as an issue or a question... but if you want to understand what are the benefits of inline datum and how to use them, [Cardano Stackexchange](https://cardano.stackexchange.com) or the builder channel in [IOG discord](https://discord.gg/inputoutput) might be a better place to ask.
