### ISSUE TITLE
The `create-script-context` tool fails with `TextEnvelopeTypeError`

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/plutus-apps#1078]
### Summary

The `create-script-context` doesn't support current body types:

> $ create-script-context --generate-tx test_context_equivalence_ci0_qlg_dummy_step2_tx.body --plutus-v1 --cardano-mode --testnet-magic 42 --out-file test_context_equivalence_ci0_qlg_script_context.redeemer
> 
> create-script-context: Error creating redeemer from: test_context_equivalence_ci0_qlg_dummy_step2_tx.body Error: ReadTxBodyError (FileError "test_context_equivalence_ci0_qlg_dummy_step2_tx.body" (TextEnvelopeTypeError [TextEnvelopeType "Tx AlonzoEra",TextEnvelopeType "Tx BabbageEra"] (TextEnvelopeType "Unwitnessed Tx BabbageEra")))
CallStack (from HasCallStack):
>  error, called at app/create-script-context.hs:82:23 in main:Main

When signed tx instead of tx body is used, the error is the same, except `TextEnvelopeType "Witnessed Tx BabbageEra"`

Transaction files attached.
[tx_files.tar.gz](https://github.com/input-output-hk/plutus-apps/files/11591770/tx_files.tar.gz)

### Steps to reproduce the behavior

1. generate dummy redeemer file, result looks like

> {"constructor":0,"fields":[{"list":[]},{"list":[]},{"map":[{"k":{"bytes":""},"v":{"map":[{"k":{"bytes":""},"v":{"int":0}}]}}]},{"constructor":0,"fields":[{"constructor":0,"fields":[{"constructor":1,"fields":[{"int":42}]},{"constructor":1,"fields":[]}]},{"constructor":0,"fields":[{"constructor":2,"fields":[]},{"constructor":1,"fields":[]}]}]},{"map":[{"k":{"bytes":""},"v":{"map":[{"k":{"bytes":""},"v":{"int":0}}]}}]},{"list":[]},{"list":[]},{"list":[]},{"constructor":1,"fields":[]}]}

2. use the dummy redeemer to generate a dummy Tx
3. derive the correct redeemer from the dummy Tx - while running the corresponding create-script-context command, it fails with `TextEnvelopeTypeError`

### Actual Result

The `create-script-context` command fails with `TextEnvelopeTypeError`

### Expected Result

The correct redeemer is derived from the dummy Tx.

### System info

OS: Fedora 37
Plutus apps: e98c255c66f3aae7f62cdcad15033a09537a0605

**Comment by mkoura** [comment]
Related to https://github.com/input-output-hk/plutus-apps/issues/583, but the error is now different.

**Comment by carbolymer** [comment]
That's pretty much because of https://github.com/input-output-hk/plutus-apps/blob/e98c255c66f3aae7f62cdcad15033a09537a0605/plutus-example/src/PlutusExample/ScriptContextChecker.hs#LL203C16-L203C28 . 

I've created a repro here: https://github.com/input-output-hk/cardano-api/pull/29/files . `unsigned tx envelope` and `signed tx envelope` reproduce the scenarios you described. `unsigned tx envelope cddl` and `signed tx envelope cddl`  appear to be working for those two cases. So this should be used for deserialization:
```haskell
  deserialiseFromTextEnvelopeCddlAnyOf
    [ FromCDDLTx "Witnessed Tx AlonzoEra" CddlTx
    , FromCDDLTx "Witnessed Tx BabbageEra" CddlTx
    ]
```
