### ISSUE TITLE
State Machine can take benefit of inline datum

### ISSUE THREAD

**Issue by berewt** [input-output-hk/plutus-apps#1085]
### Describe the feature you'd like

The state machine doesn't take benefit of inline datum introduced in the Babbage era.

At the moment, the `mkStep` function of `StateMachine` explicitly use `DatumInTx` https://github.com/input-output-hk/plutus-apps/blob/f56224ff487886bdb48cc038d6450462f23a25b6/plutus-contract/src/Plutus/Contract/StateMachine.hs#L552

### Describe alternatives you've considered

As it's hardcoded, no alternative.

**Comment by jonathanfishbein1** [comment]
`mustPayToTheScriptWithDatumInTx` is also hardcoded here

https://github.com/input-output-hk/plutus-apps/blob/f56224ff487886bdb48cc038d6450462f23a25b6/plutus-contract/src/Plutus/Contract/StateMachine/OnChain.hs#L137
