### ISSUE TITLE
Cardano-wallet synchronization stops at slot 41763935

### ISSUE THREAD

**Issue by jankun4** [input-output-hk/plutus-apps#111]
When I'm trying to walk through all steps as described in [here](https://github.com/input-output-hk/plutus-apps/tree/main/plutus-pab/test-node#readme) I'm encountering a problem. Synchronization of the `cardano-wallet` stops at slot 41763935. Because of that I cannot successfully perform all of the steps.

`[cardano-wallet.pools-engine:Info:26] [2021-11-15 01:45:05.08 UTC] {"string":"Syncing (98.89% percent) Applied 51131 blocks, 0 rollbacks in the last 30.002802275s. Currently at slot 41763935."}
[cardano-wallet.pools-engine:Warning:26] [2021-11-15 01:45:35.10 UTC] {"string":"Syncing (98.89% percent) Applied 0 blocks, 0 rollbacks in the last 30.026607965s. Currently at slot 41763935. (progress decreased)"}
[cardano-wallet.pools-engine:Warning:26] [2021-11-15 01:46:05.11 UTC] {"string":"Syncing (98.89% percent) Applied 0 blocks, 0 rollbacks in the last 30.005980651s. Currently at slot 41763935. (progress decreased)"}
[cardano-wallet.pools-engine:Warning:26] [2021-11-15 01:46:35.14 UTC] {"string":"Syncing (98.89% percent) Applied 0 blocks, 0 rollbacks in the last 30.029995944s. Currently at slot 41763935. (progress decreased)"}
[cardano-wallet.pools-engine:Warning:26] [2021-11-15 01:47:05.15 UTC] {"string":"Syncing (98.89% percent) Applied 0 blocks, 0 rollbacks in the last 30.010000168s. Currently at slot 41763935. (progress decreased)"}
`

`cardano-node` constantly outputs some stuff which might be a problem

`[localhos:cardano.node.DnsSubscription:Error:1926] [2021-11-15 01:47:13.66 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 3.124.178.139:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 41763999, blockPointHash = 2fbd8c97cb0643a879564f6fe42c4710486b636c1876a0c454ae8ea202c87d26})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [ShelleyInAlonzoPredFail (LedgersFailure (LedgerFailure (UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (UtxosFailure (ValidationTagMismatch (IsValid True) (FailedUnexpectedly [PlutusFailure "\nThe 2 arg plutus script (PlutusScript PlutusV1 ScriptHash \"8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914\") fails.\nCekError An error has occurred:  User error:\nThe budget was overspent. Final negative state: ({ cpu: -35982 | mem: 0 })\nThe redeemer is: List []\nThe context is:\nPurpose: Minting 8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914\nTxInfo:\n  TxId: ecee1d36dc6f4df7e731deba70e14aa51fade20b01aca8089667fc76ba388ba9\n  Inputs: [ c8f1f0677ee4652498bea5eeb5ecbdce9870e065200b6d00333ee6801a315e46!0 -> - Value (Map [(,Map [(\"\",5000000)])]) addressed to\n                                                                                    PubKeyCredential: ef41e0822f758a0fb7507561047f233d4de9a7003e3ce5d551147ced (StakingHash PubKeyCredential: 43ca32d42d6ef66305c91466c15aa65893acb373865c0a75a33f7e2d) ]\n  Outputs: [ - Value (Map [(,Map [(\"\",2581996)])]) addressed to\n               PubKeyCredential: ef41e0822f758a0fb7507561047f233d4de9a7003e3ce5d551147ced (StakingHash PubKeyCredential: 43ca32d42d6ef66305c91466c15aa65893acb373865c0a75a33f7e2d)\n           , - Value (Map [(,Map [(\"\",2000000)]),(8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914,Map [(\"abc\",1)])]) addressed to\n               ScriptCredential: 8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914 (no staking credential) ]\n  Fee: Value (Map [(,Map [(\"\",418004)])])\n  Value minted: Value (Map [(8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914,Map [(\"abc\",1)])])\n  DCerts: []\n  Wdrl: []\n  Valid range: (-\8734 , +\8734)\n  Signatories: []\n  Datums: []\n" "hZ8aAAMCWQABARoABgvHGQJtAAEaAAJJ8BkD6AABGgACSfAYIBoAJc6oGXH3BBl0TRhkGXRNGGQZdE0YZBl0TRhkGXRNGGQZdE0YZBhkGGQZdE0YZBoAAknwGCAaAAJJ8BggGgACSfAYIBoAAknwGQPoAAEaAAJJ8BggGgACSfAZA+gACBoAAkIgGgAGfiMYdgABARoAAknwGQPoAAgaAAJJ8BoAAbeYGPcBGgACSfAZJxABGgACFV4ZBS4BGQPoGgACSfAZA+gBGgACSfAYIBoAAknwGCAaAAJJ8BggAQEaAAJJ8AEaAAJJ8AQaAAGUrxj4ARoAAZSvGPgBGgACN3wZBVYBGgACveoZAfEBGgACSfAYIBoAAknwGCAaAAJJ8BggGgACSfAYIBoAAknwGCAaAAJJ8BggGgACQiAaAAZ+Ixh2AAEBGfBMGSvSAAEaAAJJ8BggGgACQiAaAAZ+Ixh2AAEBGgACQiAaAAZ+Ixh2AAEBGgAlzqgZcfcEABoAAUG7BBoAAknwGROIAAEaAAJJ8BggGgADAlkAAQEaAAJJ8BggGgACSfAYIBoAAknwGCAaAAJJ8BggGgACSfAYIBoAAknwGCAaAAJJ8BggGgAzDacBAf+CGgAR0/gaGTDBhFkMaVkMZgEAADIyMzIiMjIyMjMiMzIiMjMiMjIyMjMiMjIyMjMzIiIyMyIyMjMiMjIzMiIyMzIiMjMzMzMiIiIiMjIzMyIiMjIzIjIzMiIyMjIzIjMiMjIzMzIiIjMiMyIzIjMiMyIzIiIyMlM1MGAzIjIzBgMwVEkBE3dyb25nIGFtb3VudCBtaW50ZWQAUzU1BaMFUyNTALABIiIiIiIAdQARMGIWIhNTVVBfACIiUzU1BfAEEzBlMzUGQFgAM1MA0AciUzM1MBsAEhNQTDUwSjNXOJIBAkxoAAS0mIQASE1BMNTBKM1c4kkCTGgABLSYhNQTDUwSjNXOJIECTGgABLSYzNQZFBmABSACIhMGkWMwVEkBEHdyb25nIHRva2VuIG5hbWUAMzUF9QYTMiMAIAEyIzIAEyABMzVQAjIzUFUiMzUFUAMAEAI1BSABM1BUIiMAMwAgASABIjNwAAKQAQAKQABgnCQAJqCsJEZmqgtkRqaqoMIARESmamDUpmpg1GYLQASRAQAQaxBsEzAHMzVVBlADACABAEEAQAEwVzI1MA0AEiIiIiIjM1UwWxIAEzUF8iM1UwXBIAEjU1UGcAEiM1UGoAIzVTBfEgASNTVQagASIzVQbQAjM1NVBeABIzB8SAAABIjMH0AIAEjMHwAFIAAAEzVTBcEgASNTVQZwASIzVQagAjM1NVBbABIzVTBgEgASNTVQawASIzVQbgAjVQYgAQASIzNVUFkGcAIAEjNVMGASABI1NVBrABIjNVBuACNVBgABABMzVVBUBiACABUGkjUwKQASIgAgCVADSACE1MAcAEiACMD0AQzM1c0ZuHNVc6oASQABGYA5kZGRkZGRkZGRkZGZmrmjNw5qrnVAKSAAIzMzMzMwFTNQIyMjIzM1c0ZuHNVc6oASQABGYDZgZmroVACMCg1dCauiUAIjUFI1MFAzVziSAQNQVDEABRSZJhNVc8oAIm6oAE1dCoBRmoEYEhq6FQCTM1UCp1ygUmroVAIMzVQKnXKBSauhUAczUCMDk1dCoAxmoEZmqglghOtNXQqAKZGRkZmauaM3DmqudUAJIAAjNQHTIyMjMzVzRm4c1VzqgBJAAEZqBKZqB2601dCoARggGroTV0SgBEagrGpgqGaucSQBA1BUMQAFVJkmE1VzygAibqgATV0KgBGRkZGZmrmjNw5qrnVACSAAIzUCMzUDt1pq6FQAjBANXQmrolACI1BWNTBUM1c4kgEDUFQxAAVUmSYTVXPKACJuqABNXQmrolACI1BSNTBQM1c4kgEDUFQxAAUUmSYTVXPKACJuqABNXQqAIZqBG641dCoAZmoEZmqgluuBKNXQqAEYGRq6E1dEoARGoJxqYJhmrnEkAQNQVDEABNSZJhNXRKACJq6JQARNXRKACJq6JQARNXRKACJq6JQARNXRKACJq6JQARNVc8oAIm6oAE1dCoARkZGRmZq5ozcOoAKQAxGA0YGJq6E1VzygBkZmauaM3DqAEkAIRgMmB2auhNVc8oAhGZmrmjNw6gBpABEYDJgUmroTVXPKAKRmZq5ozcOoAiQABGA4brjV0JqrnlAGI1BJNTBHM1c4kgEDUFQxAASEmSZJkmSYTVXOqACJuqABNXQmrolACI1BCNTBAM1c4kkDUFQxAAQUmSYQQBNQQTUwPzNXOJIBA1BUNQAEBJhNVc8oAIm6oAEiEjMAEAMAIgASIiIiIiEjMzMzMzABALAKAJAIAHAGAFAEADACIAEiEjMAEAMAIgARIhIzABADACEgARIhIzABADACEgARIhIzABADACEgASEiIjAEAFISIiMAMAUhIiIwAgBSEiIjABAFIAESMiMAI3WAAmQAJqoJ5EZmaq58AElBHIzUEYwBDV0IARgBmrogAgLSMjIyMzNXNGbhzVXOqAGkAARmYA5kZGRmZq5ozcOaq51QAkgACMwDTArNXQqAEZqAgBOauhNXRKAERqBmamBiZq5xJAEDUFQxAAMkmSYTVXPKACJuqABNXQqAGZmqgFuuUAo1dCoARmoBjrjV0Jq6JQAiNQLzUwLTNXOJIQNQVDEAAuSZJhNXRKACJqrnlABE3VAAkRCRmYAIAgAYARAAkQkZgAgBgBEACJmqgAuudaIkRkRgBG6sAEyABNVBJIjIzM1Vz4ARKCERmoIJmqgfGAMaq51QAjAFNVc8oARgCGrogAwKBNXQgAiRGRkZmauaM3DqACkAARqAQYApq6E1VzygBkZmauaM3DqAEkAESgEEagUmpgTmaucSQQNQVDEAAoSZJkmE1VzqgAibqgARISIwAgAxEiABEgASMjIzM1c0ZuHNVc6oASQABGYAxgDmroVACN1pq6E1dEoARGoEZqYEJmrnEkEDUFQxAAIkmSYTVXPKACJuqABIhIzABADACIAEjIzM1c0ZuHNVc6oAKQABG641dCaq55QAiNQHzUwHTNXOJIEDUFQxAAHkmSYTdUACJEZGRmZq5ozcOoAKQAhKAORmZq5ozcOoASQARGoBRgDGroTVXPKAIRmZq5ozcOoAaQABKAURqBEamBAZq5xJAQNQVDEAAhSZJkmSYTVXOqACJuqABEhIiMAMAQRIiACESIgARIAEjIzM1c0ZuHUAFIAIgOiMzNXNGbh1ACSAAIDojUBo1MBgzVziSQNQVDEAAZSZJkmE1VzpuqABIyMjIyMjMzVzRm4dQAUgDCALIzM1c0ZuHUAJIAogDSMzNXNGbh1ADSAIIzALN1xq6FQBTdaauhNXRKAKRmZq5ozcOoAiQAxGYBpuuNXQqAObrjV0Jq6JQByMzNXNGbh1AFSAEIzASMBQ1dCoBJuuNXQmrolAJIzM1c0ZuHUAZIAIjAUMBU1dCaq55QCyMzNXNGbh1AHSAAIwEzAWNXQmqueUAwjUCI1MCAzVziSBA1BUMQACFJkmSZJkmSZJkmE1VzqgCCaq55QAxNVc8oAQmqueUAETdUACQkREREYA4BBEJERERGYAwBIBBCRERERgCgECREREQAgkREREAGRCRERERmAEASAQRCRERERmACASAQQAJGRkZGRmZq5ozcOoAKQARGZgEG601dCoAhutNXQqAGbrTV0Jq6JQAyMzNXNGbh1ACSAAIwCjALNXQmqueUAYjUBM1MBEzVziSQNQVDEAASSZJkmE1VzqgBiauiUAETVXPKACJuqABISIwAgAyIhIjMwAQBQBAAyABIyMjMzVzRm4dQAUgAiMAY3XGroTVXPKAGRmZq5ozcOoASQABGAQbrjV0JqrnlAEI1ANNTALM1c4kgEDUFQxAADEmSZJhNVc6oAIm6oAEhIjACADISIwAQAyABIAERIiMjIzM1c0ZuHNVc6oASQABGaqA6YAxq6FQAjAFNXQmrolACI1AJNTAHM1c4khA1BUMQAAhJkmE1VzygAibqgARIAEgARJhESIjM1UwBhIAFQGTNVMAsSABI1NVAWABIjNVAZACNVANABMzVTAGEgASI1NVAXACIlM1MCUzNVMBASABMjNQFSIzNTUAsAMiACACABNTUAkAEiABM1AJIlM1MCcAIQKRABAmI1NVAaABIjMAoAIAUAYQAxM1AdAEADUBoAEzVTALEgASNTVQFgASIyM1UBoAMwAQBTIAE1UCgiUzU1AdABE1UA0AMiE1NVAcACIlM1MCozAMACAIEzVQEgBwARMAYAMAISISMwAQAwAhIAEyABNVAfIhEiJTNTUBcAEQAiITMAUAIzNVMAcSABAFAEABESEiIwAwBBEiEiIzACAFAEESEiIwAQBBEgATIAE1UBoiESJTNTUBEAEVATIhM1AUMAQAIzVTAGEgAQBAATIAE1UBkiESIlM1NQEQARNQBgAyITM1AJAFMAQAIzNVMAcSABAFAEABEjU1ADABIgARI1NQAgASIAISISMwAQAwAhIAEiMzVzRm48AIAEBQBMiUzUwEQARATEzVzgAQCRGoAQkRmaqAORGpqoA4AREZmqgFkRqaqAWAERKZqYDJmauaM3DgApAAANgNCAGJmAUZmqqAoAMAEACAGAGACACAGJGagAqAMoA4iRCRmACAGAEIkACIkRkACZAAmqgIESmamoAoAIgBkQmYAwARgCAAiJEAEJEJEZgAgCABiQAIiJEQkZmACAIAGAEIiQAIkACRKZqYAoAQgAiAMJEZmrmjNw4AQAIAwApABiRABCRAAkACRGbgAAgAREjIwAQASIzADMAIAIAEZ+A2Hmf2Hmfn9h5n9h5n9h5n1ggyPHwZ37kZSSYvqXutey9zphw4GUgC20AMz7mgBoxXkb/AP/YeZ/YeZ/YeZ9YHO9B4IIvdYoPt1B1YQR/Iz1N6acAPjzl1VEUfO3/2Hmf2Hmf2HmfWBxDyjLULW72YwXJFGbBWqZYk6yzc4ZcCnWjP34t/////6FAoUAaAExLQNh6gP///5/YeZ/YeZ/YeZ9YHO9B4IIvdYoPt1B1YQR/Iz1N6acAPjzl1VEUfO3/2Hmf2Hmf2HmfWBxDyjLULW72YwXJFGbBWqZYk6yzc4ZcCnWjP34t/////6FAoUAaACdl7Nh6gP/YeZ/YeZ/Yep9YHI/Y/o/OIZ8KwPcapa/TyY1P+MDM6hxYgoUreRT/2HqA/6JAoUAaAB6EgFgcj9j+j84hnwrA9xqlr9PJjU/4wMzqHFiChSt5FKFDYWJjAdh5n1ggW0sBpKOJLqN1F5PaV/ByrgjuxpTdzahyI5/II55LzRv///+hQKFAGgAGYNSiQKFAAFgcj9j+j84hnwrA9xqlr9PJjU/4wMzqHFiChSt5FKFDYWJjAYCA2Hmf2Hmf2HmA2HqA/9h5n9h7gNh6gP//gIDYeZ9YIOzuHTbcb0335zHeunDhSqUfreILAayoCJZn/Ha6OIup///YeZ9YHI/Y/o/OIZ8KwPcapa/TyY1P+MDM6hxYgoUreRT///8A"]))))))))])}))))))))
[localhos:cardano.node.ErrorPolicy:Warning:69] [2021-11-15 01:47:13.67 UTC] IP 3.124.178.139:3001 ErrorPolicySuspendPeer (Just (ApplicationExceptionTrace (InvalidBlock (At (Block {blockPointSlot = SlotNo 41763999, blockPointHash = 2fbd8c97cb0643a879564f6fe42c4710486b636c1876a0c454ae8ea202c87d26})) (ValidationError (ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [ShelleyInAlonzoPredFail (LedgersFailure (LedgerFailure (UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (UtxosFailure (ValidationTagMismatch (IsValid True) (FailedUnexpectedly [PlutusFailure "\nThe 2 arg plutus script (PlutusScript PlutusV1 ScriptHash \"8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914\") fails.\nCekError An error has occurred:  User error:\nThe budget was overspent. Final negative state: ({ cpu: -35982 | mem: 0 })\nThe redeemer is: List []\nThe context is:\nPurpose: Minting 8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914\nTxInfo:\n  TxId: ecee1d36dc6f4df7e731deba70e14aa51fade20b01aca8089667fc76ba388ba9\n  Inputs: [ c8f1f0677ee4652498bea5eeb5ecbdce9870e065200b6d00333ee6801a315e46!0 -> - Value (Map [(,Map [(\"\",5000000)])]) addressed to\n                                                                                    PubKeyCredential: ef41e0822f758a0fb7507561047f233d4de9a7003e3ce5d551147ced (StakingHash PubKeyCredential: 43ca32d42d6ef66305c91466c15aa65893acb373865c0a75a33f7e2d) ]\n  Outputs: [ - Value (Map [(,Map [(\"\",2581996)])]) addressed to\n               PubKeyCredential: ef41e0822f758a0fb7507561047f233d4de9a7003e3ce5d551147ced (StakingHash PubKeyCredential: 43ca32d42d6ef66305c91466c15aa65893acb373865c0a75a33f7e2d)\n           , - Value (Map [(,Map [(\"\",2000000)]),(8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914,Map [(\"abc\",1)])]) addressed to\n               ScriptCredential: 8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914 (no staking credential) ]\n  Fee: Value (Map [(,Map [(\"\",418004)])])\n  Value minted: Value (Map [(8fd8fe8fce219f0ac0f71aa5afd3c98d4ff8c0ccea1c5882852b7914,Map [(\"abc\",1)])])\n  DCerts: []\n  Wdrl: []\n  Valid range: (-\8734 , +\8734)\n  Signatories: []\n  Datums: []\n" "hZ8aAAMCWQABARoABgvHGQJtAAEaAAJJ8BkD6AABGgACSfAYIBoAJc6oGXH3BBl0TRhkGXRNGGQZdE0YZBl0TRhkGXRNGGQZdE0YZBhkGGQZdE0YZBoAAknwGCAaAAJJ8BggGgACSfAYIBoAAknwGQPoAAEaAAJJ8BggGgACSfAZA+gACBoAAkIgGgAGfiMYdgABARoAAknwGQPoAAgaAAJJ8BoAAbeYGPcBGgACSfAZJxABGgACFV4ZBS4BGQPoGgACSfAZA+gBGgACSfAYIBoAAknwGCAaAAJJ8BggAQEaAAJJ8AEaAAJJ8AQaAAGUrxj4ARoAAZSvGPgBGgACN3wZBVYBGgACveoZAfEBGgACSfAYIBoAAknwGCAaAAJJ8BggGgACSfAYIBoAAknwGCAaAAJJ8BggGgACQiAaAAZ+Ixh2AAEBGfBMGSvSAAEaAAJJ8BggGgACQiAaAAZ+Ixh2AAEBGgACQiAaAAZ+Ixh2AAEBGgAlzqgZcfcEABoAAUG7BBoAAknwGROIAAEaAAJJ8BggGgADAlkAAQEaAAJJ8BggGgACSfAYIBoAAknwGCAaAAJJ8BggGgACSfAYIBoAAknwGCAaAAJJ8BggGgAzDacBAf+CGgAR0/gaGTDBhFkMaVkMZgEAADIyMzIiMjIyMjMiMzIiMjMiMjIyMjMiMjIyMjMzIiIyMyIyMjMiMjIzMiIyMzIiMjMzMzMiIiIiMjIzMyIiMjIzIjIzMiIyMjIzIjMiMjIzMzIiIjMiMyIzIjMiMyIzIiIyMlM1MGAzIjIzBgMwVEkBE3dyb25nIGFtb3VudCBtaW50ZWQAUzU1BaMFUyNTALABIiIiIiIAdQARMGIWIhNTVVBfACIiUzU1BfAEEzBlMzUGQFgAM1MA0AciUzM1MBsAEhNQTDUwSjNXOJIBAkxoAAS0mIQASE1BMNTBKM1c4kkCTGgABLSYhNQTDUwSjNXOJIECTGgABLSYzNQZFBmABSACIhMGkWMwVEkBEHdyb25nIHRva2VuIG5hbWUAMzUF9QYTMiMAIAEyIzIAEyABMzVQAjIzUFUiMzUFUAMAEAI1BSABM1BUIiMAMwAgASABIjNwAAKQAQAKQABgnCQAJqCsJEZmqgtkRqaqoMIARESmamDUpmpg1GYLQASRAQAQaxBsEzAHMzVVBlADACABAEEAQAEwVzI1MA0AEiIiIiIjM1UwWxIAEzUF8iM1UwXBIAEjU1UGcAEiM1UGoAIzVTBfEgASNTVQagASIzVQbQAjM1NVBeABIzB8SAAABIjMH0AIAEjMHwAFIAAAEzVTBcEgASNTVQZwASIzVQagAjM1NVBbABIzVTBgEgASNTVQawASIzVQbgAjVQYgAQASIzNVUFkGcAIAEjNVMGASABI1NVBrABIjNVBuACNVBgABABMzVVBUBiACABUGkjUwKQASIgAgCVADSACE1MAcAEiACMD0AQzM1c0ZuHNVc6oASQABGYA5kZGRkZGRkZGRkZGZmrmjNw5qrnVAKSAAIzMzMzMwFTNQIyMjIzM1c0ZuHNVc6oASQABGYDZgZmroVACMCg1dCauiUAIjUFI1MFAzVziSAQNQVDEABRSZJhNVc8oAIm6oAE1dCoBRmoEYEhq6FQCTM1UCp1ygUmroVAIMzVQKnXKBSauhUAczUCMDk1dCoAxmoEZmqglghOtNXQqAKZGRkZmauaM3DmqudUAJIAAjNQHTIyMjMzVzRm4c1VzqgBJAAEZqBKZqB2601dCoARggGroTV0SgBEagrGpgqGaucSQBA1BUMQAFVJkmE1VzygAibqgATV0KgBGRkZGZmrmjNw5qrnVACSAAIzUCMzUDt1pq6FQAjBANXQmrolACI1BWNTBUM1c4kgEDUFQxAAVUmSYTVXPKACJuqABNXQmrolACI1BSNTBQM1c4kgEDUFQxAAUUmSYTVXPKACJuqABNXQqAIZqBG641dCoAZmoEZmqgluuBKNXQqAEYGRq6E1dEoARGoJxqYJhmrnEkAQNQVDEABNSZJhNXRKACJq6JQARNXRKACJq6JQARNXRKACJq6JQARNXRKACJq6JQARNVc8oAIm6oAE1dCoARkZGRmZq5ozcOoAKQAxGA0YGJq6E1VzygBkZmauaM3DqAEkAIRgMmB2auhNVc8oAhGZmrmjNw6gBpABEYDJgUmroTVXPKAKRmZq5ozcOoAiQABGA4brjV0JqrnlAGI1BJNTBHM1c4kgEDUFQxAASEmSZJkmSYTVXOqACJuqABNXQmrolACI1BCNTBAM1c4kkDUFQxAAQUmSYQQBNQQTUwPzNXOJIBA1BUNQAEBJhNVc8oAIm6oAEiEjMAEAMAIgASIiIiIiEjMzMzMzABALAKAJAIAHAGAFAEADACIAEiEjMAEAMAIgARIhIzABADACEgARIhIzABADACEgARIhIzABADACEgASEiIjAEAFISIiMAMAUhIiIwAgBSEiIjABAFIAESMiMAI3WAAmQAJqoJ5EZmaq58AElBHIzUEYwBDV0IARgBmrogAgLSMjIyMzNXNGbhzVXOqAGkAARmYA5kZGRmZq5ozcOaq51QAkgACMwDTArNXQqAEZqAgBOauhNXRKAERqBmamBiZq5xJAEDUFQxAAMkmSYTVXPKACJuqABNXQqAGZmqgFuuUAo1dCoARmoBjrjV0Jq6JQAiNQLzUwLTNXOJIQNQVDEAAuSZJhNXRKACJqrnlABE3VAAkRCRmYAIAgAYARAAkQkZgAgBgBEACJmqgAuudaIkRkRgBG6sAEyABNVBJIjIzM1Vz4ARKCERmoIJmqgfGAMaq51QAjAFNVc8oARgCGrogAwKBNXQgAiRGRkZmauaM3DqACkAARqAQYApq6E1VzygBkZmauaM3DqAEkAESgEEagUmpgTmaucSQQNQVDEAAoSZJkmE1VzqgAibqgARISIwAgAxEiABEgASMjIzM1c0ZuHNVc6oASQABGYAxgDmroVACN1pq6E1dEoARGoEZqYEJmrnEkEDUFQxAAIkmSYTVXPKACJuqABIhIzABADACIAEjIzM1c0ZuHNVc6oAKQABG641dCaq55QAiNQHzUwHTNXOJIEDUFQxAAHkmSYTdUACJEZGRmZq5ozcOoAKQAhKAORmZq5ozcOoASQARGoBRgDGroTVXPKAIRmZq5ozcOoAaQABKAURqBEamBAZq5xJAQNQVDEAAhSZJkmSYTVXOqACJuqABEhIiMAMAQRIiACESIgARIAEjIzM1c0ZuHUAFIAIgOiMzNXNGbh1ACSAAIDojUBo1MBgzVziSQNQVDEAAZSZJkmE1VzpuqABIyMjIyMjMzVzRm4dQAUgDCALIzM1c0ZuHUAJIAogDSMzNXNGbh1ADSAIIzALN1xq6FQBTdaauhNXRKAKRmZq5ozcOoAiQAxGYBpuuNXQqAObrjV0Jq6JQByMzNXNGbh1AFSAEIzASMBQ1dCoBJuuNXQmrolAJIzM1c0ZuHUAZIAIjAUMBU1dCaq55QCyMzNXNGbh1AHSAAIwEzAWNXQmqueUAwjUCI1MCAzVziSBA1BUMQACFJkmSZJkmSZJkmE1VzqgCCaq55QAxNVc8oAQmqueUAETdUACQkREREYA4BBEJERERGYAwBIBBCRERERgCgECREREQAgkREREAGRCRERERmAEASAQRCRERERmACASAQQAJGRkZGRmZq5ozcOoAKQARGZgEG601dCoAhutNXQqAGbrTV0Jq6JQAyMzNXNGbh1ACSAAIwCjALNXQmqueUAYjUBM1MBEzVziSQNQVDEAASSZJkmE1VzqgBiauiUAETVXPKACJuqABISIwAgAyIhIjMwAQBQBAAyABIyMjMzVzRm4dQAUgAiMAY3XGroTVXPKAGRmZq5ozcOoASQABGAQbrjV0JqrnlAEI1ANNTALM1c4kgEDUFQxAADEmSZJhNVc6oAIm6oAEhIjACADISIwAQAyABIAERIiMjIzM1c0ZuHNVc6oASQABGaqA6YAxq6FQAjAFNXQmrolACI1AJNTAHM1c4khA1BUMQAAhJkmE1VzygAibqgARIAEgARJhESIjM1UwBhIAFQGTNVMAsSABI1NVAWABIjNVAZACNVANABMzVTAGEgASI1NVAXACIlM1MCUzNVMBASABMjNQFSIzNTUAsAMiACACABNTUAkAEiABM1AJIlM1MCcAIQKRABAmI1NVAaABIjMAoAIAUAYQAxM1AdAEADUBoAEzVTALEgASNTVQFgASIyM1UBoAMwAQBTIAE1UCgiUzU1AdABE1UA0AMiE1NVAcACIlM1MCozAMACAIEzVQEgBwARMAYAMAISISMwAQAwAhIAEyABNVAfIhEiJTNTUBcAEQAiITMAUAIzNVMAcSABAFAEABESEiIwAwBBEiEiIzACAFAEESEiIwAQBBEgATIAE1UBoiESJTNTUBEAEVATIhM1AUMAQAIzVTAGEgAQBAATIAE1UBkiESIlM1NQEQARNQBgAyITM1AJAFMAQAIzNVMAcSABAFAEABEjU1ADABIgARI1NQAgASIAISISMwAQAwAhIAEiMzVzRm48AIAEBQBMiUzUwEQARATEzVzgAQCRGoAQkRmaqAORGpqoA4AREZmqgFkRqaqAWAERKZqYDJmauaM3DgApAAANgNCAGJmAUZmqqAoAMAEACAGAGACACAGJGagAqAMoA4iRCRmACAGAEIkACIkRkACZAAmqgIESmamoAoAIgBkQmYAwARgCAAiJEAEJEJEZgAgCABiQAIiJEQkZmACAIAGAEIiQAIkACRKZqYAoAQgAiAMJEZmrmjNw4AQAIAwApABiRABCRAAkACRGbgAAgAREjIwAQASIzADMAIAIAEZ+A2Hmf2Hmfn9h5n9h5n9h5n1ggyPHwZ37kZSSYvqXutey9zphw4GUgC20AMz7mgBoxXkb/AP/YeZ/YeZ/YeZ9YHO9B4IIvdYoPt1B1YQR/Iz1N6acAPjzl1VEUfO3/2Hmf2Hmf2HmfWBxDyjLULW72YwXJFGbBWqZYk6yzc4ZcCnWjP34t/////6FAoUAaAExLQNh6gP///5/YeZ/YeZ/YeZ9YHO9B4IIvdYoPt1B1YQR/Iz1N6acAPjzl1VEUfO3/2Hmf2Hmf2HmfWBxDyjLULW72YwXJFGbBWqZYk6yzc4ZcCnWjP34t/////6FAoUAaACdl7Nh6gP/YeZ/YeZ/Yep9YHI/Y/o/OIZ8KwPcapa/TyY1P+MDM6hxYgoUreRT/2HqA/6JAoUAaAB6EgFgcj9j+j84hnwrA9xqlr9PJjU/4wMzqHFiChSt5FKFDYWJjAdh5n1ggW0sBpKOJLqN1F5PaV/ByrgjuxpTdzahyI5/II55LzRv///+hQKFAGgAGYNSiQKFAAFgcj9j+j84hnwrA9xqlr9PJjU/4wMzqHFiChSt5FKFDYWJjAYCA2Hmf2Hmf2HmA2HqA/9h5n9h7gNh6gP//gIDYeZ9YIOzuHTbcb0335zHeunDhSqUfreILAayoCJZn/Ha6OIup///YeZ9YHI/Y/o/OIZ8KwPcapa/TyY1P+MDM6hxYgoUreRT///8A"]))))))))])}))))))))))) 200s 200s`

We've encountered this problem on 2 different machines. Each time synchronization stops exactly at slot 41763935.

`cardano-wallet` version:
v2021-09-29 (git revision: 40e8e93dec35cebb830af317b1ddb64d275014e2)

`cardano-node` version:
cardano-node 1.30.0 - linux-x86_64 - ghc-8.10
git rev 40e8e93dec35cebb830af317b1ddb64d275014e2

Both `cardano-wallet` and `cardano-node` are provided by `nix-shell` from `plutus-apps` repository with tag [v2021-11-05](https://github.com/input-output-hk/plutus-apps/releases/tag/v2021-11-05).

Steps to reproduce:

Terminal 1

> nix-shell
> cabal build plutus-pab-examples plutus-chain-index cardano-node cardano-wallet
> cd $PLUTUS/plutus-pab/test-node/
> ./start-testnet-node.sh

Terminal 2

> nix-shell
> cd $PLUTUS/plutus-pab/test-node/
> cabal exec -- cardano-wallet serve \
    --testnet testnet/testnet-byron-genesis.json \
    --node-socket testnet/node.sock

**Comment by silky** [comment]
See #94 and https://github.com/input-output-hk/plutus-apps/issues/86

The docs have been updated: https://github.com/input-output-hk/plutus-apps/tree/main/plutus-pab/test-node
