### ISSUE TITLE
Could not resolve dependencies while building PAB components

### ISSUE THREAD

**Issue by resgsh** [input-output-hk/plutus-apps#112]
## Summary

Error in dependency resolution while trying to build PAB components.

## Steps to reproduce

1. Clone plutus-apps repo
2. Go to plutus-apps/plutus-pab/
3. Run `cabal build plutus-pab-local-cluster cardano-node cardano-wallet` as instructed in the README
4. See attached screenshot for error

## Expected behavior

Build should go through.

## System info (please complete the following information):

- OS: Ubuntu
- Version:  20.04
- Beta release tag: v2021-11-05

## Screenshots and attachments
![image](https://user-images.githubusercontent.com/89894646/141769694-e9c75a63-fd97-41b6-8546-7886d9fdf1b0.png)

**Comment by ak3n** [comment]
Please make sure that you are using `nix-shell` and `which cabal` shows the right path `/nix/store/...`.

**Comment by resgsh** [comment]
Thanks for pointing out. It works now.
