### ISSUE TITLE
BUG Wrong github reference to wallet in cabal

### ISSUE THREAD

**Issue by bhoudebert** [input-output-hk/plutus-apps#113]
https://github.com/input-output-hk/plutus-apps/blob/4ecc1d9350e9897557d2a15699a9ace7df665a01/cabal.project#L120

It should be now pointed to https://github.com/input-output-hk/cardano-wallet

**Comment by Yasuke** [comment]
Hey @bhoudebert I will look into getting this pointed in the right place, thanks for the heads up

**Comment by Yasuke** [comment]
This has been address in [Fix Plutus #3023](https://github.com/input-output-hk/cardano-wallet/pull/3023), we are just awaiting the fixes to get into upstream.

**Comment by bhoudebert** [comment]
Top thanks!
