### ISSUE TITLE
Effect interpreter equivalence

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/plutus-apps#115]
## Summary

The interpreters for mocked wallet, real wallet, playground etc seem to be not equivalent. My contract works in both playground and in the test suite, but fails against testnet, because apparently `txInfoSignatories` are not automatically added. You have to add `Constraints.mustBeSignedBy pubk` to your txConstraint, but only when running real PAB against testnet.

## Steps to reproduce

1. test [this](https://gist.github.com/hasufell/ba2789211ddbe2ca326be04444300230) on playground via lock-redeem
2. run [test suite](https://github.com/hasufell/proof-of-burn-cardano/tree/17e588b862cc9eddfd9d5d55821d5f014c591bda)
3. run [this](https://github.com/hasufell/proof-of-burn-cardano/tree/10f36345d0c0c03cbf57e6704295920c0f8a0d40) against testnet via PAB
4. Observe it failing due to missing signature

## Expected behavior

Either I get a failure in playground etc as well or the real wallet effect handler auto-adds current pubkey to `txInfoSignatories`. Probably the former.

## System info (please complete the following information):

- OS: Fedora 34
- v2021-11-05 pre-release

@migamake @iagon-tech

**Comment by hasufell** [comment]
Also related: https://github.com/input-output-hk/plutus-apps/issues/128

**Comment by ak3n** [comment]
I think it was fixed in #642. If not, please re-open.
