### ISSUE TITLE
PAB backend leaks memory

### ISSUE THREAD

**Issue by hasufell** [input-output-hk/plutus-apps#117]
## Summary

When you start a contract instance and call an endpoint that uses `awaitTxConfirmed` before the PAB backend has fully synced, the instance seems to:

1. never finish syncing
2. leak memory

I had a leak of 16gb memory. When built with profiling, I aborted the backend when it was at 5GB or so. It's possible that profiling had an impact on the issue.

## Steps to reproduce

1. clone [this contract](https://github.com/hasufell/proof-of-burn-cardano/tree/023e96401eec9c77837b1eec6b8b77745424d741)
2. start it up with node/wallet/chain-indexer etc
3. activate contract instance
4. lock a value before it's fully synced
5. observe it eating up memory

## Expected behavior

No memory leak.

## System info (please complete the following information):

- OS: Fedora 34
- Plutus version v2021-11-05

## Screenshots and attachments

Heap profiler shows `gmappend`.

![Screenshot_2021-11-16_18-58-37](https://user-images.githubusercontent.com/1241845/142041753-5ed4bb44-63be-443f-b443-4830d6b7e788.png)

@migamake @iagon-tech

**Comment by Yasuke** [comment]
Hello @hasufell thank you for the filing the issue, our team is currently investigating this, and hopefully this gets resolved soon.

**Comment by kk-hainq** [comment]
We experience constant memory leaks running the chain index for long durations as well. We'll create a new issue if these turn out to be unrelated.

**Comment by raduom** [comment]
This should be fixed, now.

**Comment by DavidEichmann** [comment]
@hasufell I noticed you're using the old profile rendering. I'd suggest you use the much nicer eventlog2html in the future :-) https://hackage.haskell.org/package/eventlog2html
