### ISSUE TITLE
Errors show up in the node logs when synchronising with the PAB.

### ISSUE THREAD

**Issue by raduom** [input-output-hk/plutus-apps#120]
## Summary

A clear and specific description of what the bug is.

When the PAB is synchronising to the chain the node outputs invalid network magic errors, even though the PAB seems to be synchronising.

```
[𝝺:cardano.node.LocalErrorPolicy:Error:65] [2021-11-17 12:01:27.83 UTC] IP LocalAddress "/tmp/node-server.sock@25" ErrorPolicyUnhandledApplicationException (HandshakeError (Refused NodeToClientV_4 "version data mismatch: NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 8}} /= NodeToClientVersionData {networkMagic = NetworkMagic {unNetworkMagic = 1097911063}}"))
```

## Steps to reproduce

Synchronise the PAB with a chain different from the testnet (alonzo-purple is an example).

## Expected behavior

No errors on the node side.

## System info (please complete the following information):

Not system dependent.

**Comment by raduom** [comment]
I think this is due to using a default value for the network magic rather than passing along the configuration / command line argument in the case of one of the connections to the node.

**Comment by bhoudebert** [comment]
Yes you are right the chain is starting with the wrong id, it seems you are running against testnet so

Let's align with something like this:
```shell
# using previous nix build
# nix build -f default.nix plutus-apps.haskell.packages.plutus-chain-index.components.exes.plutus-chain-index
./result/bin/plutus-chain-index --config chain-index-config.json start-index
```

chain-index-config.json
```
{
  "cicSlotConfig": {
    "scSlotLength": 1000,
    "scSlotZeroTime": 1596059091000
  },
  "cicPort": 9083,
  "cicSecurityParam": 2160,
  "cicSocketPath": path/to/node.socket,
  "cicDbPath": path/to/chain.db
  "cicNetworkId": {
    "contents": {
      "unNetworkMagic": 1097911063
    },
    "tag": "Testnet"
  },
  "cicStoreFrom": {
    "unBlockNo": 0
  }
}
```

You can also force info from command line something like this, which is less interesting imo:
```shell
./result/bin/plutus-chain-index --socket-path path/to/node.socket --db-path /path-to-chain/database --network-id 1097911063 start-index
```

It should suffice, warning so it is very very slow to sync
