### ISSUE TITLE
[How to] From simulator to real nodes with clients wallet

### ISSUE THREAD

**Issue by bhoudebert** [input-output-hk/plutus-apps#121]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[X] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

Let's say we are using the very simple Game contract available in plutus-apps or starter.

In a simulator mode we could have this

```haskell
correctGuessTrace :: EmulatorTrace ()
correctGuessTrace = do
  let w1 = knownWallet 1
      w2 = knownWallet 2
      secret = "secret"

  Extras.logInfo ("Wallet 1: " ++ Haskell.show w1)
  Extras.logInfo ("Wallet 2: " ++ Haskell.show w2)

  h1 <- Trace.activateContractWallet w1 (void $ lock @ContractError)
  void $ Trace.waitNSlots 1
  Trace.callEndpoint @"lock" h1 (LockParams secret (Ada.adaValueOf 10))

  h2 <- Trace.activateContractWallet w2 (void $ guess @ContractError)
  void $ Trace.waitNSlots 1
  -- Trace.callEndpoint @"guess" h2 (GuessParams secret)
  Trace.callEndpoint @"guess" h2 (GuessParams "amigos")
  void $ Trace.waitNSlots 1
```

Fine with emulator, it is working as expected, now let's use real thing like testnet with real wallets (real stuff, zero mock)

```Shell
# starting node wallet chain-index
# waiting for sync
cabal run ada-swap-pab -- --config pab-config.yml --passphrase=$WALLET_PAB_PASSPHRASE webserver
```
--> Therefore PAB is started with a wallet, provided with 1000 ADA here, wallet id is $WALLET_PAB_ID

Now we want to try to play this Game!

User 1 with $WALLET_USER_1 is willing to start
```shell
curl --location --request POST 'http://localhost:9080/api/contract/activate' \
--header 'Content-Type: application/json' \
--data-raw '{"caID":"GameContract","caWallet":{"getWalletId":$WALLET_USER_1}}'
```
This will not work at all, because pab is using passphrase (see above) against caWallet so it means we have to use $WALLET_PAB_ID. It is weird and do not seems to be close to simulator code `activateContractWallet` because in there you have the notion of activate.

If we replace $WALLET_USER_1 by $WALLET_PAB_ID, now a new contract instance is created but linked to PAB wallet (let's assume it is what we should do). As a result we got something like this
```
{
    "unContractInstanceId": $CONTRACT_INSTANCE_ID
}
```
Still from here there is no interaction with wallet $WALLET_USER_1 which is really odd (no signing, no identification)

User 1 (or Player 1) is willing now to lock his word to start playing and is willing to bet 2 ada on that:
```shell
curl --location --request POST 'http://localhost:9080/api/contract/instance/$CONTRACT_INSTANCE_ID/endpoint/lock' \
--header 'Content-Type: application/json' \
--data-raw '{
    "secretWord": "minstrel",
    "amount": {
        "getValue": [[{"unCurrencySymbol":""},[[{"unTokenName":""},2000000]]]]
    }
}'
```
-> Request accepted but again $WALLET_USER_1 is not used and regarding what we do in the simulator it is not correct at all. Therefore the ADA used are from $WALLET_PAB_ID and not $WALLET_CLIENT_1 (so the transaction is under PAB wallet)

Same issue would occurs with User 2 and his personal wallet. Rest of the code would not work either to send back funds to User 1 or User 2 regarding game issue.

Maybe I am missing a part but that is as far as I can go after reading whatever doc or code I could.

## Expectation

Provide a clear how to, description, real workflow with curl (etc) to produce the right behavior (like Emulator).

I am quite sure it would help everyone who wants to start working on smart contracts with PAB.

**Comment by kk-hainq** [comment]
This is definitely very critical. We'll try to help push both the setup and documentation forward.

**Comment by silky** [comment]
Does this help you - https://github.com/input-output-hk/plutus-apps/tree/main/plutus-pab/demo/pab-nami ? (Please re-open if not.)

We're working on putting together some richer examples.
