### ISSUE TITLE
Testnet activation contract hangs up

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus-apps#122]
I have succesfully run testnet example

When I try to run my contract on testnet it hangs on
`[pab:Info:46] [2021-11-18 10:12:13.89 UTC] Activated instance 4df05bde-2965-42cb-92e2-325e9748679a on W88cc0e4`

issue is similar to 
https://github.com/input-output-hk/plutus-apps/issues/98

Any suggestions how to trace it?

**Comment by silky** [comment]
you likely need to wait for the pab to emit the sync messages

**Comment by volodyad** [comment]
> you likely need to wait for the pab to emit the sync messages

I have next errors in cardano node, many of them

[WS-LV-CP:cardano.node.LocalErrorPolicy:Error:69] [2021-11-18 18:28:24.14 UTC] IP LocalAddress "testnet/node.sock@353" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 52> closed when reading data, waiting on next header True")

**Comment by volodyad** [comment]
It started, issue was, that nodeServerConfig.mscSocketPath point to not valid path and it just hand up forever.

Stille cardano logs is overloaded with error
`[WS-LV-CP:cardano.node.LocalErrorPolicy:Error:69] [2021-11-18 18:28:24.14 UTC] IP LocalAddress "testnet/node.sock@353" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 52> closed when reading data, waiting on next header True") `

**Comment by silky** [comment]
Thanks @volodyad 

Yes; there's certainly some improvements we can make to the verbosity of the errors :)
