### ISSUE TITLE
Improve Chain Index documentation

### ISSUE THREAD

**Issue by kk-hainq** [input-output-hk/plutus-apps#129]
## Area
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Describe the feature you'd like

We should write documentation for chain index setup, API, use cases, customization, and more. 

A good start is to add `openapi3` support to the RESTful endpoints, similar to https://github.com/input-output-hk/plutus/pull/3807. We can then write more textual documentation, from high-level guidelines to the details like tuning `cicStoreFrom` from `2877844` on the testnet, and `6236060` on the mainnet for Alonzo-only transactions, etc.

## Describe alternatives you've considered

We mostly infer things from the source code at the moment, which is not always convenient for developers in general.

## Additional context / screenshots

This issue is part of the #4 mega-thread.

**Comment by Yasuke** [comment]
@kk-hainq Thank you for the suggestion, we are making chain-index into a library and we will be documenting the features while doing so.

**Comment by kk-hainq** [comment]
@Yasuke Awesome, thank you! Let us know if we could help in any way.

**Comment by Yasuke** [comment]
Hey @kk-hainq It looks like #186 has laid the groundwork for separating chain-index out as a library, if you see anything obviously missing or aren't satisfied with the added documentation, we would definitely appreciate your input into the state of things.

**Comment by kk-hainq** [comment]
Documentation is hard and dangerous (my left wrist still screams carpal tunnel after our last documentation sprint) so I think we should take steps. We can help add more haddock to `plutus-chain-index`, `plutus-chain-index-core` and decorate their README(s) more, what do you think?

**Comment by Yasuke** [comment]
We would be happy to have your contribution @kk-hainq!

**Comment by kk-hainq** [comment]
Hang tight my right hand is already typing!

**Comment by kk-hainq** [comment]
This issue is outdated now. We'll open more documentation issues when it's more appropriate (architecture is finalized, code is refactored well enough, etc.).
