### ISSUE TITLE
Oracle.signMessage on testnet

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus-apps#135]
I need to implement oracle functionality
there is a package in plutus to support this https://github.com/input-output-hk/plutus-apps/blob/main/plutus-ledger/src/Ledger/Oracle.hs

it requires next private key format https://github.com/input-output-hk/plutus-apps/blob/main/plutus-ledger/src/Ledger/Crypto.hs
```
import Cardano.Crypto.Wallet qualified as Crypto
type PrivateKey = Crypto.XPrv
```

i have the following questions
1) How could I generate and start cardano-wallet to be able to extract signing and public key
2) There is lots of keys in the wallet (root, account, etc), which is used for is transaction signing
3) What is the approach to convert cardano wallet signing key to plutus private key
4) Are there any plans ti support signMessage, which will send payload to sign directly to the cardano wallet for signing, so there is no need to reexport the key?

**Comment by ak3n** [comment]
Well, it's better if oracle uses a different private key unrelated to the wallet. Ideally the signing would happen outside the PAB, and the PAB would just receive the already-signed message.
