### ISSUE TITLE
Strange behavior of toCardanoTxBody (missing datums)

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus-apps#139]
## Summary

I try to test my contracts with functions `toCardanoTxBody` and `evaulateTransactionExecutionUnits`.
I build Plutus `Tx` by hand and convert it to cardano `Tx` to use evaluation function. 

Something strange happens when I update datum from the input to output on the same address. 
It can not find datum by datum hash. The function that I use to create part of Tx that pays to script:

```haskell
-- | Pay to the script.
payToScript :: ToData (DatumType a) => TypedValidator a -> DatumType a -> Value -> Tx
payToScript tv dat val =
  mempty
    { txOutputs = [TxOut (validatorAddress tv) val (Just dh)]
    , txData = M.singleton dh datum
    }
  where
    dh = datumHash datum
    datum = Datum $ toBuiltinData dat
```

So it seems that I fill up `txData` and set up datum hash properly.
But when I use it in the code datum can only be found if it is the same as used in the inputs. If I change the datum validator can not find it in the outputs of TxInfo by hash although datum hash is present.
I tried to lookup how the function `toCardanoTxBody` works and I can see that it does not use `txData`.
Or maybe I miss something? 
Please can you explain how `txData` should be used in the Cardano `TxBody` properly so that I can continue with my testing?
or how it should be used in `toCardanoTxBody`?

As I understand Cardano Tx does not contain datum's and only hashes are used.
How can the datums be visible to `evaluateTransactionExecutionUnits`?

I've tried to include also output datums in the `UTxO` argument of `evaluateTransactionExecutionUnits` and it also can not find them :(

**Comment by anton-k** [comment]
As I understan Cardano `Tx` does not contain datum's and only hashes are used. 
How can the datums be visible to `evaulateTransactionExecutionUnits`?

**Comment by bhoudebert** [comment]
Hi, faced similar issue but only in offChain code.

100% working in simulator I got datum directly but when running against testnet only hash without any correspondence.

It could be related to a WIP on plutus/pab side.

**Comment by Yasuke** [comment]
Thank you for raising this issue, we have a goal to resolve these discrepancies on our roadmap, and after we get there we would expect to see the datum handled the same on both testnet and emulation.

**Comment by cstml** [comment]
This might offer some insight https://github.com/cardano-foundation/CIPs/pull/160. Currently, an eutxo on-chain doesn't contain the Datum itself, but only its hash.

**Comment by anton-k** [comment]
@cstml I'm aware of that. But we need to have some way to pass datums for validation. 
And after conversion they are present for inputs but not for outputs.
