### ISSUE TITLE
PAB Components not running

### ISSUE THREAD

**Issue by ganeshnithyanandam** [input-output-hk/plutus-apps#141]
## Summary

The PAB commands for psgenerator, migrate etc are not running. Gives message "cabal: The run command is for running executables, but the target 'plutus-pab' refers to the library plutus-pab from the package plutus-pab-0.1.0.0."

1. Clone https://github.com/input-output-hk/plutus-apps
2. Execute the steps in the readme (in a nix-shell) at https://github.com/input-output-hk/plutus-apps/tree/main/plutus-pab
3. Steps for pab-local-cluster works fine and integration test passes.
4. The subsequent steps give error. 

## Expected behavior

All commands and service should run successfully.

## System info (please complete the following information):

- OS: Ubuntu
- Version: 20.04
- plutus-apps release tag:  v2021-11-22 

## Screenshots and attachments

Logs:
[nix-shell:~/cardano/plutus-apps/plutus-pab]$ cabal run plutus-pab -- psgenerator
cabal: The run command is for running executables, but the target 'plutus-pab'
refers to the library plutus-pab from the package plutus-pab-0.1.0.0.

[nix-shell:~/cardano/plutus-apps/plutus-pab]$ cabal run plutus-pab -- migrate
cabal: The run command is for running executables, but the target 'plutus-pab'
refers to the library plutus-pab from the package plutus-pab-0.1.0.0.

[nix-shell:~/cardano/plutus-apps/plutus-pab]$ cabal run plutus-pab -- all-servers
cabal: The run command is for running executables, but the target 'plutus-pab'
refers to the library plutus-pab from the package plutus-pab-0.1.0.0.

![plutus-pab](https://user-images.githubusercontent.com/5955141/143240984-9420ffc2-cbbe-4c3d-ae9f-93f89844f56e.png)

## Additional context

Followed the readme step by step. In case this is related to how the commands need to be run, please advise.

**Comment by koslambrou** [comment]
You need to run the executable, not the library. 

`cabal run plutus-pab:exe:plutus-pab-examples -- webserver --config plutus-pab/plutus-pab.yaml.sample`

or

`cabal run plutus-pab:exe:plutus-pab-examples -- migrate --config plutus-pab/plutus-pab.yaml.sample`

**Comment by ganeshnithyanandam** [comment]
Thanks. The README seems to be amiss in that case. It would help the dev community if the insrtuctions to be followed can be made clear.
