### ISSUE TITLE
Are on-chain validator Integer comparing functions working correctly?

### ISSUE THREAD

**Issue by serxasz** [input-output-hk/plutus-apps#144]
In the validator, I have defined:
```
txInfo :: TxInfo
txInfo = scriptContextTxInfo ctx

feePaid :: Integer
feePaid = Ada.getLovelace (Ada.fromValue (txInfoFee txInfo))
```
the strange thing is, when I do:
```
traceIfFalse "fee test" (feePaid >= 0)
```
, it evaluates to True, but
```
traceIfFalse "fee test" (feePaid == 0)
```
and
```
traceIfFalse "fee test" (feePaid > 0)
```
evaluates to False! How is this possible? Am I doing something wrong?

The very same thing happens when using Plutus.V1.Ledger.Contexts functions.

For example valueProduced (of ADA, using valueOf, so getting Integer) - valueSpent (same, Integer) equates to true if using >= or <= operator, but is neither >, < or ==.

Evaluating using Emulator Trace.

valueProduced, valueSpent example:
```
test :: TxInfo -> Order -> Integer
test info ord = subtractInteger (valueOf (valueProduced info) (quoteAssetSymbol ord) (quoteAssetName ord)) (valueOf (valueSpent info) (quoteAssetSymbol ord) (quoteAssetName ord))
```
Order has quoteAssetSymbol which is of type CurrencySymbol and is ADA (""), quoteAssetSymbol is of type TokenName, and is also ADA ("").

Tried using greaterThanEqualsInteger, equalsInteger, etc.. Same result

**Comment by ak3n** [comment]
Thanks for the issue!

Could you please share the contract code? It's hard to say what might be wrong. I doubt integer functions work incorrectly. I guess `feePaid` changes each time. Have you tried to add three traces at one moment?

```
traceIfFalse "1" (feePaid >= 0) $
traceIfFalse "2" (feePaid == 0) $
traceIfFalse "3" (feePaid > 0)
```

**Comment by serxasz** [comment]
thanks for the quick response!
```
traceIfFalse "1" (feePaid >= 0) $
traceIfFalse "2" (feePaid == 0) $
traceIfFalse "3" (feePaid > 0)
```
gives me
```
Couldn't match expected type ‘Bool -> a0’ with actual type ‘Bool’
```
So I simplified code as much as possible. Off-chain contract script is definitely doing some spending/collecting (using a PAB new version release tag) with 
```
logInfo @Text $ "Provided script version: 1"
let tx = Typed.collectFromScript utxos Take
<> Constraints.mustPayToTheScript o quoteAsset
 txid <- fmap Ledger.getCardanoTxId (submitTxConstraintsSpending inst utxos tx)
 logInfo @Text $ "Tx id: " <> Text.pack (Haskell.show txid)
```
EmulatorTrace is:
```
make (knownWallet 1)
void $ Trace.waitUntilSlot 21
take (knownWallet 2)
```
and funds are being distributed correctly if I set validator = True (no conditions).
The validator script is:
```
{-# INLINABLE mkValidator #-}
mkValidator :: Order -> Order -> OrderAction -> ScriptContext -> Bool
mkValidator o _ act ctx =
    case act of
        Take ->
            traceIfFalse "fee test >=" (feePaid >= 0) &&
            traceIfFalse "fee test ==" (feePaid == 0) &&
            traceIfFalse "fee test >" (feePaid > 0)
        Collect ->
            traceIfFalse "Invalid owner public key" (txInfo `V.txSignedBy` oOwner o)
  where
    txInfo :: TxInfo
    txInfo = scriptContextTxInfo ctx

    feePaid :: Integer
    feePaid = Ada.getLovelace (Ada.fromValue (txInfoFee txInfo))
```
In case of:
```
traceIfFalse "fee test >=" (feePaid >= 0) &&
traceIfFalse "fee test ==" (feePaid == 0) &&
traceIfFalse "fee test >" (feePaid > 0)
it gives
Slot 00021: *** CONTRACT LOG: "Provided script version: 1"
Slot 00021: *** CONTRACT STOPPED WITH ERROR: "WalletError (ValidationError (ScriptFailure (EvaluationError [\"fee test >\",\"PT5\"] \"CekEvaluationFailure\")))"
Slot 00021: SlotAdd Slot 22

traceIfFalse "fee test >=" (feePaid >= 0) &&
traceIfFalse "fee test >" (feePaid > 0) &&
traceIfFalse "fee test ==" (feePaid == 0)
gives the same
Slot 00021: *** CONTRACT LOG: "Provided script version: 1"
Slot 00021: *** CONTRACT STOPPED WITH ERROR: "WalletError (ValidationError (ScriptFailure (EvaluationError [\"fee test >\",\"PT5\"] \"CekEvaluationFailure\")))"
Slot 00021: SlotAdd Slot 22

but

traceIfFalse "fee test >=" (feePaid >= 0) &&
traceIfFalse "fee test ==" (feePaid == 0)
or
traceIfFalse "fee test ==" (feePaid == 0)
gives
Slot 00021: *** CONTRACT LOG: "Provided script version: 1"
Slot 00021: W7ce812d: TxSubmit: 435b674a933539ff3f182ea5972994940cbb5e9965ae568d58e1203b556e25a0
Slot 00021: *** CONTRACT LOG: "Tx id: 435b674a933539ff3f182ea5972994940cbb5e9965ae568d58e1203b556e25a0"
Slot 00021: 00000000-0000-4000-8000-000000000002 {Contract instance for wallet 7ce812d7a4770bbf58004067665c3a48f28ddd58}:
Contract instance stopped (no errors)
Slot 00021: TxnValidationFail Phase2 435b674a933539ff3f182ea5972994940cbb5e9965ae568d58e1203b556e25a0: ScriptFailure (EvaluationError ["fee test ==","PT5"] "CekEvaluationFailure")
Slot 00021: SlotAdd Slot 22
```
On one case it accepts ==, on the other it doesn't. Note that logs are very different. in the second case, it throws error after tx was submitted. Now I see that I am clearly missing something. Is validator being called twice, or what is happening in this case? 

Can you point me to the right direction?

Thank you

**Comment by francolq** [comment]
We had the same issue. It is called twice. The first call is done "off-chain" to compute fees. In this call, txInfoFee is 0. The second call represents the actual submission of the balanced transaction, now including the obtained fee value in txInfoFee.

**Comment by manuimagine** [comment]
Seems it's difficult (maybe impossible?) to check anything about `txInfoFee` onchain, because the same code runs twice with different values for it, right?

**Comment by serxasz** [comment]
yep, that part where same code is being ran with different parameters is very confusing. As @francolq noted, having in mind that first call is for "off-chain" code, for the time being I am just skipping it (sorry for the parentheses):
```
(traceIfFalse "fee test for off-chain" (feePaid == 0)) ||
(traceIfFalse "fee test for on-chain" (feePaid > 0) &&
traceIfFalse "any other tests" (feePaid > 1))
```

Thanks for the help!

**Comment by serxasz** [comment]
yes, indeed. Tried to exclude first call from validation via some conditions, but failed. For me, the first call also has a fee value greater than zero, but it's different from the second call's parameters. @francolq maybe you can share how you overcame this using emulator? is skipping first call possible, or something like that?
Also will it work correctly on for example testnet?

**Comment by serxasz** [comment]
for the time being, this should skip the first call (sorry for parentheses):
```
(traceIfFalse "For off-chain validation call" (feePaid == 0)) ||
(traceIfFalse "Fee must be greater than 0" (feePaid > 0) &&
traceIfFalse "Incorrect length of outputs" outputsLengthCorrect &&
traceIfFalse "test value produced" (test txInfo o - feePaid == 0) &&
traceIfFalse "test value produced" (test txInfo o > 0))
```

Thank you for your answers

**Comment by francolq** [comment]
As @manuimagine said, we just understood that we don't have to do any check on txInfoFee. :)
