### ISSUE TITLE
Cannot run 'nix-shell' on Mac OSX

### ISSUE THREAD

**Issue by omefire** [input-output-hk/plutus-apps#150]
## Summary

I have cloned the repo and I am now trying to run `nix-shell`, but I get the following error:

```
> cd Projects/plutus-apps; nix-shell
/nix/store/zrz9si84rhdarqa8sqd9zi8n5m21wsw7-nopt-5.0.0.tgz
/nix/store/zwk0h77xwdbp01cf3lgrmzxnkfyh6v60-readable-0.3.1.tar.gz
/nix/store/zz2jj6v1j15y2w8pmm639z5rm0w7q8y9-are-we-there-yet-1.1.5.tgz
copying path '/nix/store/9y6ys981rs4lzn7airs34bvgiwklcfzh-aeson-qq-0.8.4.tar.gz' from 'https://cache.nixos.org'...
copying path '/nix/store/wc0sshipvsfzkaxhx221bnl84pk1fi2m-abstract-par-0.3.3.tar.gz' from 'https://cache.nixos.org'...
error: opening directory '/nix/store/pkbi8r18y95x5q4h76hq0mg0ak3fzmr0-pqueue-lib-pqueue-1.4.1.3-config': Too many open files
```

## Steps to reproduce

1. cd plutus-apps
2. nix-shell

## Expected behavior
It should build fine, and should not result in an error.

## System info (please complete the following information):

- OS: Mac OSX
- Version: Catalina
- Plutus version or commit hash: 7333e3c3ae62c955c5db7799dbf1c1f58593325d

**Comment by bhoudebert** [comment]
Did you have similar issue with other projects using Nix? I never has such issue when I was using Nix on a macbook but since I move to Arch, I cannot verify it.

To me it is not an issue related to plutus-apps, maybe more related to your Nix installation, you could try getting rid of your nix folder a do a fresh reinstall.

**Comment by ak3n** [comment]
@omefire sorry, I saw you comment in #82 but forgot to reply.

Please take a look if sandbox is enabled. If yes, try to disable. Maybe a fresh reinstall as @bhoudebert suggested.

**Comment by ak3n** [comment]
I'm closing this for now. Please feel free to reopen and to ask questions.
