### ISSUE TITLE
No instance for (Ord ThreadToken)

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus-apps#157]
On starting Pab 
`runWith (Builtin.handleBuiltin @Contracts)`
it gives compile error if thread token is a parameter
`No instance for (Ord ThreadToken)`

**Comment by ak3n** [comment]
Well, it means that you are trying to use `ThreadToken` somewhere and it requires `Ord` type class.

Also, please note that `StateMachine` at the moment is not usable on Test Net because of too big scripts size #11.

**Comment by volodyad** [comment]
> Well, it means that you are trying to use `ThreadToken` somewhere and it requires `Ord` type class.

For the moment just implement custom Ord

**Comment by ak3n** [comment]
Please try 9c0cf0255191a25297e4cabbec68fe9ba20b178d, it should work.
