### ISSUE TITLE
Run example on Alonzo Purple , cardano wallet sync forever

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus-apps#160]
I am trying to run example on the alonzo-purple network
cardano node build from last master
```
cabal exec cardano-node -- run \
    --config alonzo-purple/alonzo-purple-config.json \
    --topology alonzo-purple/alonzo-purple-topology.json \
    --database-path alonzo-purple/db \
    --socket-path alonzo-purple/node-server.sock \
    --port 3003
```

I have started cardano wallet via 
```
cabal exec -- cardano-wallet serve \
      --testnet alonzo-purple/alonzo-purple-byron-genesis.json \
      --node-socket alonzo-purple/node-server.sock 
```
It gives me the error 
`[cardano-wallet.pools-engine:Warning:45] [2021-12-01 15:07:59.46 UTC] Syncing (92.14% percent) Applied 0 blocks, 0 rollbacks in the last 30.000789s. Current tip is [point 6da22717 at slot 8190079]. (progress decreased)`

8190079 is last block in network 
https://explorer.alonzo-purple.dev.cardano.org/en/block?id=6da227172643387f26e2b95e7f8d781938a6084bc745fb5026134fa901bd5ef8

**Comment by silky** [comment]
The Purple network has now been discontinued!
