### ISSUE TITLE
User error The budget was overspent on testnet

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus-apps#161]
I have create a trnasaction which creates a token and send it to the script address with datum
I have received next error 

What could be the cause of this error?
`CekError An error has occurred:  User error:\\\\\\\\nThe budget was overspent. Final negative state: ({ cpu: -7904 | mem: 0 }`

`[pab:Warning:8000] [2021-12-02 09:20:27.57 UTC] WalletClientError "FailureResponse (Request {requestPath = (BaseUrl {baseUrlScheme = Http, baseUrlHost = \"localhost\", baseUrlPort = 8090, baseUrlPath = \"\"},\"/v2/proxy/transactions\"), requestQueryString = fromList [], requestBody = Just ((),application/octet-stream), requestAccept = fromList [application/json;charset=utf-8,application/json], requestHeaders = fromList []), requestHttpVersion = HTTP/1.1, requestMethod = \"POST\"} (Response {responseStatusCode = Status {statusCode = 500, statusMessage = \"Internal Server Error\"}, responseHeaders = fromList [(\"Transfer-Encoding\",\"chunked\"),(\"Date\",\"Thu, 02 Dec 2021 09:20:27 GMT\"),(\"Server\",\"Warp/3.3.17\"),(\"Content-Type\",\"application/json;charset=utf-8\")], responseHttpVersion = HTTP/1.1, responseBody = \"{\\\"message\\\":\\\"The submitted transaction was rejected by the local node. Here's an error message that may help with debugging: TxValidationErrorInMode (ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (UtxosFailure (ValidationTagMismatch (IsValid True) (FailedUnexpectedly [PlutusFailure \\\\\\\"\\\\\\\\nThe 2 arg plutus script (PlutusScript ScriptHash \\\\\\\\\\\\\\\"fba5fc2b1872cd510324d2b0915b8158ceafb90e57ded9ccb4885135\\\\\\\\\\\\\\\") fails.\\\\\\\\nCekError An error has occurred:  User error:\\\\\\\\nThe budget was overspent. Final negative state: ({ cpu: -7904 | mem: 0 })\\\\\\\\nThe redeemer is: Constr 0 []\\\\\\\\nThe context is:\\\\\\\\nPurpose: Minting fba5fc2b1872cd510324d2b0915b8158ceafb90e57ded9ccb4885135\\\\\\\\nTxInfo:\\\\\\\\n  TxId: 53e76cc13bbb9a2918596b5757df2b6fcc9ad831287746d462ae3978f57fb2ea\\\\\\\\n  Inputs: [ 49ec84d56343988e4c794031476bf3d53263da989d65f96d9a3f9fae6847670f!0 -> - Value (Map [(,Map [(\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",1000000000)])]) addressed to\\\\\\\\n                                                                                    addressed to PubKeyCredential: a8db20fe9592b7e0ef9efa0a56a70b5e384c5d21cb4939adc9e8e3f8 (StakingHash PubKeyCredential: a59b25cb163a2dfe6a8231a756c849f780fdec9b85d8af7634cf7bb6) ]\\\\\\\\n  Outputs: [ - Value (Map [(,Map [(\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",2000000)]),(fba5fc2b1872cd510324d2b0915b8158ceafb90e57ded9ccb4885135,Map [(\\\\\\\\\\\\\\\"oracleRequestTokenName\\\\\\\\\\\\\\\",1)])]) addressed to\\\\\\\\n               addressed to ScriptCredential: 3189c91a3b436de86a6ae3719837a11db8f0b17a2ffb81f5b02cc659 (no staking credential)\\\\\\\\n           , - Value (Map [(,Map [(\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",2000000)])]) addressed to\\\\\\\\n               addressed to PubKeyCredential: 519ccb9453513f5165a661281819dbb487581a25cba373c6d51bcd8c (no staking credential)\\\\\\\\n           , - Value (Map [(,Map [(\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",498105612)])]) addressed to\\\\\\\\n               addressed to PubKeyCredential: f35b7abd78a6b544afb3491508d763e22b9b7fa858830ac926a53d08 (StakingHash PubKeyCredential: a59b25cb163a2dfe6a8231a756c849f780fdec9b85d8af7634cf7bb6)\\\\\\\\n           , - Value (Map [(,Map [(\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",497215291)])]) addressed to\\\\\\\\n               addressed to PubKeyCredential: 3d0b83c031b20ea35ec557668cca993aaf8e694f1bda264e03197148 (StakingHash PubKeyCredential: a59b25cb163a2dfe6a8231a756c849f780fdec9b85d8af7634cf7bb6) ]\\\\\\\\n  Fee: Value (Map [(,Map [(\\\\\\\\\\\\\\\"\\\\\\\\\\\\\\\",679097)])])\\\\\\\\n  Value minted: Value (Map [(fba5fc2b1872cd510324d2b0915b8158ceafb90e57ded9ccb4885135,Map [(\\\\\\\\\\\\\\\"oracleRequestTokenName\\\\\\\\\\\\\\\",1)])])\\\\\\\\n  DCerts: []\\\\\\\\n  Wdrl: []\\\\\\\\n  Valid range: (-\\\\\\\\8734 , +\\\\\\\\8734)\\\\\\\\n  Signatories: []\\\\\\\\n  Datums: []\\\\\\\\n\\\\\\\" \\\\\\\"hZ8aAAMCWQABARoABgvHGQJtAAEaAAJJ8BkD6AABGgACSfAYIBoAJc6oGXH3BBl0TRhkGXRNGGQZdE0YZBl0TRhkGXRNGGQZdE0YZBhkGGQZdE0YZBoAAknwGCAaAAJJ8BggGgACSfAYIBoAAknwGQPoAAEaAAJJ8BggGgACSfAZA+gACBoAAkIgGgAGfiMYdgABARoAAknwGQPoAAgaAAJJ8BoAAbeYGPcBGgACSfAZJxABGgACFV4ZBS4BGQPoGgACSfAZA+gBGgACSfAYIBoAAknwGCAaAAJJ8BggAQEaAAJJ8AEaAAJJ8AQaAAGUrxj4ARoAAZSvGPgBGgACN3wZBVYBGgACveoZAfEBGgACSfAYIBoAAknwGCAaAAJJ8BggGgACSfAYIBoAAknwGCAaAAJJ8BggGgACQiAaAAZ+Ixh2AAEBGfBMGSvSAAEaAAJJ8BggGgACQiAaAAZ+Ixh2AAEBGgACQiAaAAZ+Ixh2AAEBGgAlzqgZcfcEABoAAUG7BBoAAknwGROIAAEaAAJJ8BggGgADAlkAAQEaAAJJ8BggGgACSfAYIBoAAknwGCAaAAJJ8BggGgACSfAYIBoAAknwGCAaAAJJ8BggGgAzDacBAf+CGgA+2c4aT2j7xVkOglkOfwEAADMjIyMyIzIjIzMiIyMjIyMzIiMjIzMyIiMjMiMyIyMjIyMjMyIjMyIjIyMyIyMjMyIjMyIjMzMzMiIiIiMzMiIjMiMyIzIjMiMyIzIjMiMyIyMjIyMjMiMjIyMjIyMjIyMjIyMjMzMiIiMyIiMiMjJTNTBnMyIyMjUwCwAyI1MCgAIiIiIiIlMzNTAZALIWIVM1MF4BETMFVJEXU2hvdWxkIHJlZGVlbSBvbmUgdG9rZW4AMzUGEHUzMC8wMlAOUA9IgRZvcmFjbGVSZXF1ZXN0VG9rZW5OYW1lAEgARMwdzMFVJAEWU2hvdWxkIGZvcmdlIG9uZSB0b2tlbgAzNQYQdTMwLzAyUA5QD0iBFm9yYWNsZVJlcXVlc3RUb2tlbk5hbWUASACMwdzMFVJBGUlzIGZvcmdlZCB3aXRoIGNvbGxhdGVyYWwAM1UIABM1VQYlBZM1UFowcBIAEjM1BiUGQwMQATMiM1UwchIAEjU1UGwAEiM1UG8AIzVTB1EgASNTVQbwASIzVQcgAjM1NVB0ABIzCLAUgAAASIzCMAQAgASMwiwEAFIAAAEzBnACABMzIiM1B2M1UG0AMzUHYzVQbQAgAVB3UHdQEEiBFm9yYWNsZVJlcXVlc3RUb2tlbk5hbWUASACM1UIEBBXNTBYAYIiABMDFQDjMFVJBC0lzIGZlZSBwYWlkADNVCAATNVUGJQWTNVBaMHASABIzB4MzUGJQZDAxABM1UIEBBXNTBYAYIiACMzUGIiUzU1BeACIVM1NQXwAiEzB5ACABEH0VM1NQXgASEH0QfTNVCBAVBeNTBYAYIiADNTA4ABIiNTA9ADIjNTBYACI1BkABJQYzAxUA4hYhYTUwCgAiIAITUwCQASJTMzUwDQASE1AiNTAgM1c4kgECTGgAAhSYhABITUCI1MCAzVziSQJMaAACFJiE1AiNTAgM1c4kgQJMaAACFJjMzVzRm4dQBEgAiBQIzM1c0ZuHUAVIAAgUCNQHzUwHTNXOJIEDUFQxAAHkmSZJjMzVzRm4c1VzqgBJAAEZgEmRkZGRkZGRkZGRkZmauaM3DmqudUApIAAjMzMzMzAwM1AbIyMjMzVzRm4c1VzqgBJAAEZgbGBIauhUAIwIDV0Jq6JQAiNQLjUwLDNXOJIBA1BUMQAC1JkmE1VzygAibqgATV0KgFGagNgOGroVAJMzVQHnXKA6auhUAgzNVAedcoDpq6FQBzNQGwJDV0KgDGagNmaqBOBK601dCoApkZGRmZq5ozcOaq51QAkgACM1A+MjIyMzNXNGbhzVXOqAEkAARmoIxmoFTrTV0KgBGBWauhNXRKAERqBkamBgZq5xJAEDUFQxAAMUmSYTVXPKACJuqABNXQqAEZGRkZmauaM3DmqudUAJIAAjNQRDNQKnWmroVACMCs1dCauiUAIjUDI1MDAzVziSAQNQVDEAAxSZJhNVc8oAIm6oAE1dCauiUAIjUC41MCwzVziSAQNQVDEAAtSZJhNVc8oAIm6oAE1dCoAhmoDbrjV0KgBmagNmaqBO64gATV0KgBGBCauhNXRKAERqBUamBQZq5xJBA1BUMQAClJkmE1dEoAImrolABE1dEoAImrolABE1dEoAImrolABE1dEoAImrolABE1VzygAibqgATV0KgBGRkZGZmrmjNw6gApADEYCRgOGroTVXPKAGRmZq5ozcOoASQAhGAiYDxq6E1VzygCEZmauaM3DqAGkAERgImA0auhNVc8oApGZmrmjNw6gCJAAEYChuuNXQmqueUAYjUCU1MCMzVziSAQNQVDEAAkSZJkmSZJhNVc6oAIm6oAE1dCauiUAIjUB41MBwzVziSQNQVDEAAdSZJhAcE1AdNTAbM1c4kgEDUFQ1AAHEmE1VzygAibqgARNVc6bqgASISMwAQAwAiABISIiMAQAUhIiIwAwBSEiIjACAFISIiMAEAUgARIyIwAjdYACZAAmqgyERmZqrnwASUFgjNQVzAENXQgBGAGauiACARIyMjIzM1c0ZuHNVc6oAaQABGZgOmRkZGZmrmjNw5qrnVACSAAIzAjMBM1dCoARmoBgCRq6E1dEoARGoC5qYCpmrnEkBA1BUMQABZJkmE1VzygAibqgATV0KgBmZqoA7rlAGNXQqAEZqAQ641dCauiUAIjUBM1MBEzVziSEDUFQxAAEkmSYTV0SgAiaq55QARN1QAImaqAC651oiRGRGAEbqwATIAE1UGIiMjMzVXPgBEoK5GagrGaqCaYAxqrnVACMAU1VzygBGAIauiADAQE1dCACJEZGRmZq5ozcOoAKQABGoH5gCmroTVXPKAGRmZq5ozcOoASQARKB+RqAiamAeZq5xJAEDUFQxAAEEmSZJhNVc6oAIm6oAEjIyMzNXNGbhzVXOqAEkAARmA4YApq6FQAjdaauhNXRKAERqAcamAYZq5xJBA1BUMQAA1JkmE1VzygAibqgASMjMzVzRm4c1VzqgApAAEbrjV0JqrnlACI1AMNTAKM1c4kkDUFQxAAC0mSYTdUACJEZGRmZq5ozcOoAKQAhKBGRmZq5ozcOoASQARGoExgDGroTVXPKAIRmZq5ozcOoAaQABKBMRqAeamAaZq5xJAQNQVDEAAOSZJkmSYTVXOqACJuqABIyMzNXNGbh1ABSACIFYjMzVzRm4dQAkgACBWI1ALNTAJM1c4kkDUFQxAACkmSZJhNVc6bqgASMjIyMjIzM1c0ZuHUAFIAwgKSMzNXNGbh1ACSAKICsjMzVzRm4dQA0gCCMwKTdcauhUAU3WmroTV0SgCkZmauaM3DqAIkAMRmBWbrjV0KgDm641dCauiUAcjMzVzRm4dQBUgBCMwMDAMNXQqASbrjV0Jq6JQCSMzNXNGbh1AGSACIwMjANNXQmqueUAsjMzVzRm4dQB0gACMDEwDjV0JqrnlAMI1ATNTARM1c4kgQNQVDEAASSZJkmSZJkmSZJhNVc6oAgmqueUAMTVXPKAEJqrnlABE3VAAkZGRkZGZmrmjNw6gApABEZmBabrTV0KgCG601dCoAZutNXQmrolADIzM1c0ZuHUAJIAAjAvMAg1dCaq55QBiNQDDUwCjNXOJIEDUFQxAAC0mSZJhNVc6oAYmrolABE1VzygAibqgASMjIzM1c0ZuHUAFIAIjAtN1xq6E1VzygBkZmauaM3DqAEkAARgXm641dCaq55QBCNQCTUwBzNXOJIBA1BUMQAAhJkmSYTVXOqACJuqABESIjIyMzNXNGbhzVXOqAEkAARmqgiGAMauhUAIwBTV0Jq6JQAiNQCTUwBzNXOJIQNQVDEAAISZJhNVc8oAIm6oAESABIAESYiIyMjABAFMgATVQVyIzU1BIABSAAIjU1UEEAIiUzUwUzM1c0ZuPACAJBVBUEwBwARMAYAMyABNVBWIjNTUEcAFIAAiNTVQQAAiJTNTBSMzVzRm48AIAcFQFMQARMAYAMjUwCAASIgAiNTADABIiIiIiIAkjUwAgASIiIiIiAHIiIiIiISMzMzMzMAEAsAoAkAgAcAYAUAQAMAIgASISMwAQAwAiABIiEjMwAQBAAwAiABIhIzABADACIAEiEjMAEAMAIgARIhIzABADACEgARIhIzABADACEgARIhIzABADACEgARISIjADAEESIgAhEiIAESABISIiIiMAcAgiEiIiIjMAYAkAghIiIiIwBQCBIiIiIAQSIiIiADIhIiIiIzACAJAIIhIiIiIzABAJAIIAEhIjACADIiEiMzABAFAEADIAEhIjACADISIwAQAyABIlM1MCUAEQJxM1c4AEBMRmoDpmqgKJEEAM1AdM1UBRIkAABUB5QHiIhIzMAEAQAMAIgARJTNTUAMAEhAjECERIiMgATM1UAMzUCYiUzU1AGACIQAxABUAUlM1MCIwAwARNQBwARUAYAESEiMAIAMRIgARIAESIAISIAEgARIAEREiIwAzACABEiMzVTAPEgATUBpQFSNTVQCAASIzNVMBISABNQHVAYI1NVALABIjM1NVAQABIzAbSAAABIjMBwAIAEjMBsAFIAAAEzADACABIjNVMA0SABI1NVAHABIjNVAKACMzU1UAwAEjNVMBESABI1NVALABIjNVAOACNVATABABIjM1VQCAFwAgASM1UwERIAEjU1UAsAEiM1UA4AI1UBEAEAEzNVUAMBIAIAEREiIzNVMAgSABUBAzVTANEgASNTVQBwASIzVQCgAjVQDwATM1UwCBIAEiNTVQCAAiJTNTAaMzVTASEgATIzUCAiMzU1ALADIgAgAgATU1AJABIgATNQCSJTNTAcACEB4QAQGyNTVQCwASIzAKACAFAGEAMTNQFABAA1ARABM1UwDRIAEjU1UAcAEiMjNVALADMAEAUyABNVAjIlM1NQFAARNVAPADIhNTVQDQAiJTNTAfMwDAAgCBM1UBQAcAETAGADACEiEjMAEAMAISABESISMwAQAwAhEgATIAE1UBgiESIlM1NQDAARACIhMwBQAjM1UwBxIAEAUAQAERISIjADAEESISIjMAIAUAQRISIjABAEESABMgATVQEyIRIlM1NQBgARUAgiEzUAkwBAAjNVMAYSABAEABMgATVQEiIRIiUzU1AGABE1NQEQAyIAEiEzNTUBMAUiACMAQAIzNVMAcSABAFAEABESIAISISIzABAEADEgASIzNXNGbjwAgAQCAByIzNXNGbhwAgAQBwBhM1AJABAEIlM1MAMAIQARAEEiACEiABIAESM1ADIjM1NQBgAyIAIAIAE1NQBAASIAESISMwAQAwAhIAESISMwAQAwAhIAERIjACABIjNwAAQAIiRkYAIAJEZgBmAEAEACZkRmYASREcUZzLlFNRP1FlpmEoGBnbtIdYGiXLo3PG1RvNjABIICS9AFIICS9AEiISMzABAEADACIAEZ/YeYDYeZ/YeZ+f2Hmf2Hmf2HmfWCBJ7ITVY0OYjkx5QDFHa/PVMmPamJ1l+W2aP5+uaEdnD/8A/9h5n9h5n9h5n1gcqNsg/pWSt+DvnvoKVqcLXjhMXSHLSTmtyejj+P/YeZ/YeZ/YeZ9YHKWbJcsWOi3+aoIxp1bISfeA/eybhdivdjTPe7b/////oUChQBo7msoA2HqA////n9h5n9h5n9h6n1gcMYnJGjtDbehqauNxmDehHbjwsXov+4H1sCzGWf/YeoD/okChQBoAHoSAWBz7pfwrGHLNUQMk0rCRW4FYzq+5Dlfe2cy0iFE1oVZvcmFjbGVSZXF1ZXN0VG9rZW5OYW1lAdh5n1ggLMpCs8ogXe/DZ65jgkvD9DuXCz9i7vm71BbhmbTZzJL//9h5n9h5n9h5n1gcUZzLlFNRP1FlpmEoGBnbtIdYGiXLo3PG1RvNjP/YeoD/oUChQBoAHoSA2HqA/9h5n9h5n9h5n1gc81t6vXimtUSvs0kVCNdj4iubf6hYgwrJJqU9CP/YeZ/YeZ/YeZ9YHKWbJcsWOi3+aoIxp1bISfeA/eybhdivdjTPe7b/////oUChQBodsH0M2HqA/9h5n9h5n9h5n1gcPQuDwDGyDqNexVdmjMqZOq+OaU8b2iZOAxlxSP/YeZ/YeZ/YeZ9YHKWbJcsWOi3+aoIxp1bISfeA/eybhdivdjTPe7b/////oUChQBodouc72HqA//+hQKFAGgAKXLmiQKFAAFgc+6X8KxhyzVEDJNKwkVuBWM6vuQ5X3tnMtIhRNaFWb3JhY2xlUmVxdWVzdFRva2VuTmFtZQGAgNh5n9h5n9h5gNh6gP/YeZ/Ye4DYeoD//4CA2HmfWCBT52zBO7uaKRhZa1dX3ytvzJrYMSh3RtRirjl49X+y6v//2HmfWBz7pfwrGHLNUQMk0rCRW4FYzq+5Dlfe2cy0iFE1////AA==\\\\\\\"])))))])) AlonzoEraInCardanoMode\\\",\\\"code\\\":\\\"created_invalid_transaction\\\"}\"})"`

**Comment by ak3n** [comment]
Thanks for the issue!

Have you tried to change the memory and cpu usage with `cardano-cli`? Please take a look at https://cardano.stackexchange.com/questions/4702/the-plutus-script-evaluation-failed

**Comment by volodyad** [comment]
I am runing from PAB, is there options to change this props in PAB?

**Comment by volodyad** [comment]
What are the limits of testnet
in https://hydra.iohk.io/build/7189190/download/1/testnet-alonzo-genesis.json
it has 
`"maxTxExUnits": {
        "exUnitsMem": 10000000000,
        "exUnitsSteps": 10000000000
    },`

I have run plutus-use-cases-scripts with my transaction and it returns

```
Writing script: ./tmp/oracle-1.flat (Size: 4.3kB, Cost: ExCPU 1429004281, ExMemory 4452694)
Total Size: 4.3kB, Cost: ExCPU 1429004281, ExMemory 4452694
1429004281 < exUnitsSteps
```
1429004281 is less then exUnitsMem,
or this error relates to other parameters?

**Comment by ak3n** [comment]
Oh, I just got the same problem and have no idea how to fix that yet. I have tried to increase the limits but no effect.

Have you tried to delete db and run node sync from start?

**Comment by ak3n** [comment]
The problem on my side was an incorrect `cardano-node` version.

Please try `1.31.0` version. There is a binary available to download here https://hydra.iohk.io/build/9124058

**Comment by volodyad** [comment]
Are there any plans to update plutus-apps dependency to latest cardano-node
current commit hash in plutus apps is very old
```
commit b6ca519f97a0e795611a63174687e6bb70c9f752 (HEAD)
Merge: c7d0f38e7 08cb5d50c
Author: iohk-bors[bot] <43231472+iohk-bors[bot]@users.noreply.github.com>
Date:   Fri Oct 22 12:10:23 2021 +0000
```
What about caradno-wallet? should I try latest one?

**Comment by ak3n** [comment]
I think you should try to run the PAB with current dependencies against `cardano-node-1.31.0`. If it won't work then I guess it means we should bump the pin.

**Comment by volodyad** [comment]
Cannot run due to
#189

**Comment by ak3n** [comment]
Okay, thanks, will take a look. Closing this one as it seems the correct version of cardano-node fixes the problem.

**Comment by jankun4** [comment]
For me `cardano-node-1.31.0` didn't fix the problem.

**Comment by volodyad** [comment]
> For me `cardano-node-1.31.0` didn't fix the problem.

Same for me

**Comment by alegadea** [comment]
Hi everyone!

I started getting this error after I updated my instances of the cardano-node to the 1.33 version, also I'm using the last tag of plutus-apps ([v2022-01-17](https://github.com/input-output-hk/plutus-apps/releases/tag/v2022-01-17)). Any ideas of what the source of the problem might be?

`The budget was overspent. Final negative state: ({ cpu: -1729 | mem: 0 })`

**Comment by manuimagine** [comment]
Getting the same error too.

**Comment by ak3n** [comment]
Sorry, we are waiting for `cardano-wallet` to update the dependencies. Then it will be `plutus-apps`'s turn.

**Comment by Benjmhart** [comment]
@ak3n why is this ticket closed if plutus-apps is going to update in order to resolve it?

**Comment by ak3n** [comment]
@Benjmhart I closed this ticket when I had the same problem and the solution I found was to run the correct cardano-node version that matches PAB (a general solution but maybe I'm wrong and there are other reasons why this error may occur).

I think we can't use the same ticket for all problems with mismatching versions because the information will become obsolete over time. If someone is having this problem it might be better to open a new issue specifying plutus-pab pin and other dependencies so we can distinguish them. Maybe I'm wrong.

Maybe a better general solution would be to make PAB more user-friendly by reporting the supported cardano-node version. Or something like that.

**Comment by Benjmhart** [comment]
@ak3n Is there a ticket for the current effort then?   That ticket should be cross-linked here at the very least.

**Comment by gege251** [comment]
@ak3n We are using `evaluateScriptCounting` directly to calculate the execution units, based on the way it was presented in the [Alonzo exercises](https://github.com/input-output-hk/Alonzo-testnet/blob/main/resources/plutus-sources/plutus-alwayssucceeds/app/plutus-alwayssucceeds.hs#L32), but we're having issues with budget overspent error (mostly with minting policies). We've already updated and synchronised the plutus and cardano-node version, but the problem persists.
I wanted to test whether we experience the same issue using PAB or is it a problem on our side, but I couldn't make time for it yet.
Now we're working on an alternative solution for our library, using cardano-api, that seems to return the correct execution units.
Would it be possible to use cardano-api in Plutus as well? Also, I'm just wondering if we could add some unit tests for this function?

**Comment by ak3n** [comment]
@gege251 can you please provide a link to a solution from `cardano-api`?

>Would it be possible to use cardano-api in Plutus as well? Also, I'm just wondering if we could add some unit tests for this function?

Not sure. `evaluateScriptCounting` is a part of `plutus`, not even `plutus-apps`, and `plutus` doesn't depend on `cardano-node` repo anymore. We could use something from `cardano-api` I suppose.

**Comment by gege251** [comment]
@ak3n Could we have `cardano-node` as a dependency for the tests? We could then test the result of `evaluateScriptCounting` against the result of `evaluateTransactionExecutionUnits` from `cardano-api`
