### ISSUE TITLE
PAB not synchronizing with chain-index for testnet

### ISSUE THREAD

**Issue by kelizarov** [input-output-hk/plutus-apps#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

After launching all necessary components of `cardano-node`, `cardano-wallet` and `plutus-chain-index` and making sure that node's and chain-index's tip are synced with the testnet, the PAB process just hangs indefinetly without printing any messages that it is synced or being synced with chain-index.

The instruction were followed as described [here](https://github.com/input-output-hk/plutus-apps/blob/main/plutus-pab/test-node/README.md) with only difference that cardano-node and cardano-wallet executables were downloaded from hydra.

### Steps to reproduce the behavior

1. Launch `cardano-node`, `cardano-wallet` and `plutus-chain-index` as described in [instruction](https://github.com/input-output-hk/plutus-apps/blob/main/plutus-pab/test-node/README.md)
2. Wait until everything is synced with the testnet.
2. Launch PAB with test contract.

### Actual Result

PAB does not print messages about sync with chain-index. It only prints first 3 messages.
```
[pab:Info:4] [2021-12-06 06:59:37.95 UTC] Restoring PAB state ...
[pab:Info:4] [2021-12-06 06:59:37.95 UTC] No constract instance were restored in the PAB state.
[pab:Info:4] [2021-12-06 06:59:37.95 UTC] Starting PAB backend server on port 9080
```

### Expected Result

PAB starts printing messages like this
```
...
Current block: 327295. Current slot: 41749136.
Current block: 327295. Current slot: 41749150.
```

### What have you tried to resolve this issue?

Tried clean setup of cardano-node DB. 
Restarted PAB with removed DB file that it creates.
Tried latest revision of plutus-apps at `main`

### Checked our docs?

- [X] Yes, I have looked in the the readme, plutus docs, and technical report for help on this issue.

### Checked Stack Exchange?

- [X] Yes, I have searched Stack Exchange for this issue and it doesn't exist.
- [X] I have considered raising this issue in Stack Exchange.

### System info

Versions that were used:
```
cardano-node --version
cardano-node 1.30.1 - darwin-x86_64 - ghc-8.10
git rev 0fb43f4e3da8b225f4f86557aed90a183981a64f

cardano-wallet version
v2021-11-11 (git revision: dac16ba7e3bf64bf5474497656932fd342c3b720)
```

for plutus-apps I've used `plutus-starter-devcontainer/v1.0.14` tag.

My machine is MacOS 12.0.1 (21A559)

**Comment by kelizarov** [comment]
I also noticed: when I try to launch PAB with prepared chain-index the cardano-node shows these messages:
![image](https://user-images.githubusercontent.com/7036666/145017312-e5df3c90-208c-4acd-abe9-066323659661.png)

**Comment by Yasuke** [comment]
Hey @kelizarov thank you for your submission, I will take a look into your synchronization issue.

**Comment by raduom** [comment]
What exactly is the synchronisation issue?
a) It takes too much time? - Currently implementing a workaround.
b) It takes too much RAM? - Currently implementing a workaround.
c) No feedback on the PAB synchronisation with the node.

**Comment by kelizarov** [comment]
Hey,

1. I haven't reached the completion. In the tutorial they've mentioned that PAB instance should have been logging the sync status, like this:
```
...
Current block: 327295. Current slot: 41749136.
Current block: 327295. Current slot: 41749150.
```
but I've haven't seen it.
2. Yes, I've left PAB running over-night and the instance consumed over >10Gbs of RAM.
3. The cardano-node has been producing errors like in the attached screenshot I've posted earlier here.

**Comment by raduom** [comment]
1. We will look into it.
2. We will have a tentative fix for that, probably this week.
3. We are also looking into that so it will be fixed soon.

**Comment by kelizarov** [comment]
> I also noticed: when I try to launch PAB with prepared chain-index the cardano-node shows these messages:
> ![image](https://user-images.githubusercontent.com/7036666/145017312-e5df3c90-208c-4acd-abe9-066323659661.png)

Can anyone tell me the reason what could cause these logs when launching PAB? I'm still getting it with `v2021-12-20` version.

**Comment by raduom** [comment]
It may be connected to: https://github.com/input-output-hk/plutus-apps/issues/120. A fix for it is in the works and it will probably be merged at the beginning of next year.

**Comment by kelizarov** [comment]
Can confirm that PAB works with `fd9e2f0ede0b476dcfac1f7c71f2377b4002e6b6 ` commit. `pabRollbackHistory` helps to ease the synchronisation process.
