### ISSUE TITLE
`Arbitrary Datum` produces infinitely* large data structures

### ISSUE THREAD

**Issue by Renegatto** [input-output-hk/plutus-apps#172]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

`arbitrary` method of `Arbitrary Datum` instance generates infinitely* large `Datum`s with very high probability (more than `0.3` i guess), that require corresponding amount of memory.

(*) - possibly, didn't have infinite amount of time to ensure

### Steps to reproduce the behavior

1. Run following code:
```haskell
import Test.QuickCheck qualified as QC
import Ledger qualified
import Plutus.PAB.Arbitrary ()

main = print =<< QC.generate (QC.arbitrary :: QC.Gen Ledger.Datum)
```

### Actual Result

Infinitely large Datum printing to the console.

### Expected Result

Some finite, likely small Datum data structure prints out.

### What have you tried to resolve this issue?

After my property-based tests were hang because of `arbitrary @Datum` call, I tried out to look what it generates by printing it out. Printing process took more than 10 minutes and didn't stop.

### Checked our docs?

- [X] Yes, I have looked in the the readme, plutus docs, and technical report for help on this issue.

### Checked Stack Exchange?

- [X] Yes, I have searched Stack Exchange for this issue and it doesn't exist.
- [X] I have considered raising this issue in Stack Exchange.

### System info

OS: Ubuntu 
Version: 20.04
Plutus: 3f089ccf0ca746b399c99afe51e063b0640af547
plutus-apps: 404af7ac3e27ebcb218c05f79d9a70ca966407c9

**Comment by kozross** [comment]
This issue stems from use of `generic-arbitrary`, which doesn't work correctly on recursive structures. This is a common mistake: you have to _manually_ bound the recursion using the size parameter provided by QuickCheck.

**Comment by Yasuke** [comment]
Hello @Renegatto, I have reviewed this issue and created a PR that will fix this. Thank you for your issue, and thank you @kozross for the insight. When the PR is merged your issue will be resolved.

**Comment by kozross** [comment]
It is probably worth going over any other `Arbitrary` instances of recursive types and fixing this problem if it exists.
