### ISSUE TITLE
Separate ToSchema from PAB usage

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus-apps#19]
## Area

[X] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Describe the feature you'd like

ToSchema seems to be useful only for Playground, and provides support for user to input data in the web-interface.
Also PAB is useful on it's own in the headless-mode. When we can run servant server.
Often one or another data type can not be made instance of ToSchema, because it does not support Sum-types
(only sum of constants is supported right now0.

I wonder is it possible to create functional PAB in headless node without requirement for ToSchema instance for it's inputs.
If we are going to use it with cli-executable that can create JSON-values.

So is it possible to relax requirement of PAb from ToSchema down to ToJSON?
it can be super useful to create custom cli-executables.

**Comment by koslambrou** [comment]
Closing as solved in https://github.com/input-output-hk/plutus-apps/issues/212.
