### ISSUE TITLE
plutus-ledger for plutus V2

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus-apps#190]
### Describe the feature you'd like

Plutus V2 was added to plutus repo. But useful functions in the plutus-ledger are all defined for Plutus V1.
Is there Plutus V2 versions of functions like: wrapMintingPolicy or wrapValidator?

**Comment by michaelpj** [comment]
There is no library support for V2 because V2 doesn't exist yet, see https://github.com/input-output-hk/plutus/issues/4285.

When we do actually have V2 we'll have to figure out how to expose that here.

**Comment by koslambrou** [comment]
The Plutus V2 functions currently exist in the `plutus-script-utils` package in the `next-node` branch. The functions `ẁrapMintingPolicy` and `wrapValidator` (they have been renamed to `mkUntypedMintingPolicyt` and `mkUntypedValidator`) have been created.
