### ISSUE TITLE
The program 'cardano-wallet' is required but it could not be found.

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus-apps#204]
### Summary

Try to run testnet on latests sample

### Steps to reproduce the behavior

run step
cabal exec -- cardano-wallet serve \
>     --testnet testnet/testnet-byron-genesis.json \
>     --node-socket testnet/node.sock

### Actual Result

The program 'cardano-wallet' is required but it could not be found.

### Expected Result

Cardano wallet should start

### System info

MacOS

**Comment by koslambrou** [comment]
I don't understand what you're trying to do. Are you trying to run `cardano-wallet`? In that case, you should go to the `cardano-wallet` github repo.

**Comment by Yasuke** [comment]
In the plutus-pab integration example cardano-wallet can be built and is part of the instructions @koslambrou. I have seen this issue when the tag being used is something along the lines of `plutus-starter-devcontainer`. 

@volodyad I would suggest updating to a newer version of plutus-apps where cardano-wallet is present, or as @koslambrou suggested get it from the cardano-wallet repo instead.

**Comment by koslambrou** [comment]
@Yasuke I'm on latest `plutus-apps`, but `cardano-wallet` is not present.

**Comment by Yasuke** [comment]
@koslambrou when I am on latest  doing `cabal build cardano-wallet` succeeds and is listed as a source-repository-package in the cabal.project.

**Comment by koslambrou** [comment]
Sorry, my bad. Called `cabal exec` instead of `cabal build`. Thanks!
