### ISSUE TITLE
utxoIsProduced does not work on local cluster

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus-apps#206]
### Summary

utxoIsProduced does not listen for changes

### Steps to reproduce the behavior

on the branch https://github.com/volodyad/plutus-apps/tree/awaitissue

cabal build plutus-pab-local-cluster
cabal exec plutus-pab-local-cluster

```
curl -H "Content-Type: application/json" -v \
       -X POST \
       -d '{"caID":{"tag":"AwaitTestWaitUtxo"},"caWallet":{"getWalletId":"2d4cc31a4b3116ab86bfe529d30d9c362acd0b44"}}' \
       localhost:9080/api/contract/activate
```

Run to create utxo
```
curl -H "Content-Type: application/json" -v \
       -X POST \
       -d '{"caID":{"tag":"AwaitTestCreateUtxo"},"caWallet":{"getWalletId":"2d4cc31a4b3116ab86bfe529d30d9c362acd0b44"}}' \
       localhost:9080/api/contract/activate
```

### Actual Result

Message "******Await Utxo created success*****" should be shown in logs on every utxo produced

### Expected Result

No message is shown

### System info

mac os big sur
11.5.2

**Comment by Yasuke** [comment]
Hey @volodyad this is being investigated along with #199

**Comment by ak3n** [comment]
Thanks @volodyad for the issue and the reproduction case!
