### ISSUE TITLE
PAB Simulator "forgets" utxos after an extended amount of time

### ISSUE THREAD

**Issue by vlasin** [input-output-hk/plutus-apps#208]
### Summary

I ran my PAB Simulator for 15+ minutes and noticed that the simulated chain index utxo query at my script address returns empty even though there are utxos at that address.

### Steps to reproduce the behavior

1. Start the PAB Simulator with default config.
2. Pay to some script.
3. Leave the PAB Simulator running for at least 15-20 minutes (maybe machine-dependent, not sure).
4. Run the smart contract that logs utxos at the script address:

utxo <- utxosTxOutTxAt myScriptAddress
logInfo @String $ show utxo

### Actual Result

The query above returns an empty Map while 'Plutus.PAB.Simulator.currentBalances' returns the correct amount at the script address.

### Expected Result

The query should return the utxo with the payment to 'myScriptAddress'.

### System info

Ubuntu 20.04, plutus-apps commit eba0a570f72502ac650e642011171bfdcca60e89 (December 16).

**Comment by raduom** [comment]
Can you please retest with the current master?

**Comment by vlasin** [comment]
Retested with the current master. Yep, it is working as expected now. Thanks! I am closing the issue.
