### ISSUE TITLE
Bump HLS

### ISSUE THREAD

**Issue by bhoudebert** [input-output-hk/plutus-apps#209]
### Describe the feature you'd like

Current version of haskell-language-server: 1.3.0.0

Expected version: 1.5.1.0

Huge improvements has been done in new version which could result in a superior QOL.

**Comment by silky** [comment]
Thanks @bhoudebert ; if you're feeling up for it; please do submit a PR! You may glance at this PR - https://github.com/input-output-hk/plutus/pull/4253 - for inspiration :)

**Comment by ak3n** [comment]
Thanks @bhoudebert!
