### ISSUE TITLE
nix-shell error

### ISSUE THREAD

**Issue by cardano-on-the-road** [input-output-hk/plutus-apps#218]
### Summary

I can't use the nix-shell with the latest commit

```
commit fd9e2f0ede0b476dcfac1f7c71f2377b4002e6b6 (HEAD, origin/main, origin/HEAD, main)
Merge: 80c2ee079 57d10773c
Author: Shea Levy <shea@shealevy.com>
Date:   Fri Dec 24 12:01:43 2021 -0500
```

it works fine with this one:
```
commit ad35d7826d575db546e3bdba6d07926afe2a67c0
Author: Shea Levy <shea@shealevy.com>
Date:   Wed Dec 1 10:26:57 2021 -0500
bitte: Restore web-ghc-server
```

### Steps to reproduce the behavior

1. lunching ```nix-shell``` command

### Actual Result

error: getting status of /nix/var/nix/daemon-socket/socket: Operation not permitted
rewrite-libs: ProcFailed {procCommand = "nix-store", procArguments = ["-r","/nix/store/vv3k4s0gzkvdbirq5iiah15w920z6aql-zlib-1.2.11/lib/libz.dylib"], procExitCode = ExitFailure 1}
error: builder for '/nix/store/z0i1gyl2blzxp2naan6wq3dib60r818r-cardano-cli-exe-cardano-cli-1.32.1.drv' failed with exit code 1;
       last 10 log lines:
       > Linking dist/build/cardano-cli/cardano-cli ...
       > installing
       > Installing executable cardano-cli in /nix/store/qxzkl3pvmj1agri8a4k6awd4gsd61in2-cardano-cli-exe-cardano-cli-1.32.1/bin
       > Warning: The directory
       > /nix/store/qxzkl3pvmj1agri8a4k6awd4gsd61in2-cardano-cli-exe-cardano-cli-1.32.1/bin
       > is not in the system search path.
       > Setting gitrev of /nix/store/qxzkl3pvmj1agri8a4k6awd4gsd61in2-cardano-cli-exe-cardano-cli-1.32.1/bin/cardano-cli ... OK
       > "Bundling /nix/store/vv3k4s0gzkvdbirq5iiah15w920z6aql-zlib-1.2.11/lib/libz.dylib in /nix/store/qxzkl3pvmj1agri8a4k6awd4gsd61in2-cardano-cli-exe-cardano-cli-1.32.1/bin/cardano-cli"
       > error: getting status of /nix/var/nix/daemon-socket/socket: Operation not permitted
       > rewrite-libs: ProcFailed {procCommand = "nix-store", procArguments = ["-r","/nix/store/vv3k4s0gzkvdbirq5iiah15w920z6aql-zlib-1.2.11/lib/libz.dylib"], procExitCode = ExitFailure 1}
       For full logs, run 'nix log /nix/store/z0i1gyl2blzxp2naan6wq3dib60r818r-cardano-cli-exe-cardano-cli-1.32.1.drv'.
error: build of '/nix/store/87iqpvg6d4bizsgrzg35k8rc5m1x64ch-cardano-node-exe-cardano-node-1.32.1.drv', '/nix/store/z0i1gyl2blzxp2naan6wq3dib60r818r-cardano-cli-exe-cardano-cli-1.32.1.drv' failed

### Expected Result

Lunching with success ```nix-shell```

### System info

macOS Monterrey

**Comment by silky** [comment]
This has to do with your nix setup, I believe, not to do with this project.

**Comment by cardano-on-the-road** [comment]
Hi @silky, 

May I ask you where I can have some support or an Idea to fix it? 

I would need to lunch the playground server & client.

Best regards,
Valerio
