### ISSUE TITLE
Update README for `plutus-contract` library

### ISSUE THREAD

**Issue by vyastrebovvareger** [input-output-hk/plutus-apps#224]
### Describe the feature you'd like

Could you please provide the correct steps to how to build the examples?
Currently as far as I can see it's out of date because
1. plutus-contract folder does not have any nix config file => 1. `cd plutus-contract` 2. `nix-shell` is not working
2. in cabal there is no contract-exe-guessing-game entry point.

**Comment by ak3n** [comment]
Thanks! I have update the README. It was **very** outdated.

Please take a look at `plutus-use-cases` for the examples.
