### ISSUE TITLE
/bin/plutus-playground-server: No such file or directory

### ISSUE THREAD

**Issue by derneuere** [input-output-hk/plutus-apps#230]
### Summary

I followed the getting started section, setup the cache, opened nix-shell and tried to open the playground server. All get is an error, that is not specific and I could not find anything in the docs or on the discord server.

### Steps to reproduce the behavior

```
git clone https://github.com/input-output-hk/plutus-apps
cd /etc/nix
sudo nano nix.conf //Setup nix cache
cd plutus-apps && nix-shell
cd plutus-playground-server
plutus-playground-server
```

### Actual Result

```
[nix-shell:/home/niaz/plutus-apps/plutus-playground-server]# plutus-playground-server
plutus-playground-server: for development use only
/nix/store/fm77y43lzpgnay4pyc48jwpln0lnmrk3-plutus-playground-server/bin/plutus-playground-server: line 10: /bin/plutus-playground-server: No such file or directory
```

### Expected Result

Startup the server.

### Describe the approach you would take to fix this

I tried to build the server with
```
cd plutus-playground-server
stack build plutus-playground-server
```
This gets stuck on pulling the repository for cardano-wallet.

It has probably something to do with me using the latest commit. But it's not documented which commit is confirmed to work. I only can find information regarding the old repo in plutus

### System info

OS: Manjaro
Version: Latest commit (41149926c108c71831cfe8d244c83b0ee4bf5c8a)

**Comment by ak3n** [comment]
Thanks for the issue!

As `plutus-playground-server` in `nix-shell` is just a script, the command at 10th line is the following

```
$(nix-build --quiet --no-build-output ../default.nix -A plutus-apps.haskell.packages.plutus-playground-server.components.exes.plutus-playground-server)/bin/plutus-playground-server webserver "$@"
```

`/bin/plutus-playground-server: No such file or directory` error means that the `nix-build` command returned an empty string and the script tried to execute `/bin/plutus-playground-server`.

Could you please try to run `$(nix-build --quiet --no-build-output ../default.nix -A plutus-apps.haskell.packages.plutus-playground-server.components.exes.plutus-playground-server)` in `plutus-playground-client` directory? not `plutus-playground-server`.

**Comment by derneuere** [comment]
Thanks for the help! I tried running the command from within the plutus-playground-client and that worked. Running plutus-playground-server still returned the no such file error.

While looking through the issues, I found this one here, which states that I also have to build the server outsider the nix-shell with nix-build -A plutus-playground.server  #195 While doing that I got a different error. Maybe that's the root reason why it does not work on my machine.

**Comment by Iwijn** [comment]
Running plutus-playground-server in the plutus-playground-client directory gives me this error. 
Running just the nix-build command in the plutus-playground-client directory indeed gives no output.

**Comment by Iwijn** [comment]
I also have this error. When running the nix-build command from the script (in the plutus-playground-client directory), it gives a segfault:
![image](https://user-images.githubusercontent.com/30521286/149416670-1dfbaf13-2ab1-4d9a-b41f-b317670fff7c.png)

**Comment by Soupstraw** [comment]
I set `GC_DONT_GC=1` when running `nix-shell` to fix the segfaults.

**Comment by Iwijn** [comment]
Works for me, thanks!
