### ISSUE TITLE
Nix on macOS - README file

### ISSUE THREAD

**Issue by MRyderOC** [input-output-hk/plutus-apps#258]
So on the README in the "Nix on macOS" there is a line that one should add to `/etc/nix/nix.conf` for enabling sandbox. It's a good practice to restart the machine to make sure that changes will take effect (It's a sandbox!). Should I add that to the README and request a PR?

P.S. I enrolled in the Plutus Pioneer Program and am kinda new to this platform but as Lars explained in the first lecture, we should look for good practices.

**Comment by ak3n** [comment]
Thanks for the issue!

There is no need in a reboot for nix to take changes. https://nixos.wiki/wiki/Nix#Sandboxing doesn't mention this as well. Nix will enable sandbox builds right immediately after the configuration file is updated.
