### ISSUE TITLE
Extra signer UTxO when minting

### ISSUE THREAD

**Issue by ignaciodopazo** [input-output-hk/plutus-apps#263]
### Summary

When building a transaction where we mint tokens and pay them to a pkh, at the outputs there’s a UTxO with only minAda as its value that has no reason to exist. Seeing the balance of such a transaction seems that it comes from the UTxO where the transaction deducts the fees.

### Steps to reproduce the behavior

Try in the emulator an operation like
```
{-# INLINABLE mkPolicy #-}
mkPolicy :: () -> ScriptContext -> Bool
mkPolicy _ _ = True

coinMintingPolicy :: Scripts.MintingPolicy
coinMintingPolicy = mkMintingPolicyScript
    $$(PlutusTx.compile [|| Scripts.wrapMintingPolicy mkPolicy ||])

{-# INLINABLE coinCS #-}
coinCS :: CurrencySymbol
coinCS = scriptCurrencySymbol coinMintingPolicy

coinTokenName :: TokenName
coinTokenName = "coinToken"

mintingOperation
    :: forall w s
    .  Contract w s Text ()
mintingOperation = do
    pkh <- Contract.ownPaymentPubKeyHash

    let val = assetClassValue (Value.assetClass coinCS coinTokenName) 200

	lookups = Constraints.mintingPolicy coinMintingPolicy
        tx      = Constraints.mustMintValue val
               <> Constraints.mustPayToPubKey pkh (val <> minAda)

    ledgerTx <- submitTxConstraintsWith @Any lookups tx
```
That mints any amount of a coin and pays to a pkh. The outputs of a transaction like this always have an extra UTxO with _only_ minAda that belongs to the pubkey which pays the fees.

If we paid the minted tokens to a different pkh than the one paying fees the problem remains.

### Actual Result

We printed ledgerTx, a CardanoTx value that represents the above transaction. Their txOutputs and txMint fields looks like this
```
txOutputs = [
  TxOut {
    txOutAddress = Address {
      addressCredential = PubKeyCredential 80a4f45b56b88d1139da23bc4c3c75ec6d32943c087f250b86193ca7,
      addressStakingCredential = Nothing
    },
    txOutValue = Value (Map [(,Map [(\"\",45994238)])]),
    txOutDatumHash = Nothing
  },
  TxOut {
    txOutAddress = Address {
      addressCredential = PubKeyCredential 80a4f45b56b88d1139da23bc4c3c75ec6d32943c087f250b86193ca7,
      addressStakingCredential = Nothing
    },
    txOutValue = Value (Map [(,Map [(\"\",2000000)])]),
    txOutDatumHash = Nothing
  },
  TxOut {
    txOutAddress = Address {
      addressCredential = PubKeyCredential 80a4f45b56b88d1139da23bc4c3c75ec6d32943c087f250b86193ca7,
      addressStakingCredential = Nothing
    },
    txOutValue = Value (
      Map [
        (,Map [(\"\",2000000)]),
        (ddfaa51476c09e1534c81ad0a4c6c44276683727cacecae737e47dbb,Map [(\"coinToken\",200)])
      ]
    ),
    txOutDatumHash = Nothing}],
    txMint = Value (Map [(ddfaa51476c09e1534c81ad0a4c6c44276683727cacecae737e47dbb,Map [(\"coinToken\",200)])])
```

### Expected Result

That UTxO with only minAda should not exist - those minAda are “inside” the UTxO that pays the fees.

### System info

OS: Ubuntu
Version: 20.04
Plutus: c330fc60d0cd174743c95de71e5c404b5008f186

**Comment by sjoerdvisscher** [comment]
It turns out part of our balancing code assumes you don't specify an output for the minted value, and that balancing will take care of it. This is a wrong assumption, and we will fix it. A short term workaround is to remove the `<> Constraints.mustPayToPubKey pkh (val <> minAda)` line.

**Comment by manuimagine** [comment]
But what if you need to pay `(val <> minAda)` to a different wallet? You need the constraint and the extra utxo of the signer will be still there.

**Comment by sjoerdvisscher** [comment]
Indeed, in that case there's no workaround. But see #267 for progress with fixing this bug.
