### ISSUE TITLE
No instance for (ToArgument Slot)

### ISSUE THREAD

**Issue by DrXano** [input-output-hk/plutus-apps#271]
### Summary

No instance for (ToArgument Slot)

### Steps to reproduce the behavior

I got this when i used Slot as a type for the parameters of a function while coding in the Plutus Playground.
For example:

data ExampleParams = ExampleParams {
Param :: Slot
}
deriving stock (Prelude.Eq, Show, Generic)
deriving anyclass (FromJSON, ToJSON, ToSchema, ToArgument)

### Actual Result

The Playground gives me that error when Slot is deriving ToArgument.

### Expected Result

The Playground should compile Slot with ToArgument

### System info

Im using the online version of Plutus Playground

**Comment by ak3n** [comment]
Thanks for the issue!
