### ISSUE TITLE
Unable to get nix-shell running

### ISSUE THREAD

**Issue by AndyWritesBadCode** [input-output-hk/plutus-apps#276]
### Summary

When attempting to run `nix-shell` command in plutus-apps project directory, I keep getting the same error that a package has failed to build. I've confirmed that I'm running the proper version with `nix-env --version`, I believe I have the proper iohk cache set up in a config file in both `/etc/nix/nix.conf` and `~/.config/nix/nix.conf`, and `nix-build -A plutus-playground.server` looks like it's built properly. I've looked through several guides for getting the project started and it doesn't look like I am missing any steps.

### Steps to reproduce the behavior

I've used both

https://docs.google.com/document/d/15QR25eWgg587FTPnuf6Si_lpux-uFQsY_2Gj_4vf4lM/edit

and 

https://www.youtube.com/watch?v=i_PIqUjBQoE

For references on setting the project up, both approaches end up yielding the same result.

### Actual Result

![20220124-2015-dot-cabal-hackage-error](https://user-images.githubusercontent.com/85260689/150892429-3f1f32c3-23fb-40d5-8f02-56a0604e573f.png)

### Expected Result

I would expect nix-shell to launch properly.

### System info

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

plutus-app hash: 41149926c108c71831cfe8d244c83b0ee4bf5c8a

**Comment by ak3n** [comment]
Do you use WSL?

If yes, please consider upgrading it as mentioned here https://forum.cardano.org/t/nix-shell-command-on-wsl-is-throwing-error/72791/3

**Comment by AndyWritesBadCode** [comment]
That did the trick, thank you so much!!
