### ISSUE TITLE
CardanoAPI.toCardanoTxBody does not properly export scriptData

### ISSUE THREAD

**Issue by etiennejf** [input-output-hk/plutus-apps#280]
### Summary

Function `toCardanoTxBody` defined in `Ledger.Tx.CardanoAPI `does not properly export the `txData` of an unbalanced Tx and therefore fails script validation when balancing is performed using a local wallet configuration. This function calls `makeTransactionBody'` (defined in `Ledger.Tx.CardanoAPITemp.hs`), which only considers datums specified in txIns and txOuts. However, additional datum hashes may be introduced in txData via the use of `Constraints.mustHashDatum`. It is therefore recommended to direclty use `txData` of the unbalanced Tx when creating `Alonzo.TxDats`. Note that this map is properly populated when an unbalanced tx is produced. If txData is also passed as an argument to `makeTransactionBody'`, the following changes can easily be performed to rectify the bug.

**Replace**
```
datums :: Alonzo.TxDats StandardAlonzo
datums =
      Alonzo.TxDats $
        Map.fromList
          [ (Alonzo.hashData d', d')
          | d <- scriptdata
          , let d' = toAlonzoData d
          ]
```
**with**

```
 datums :: Alonzo.TxDats StandardAlonzo
 datums  =
     Alonzo.TxDats $
     Map.fromList
     [ (Alonzo.hashData d', d')
     | (_, Datum d) <- Map.toList datums'
     , let d' = toAlonzoData $ fromPlutusData $ PlutusTx.builtinDataToData d
     ]
```
where `datums'` corresponds to txData of the unbalanced transaction. Note that this bug may also impact browser-based wallets, especially when exporting a partial tx to be balanced and signed externally.

### Steps to reproduce the behavior

1. A validator script that must verify the hash of a datum to guarantee integrity, with the datum and its hash only passed as redeemer. An appropriate error is raised when the datum hash is not found.
2. Specify the corresponding off-chain code using `Constraints.mustHashDatum`
3. Submit the transaction within a PAB context (e.g., via the invocation of an endpoint) using a local wallet configuration.

### Actual Result

Validator script fails during balancing

### Expected Result

Validator must evaluate successfully if `Constraints.mustHashDatum` is properly specified.

### Describe the approach you would take to fix this

See above

### System info

plutus-apps commit: 51da951ee2a7b8f05bde624bc9da4ce9a1f81ea1

**Comment by stanislav-az** [comment]
I had similar problem, it seems to be related to this issue. 
In off-chain code creating transaction I used `Ledger.Constraints.mustIncludeDatum` constraint. In on-chain code I used `Ledger.Contexts.findDatum`, which fails with error if datum hash provided via redeemer was not found.
When I try to submit the transaction to testnet using pab, I get `ValidationFailedV1` during wallet balancing:
```
pab:Warning:352] [2022-02-27 19:00:54.96 UTC] WalletClientError "FailureResponse (Request {requestPath = (BaseUrl {baseUrlScheme = Http, baseUrlHost = \"localhost\", baseUrlPort = 8090, baseUrlPath = \"\"},\"/v2/wallets/de119af0cf33eda6b8c0fe501ae48208bd4edf51/transactions-balance\"), requestQueryString = fromList [], requestBody = Just ((),application/json;charset=utf-8), requestAccept = fromList [application/json;charset=utf-8,application/json], requestHeaders = fromList []), requestHttpVersion = HTTP/1.1, requestMethod = \"POST\"} (Response {responseStatusCode = Status {statusCode = 400, statusMessage = \"Bad Request\"}, responseHeaders = fromList [(\"Transfer-Encoding\",\"chunked\"),(\"Date\",\"Sun, 27 Feb 2022 19:00:54 GMT\"),(\"Server\",\"Warp/3.3.18\"),(\"Content-Type\",\"application/json;charset=utf-8\")], responseHttpVersion = HTTP/1.1, responseBody = \"{\\\"code\\\":\\\"redeemer_script_failure\\\",\\\"message\\\":\\\"I was unable to assign execution units to one of your redeemers: spending(1st 0df50987); Its execution is failing with the following error: ValidationFailedV1 (CekError An error has occurred:  User error: The provided Plutus code called 'error'.) [\\\\\\\"Invalid\\\\\\\"].\\\"}\"})"
```
Does somebody know any workarounds?

**Comment by etiennejf** [comment]
In fact, you can't add extra datum or datumHash that is not associated to a produced utxo. Even if the toCardanoTxBody is patched properly, cardano-node will reject the transaction as it only expects datum hash available in produced utxos.

**Comment by stanislav-az** [comment]
But shouldn't any transaction which works in `Plutus.PAB.Simulator` and in `Plutus.Trace`, work in `testnet` also?

**Comment by etiennejf** [comment]
No, there can be discrepancy between the simulator and a real testnet as the simulator is not using the real ledger rules to validate transaction.The plutus-app team is working on this to narrow as much as possible the difference between simulator and testnet.

**Comment by stanislav-az** [comment]
> In fact, you can't add extra datum or datumHash that is not associated to a produced utxo

Thanks, I used `Ledger.Constraints.mustPayWithDatumToPubKey` instead of `Ledger.Constraints.mustIncludeDatum` and it is working as expected.

**Comment by etiennejf** [comment]
Yes, this of course is working fine. I think we misunderstood each other. As stated in by previous post, you cannot provide a datum or a datum hash to a script without it being explicitly associated to a produced UTXO. This means that any datum that is explicitly sent to a public key address or script address will be made available to the script during validation. However, if you want to provide a datum / datum hash not explicitly associated with a produced UTXO using `Constraints.mustHashDatum` or `Constraints.mustIncludeDatum` this will not work even with the patch mentioned in the initial post. For instance, you may want to hash some specific data to be signed externally and to make this datum hash available to the script during validation.

**Comment by koslambrou** [comment]
This was fixed in the recent release. Now, `mustIncludeDatum` and `mustHashDatum` basically don't do anything anymore. They are only used on-chain for validation. 

In order to add a datum in a tx body, you need to use constraints like `mustPayToTheScriptWithDatumInTx` or `mustPayToPubKeyWithDatumInTx`.
