### ISSUE TITLE
Playground simulations should be exportable as test cases.

### ISSUE THREAD

**Issue by micahkendall** [input-output-hk/plutus-apps#288]
### Describe the feature you'd like

The playground web app allows testing of smart contracts in the 'Simulate' panel. These could be exportable into some other format which allows unit testing.

This would make Plutus more accessible because it would be easier to understand what the blocks in the simulator are executing.

**Comment by ak3n** [comment]
Thanks for the idea!

It sounds good and useful but may require too much effort to build and to maintain that general tool with code generation and playground UI changes. The generated code will be outdated after some time. It might differ from the real world plutus tests — there are many to write them. There is no guarantee that it will pay off.

>This would make Plutus more accessible because it would be easier to understand what the blocks in the simulator are executing.

I think it's possible to achieve with a better documentation and examples.
