### ISSUE TITLE
Problem with module re-exports

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/plutus-apps#320]
### Summary

Getting this with latest version of plutus (4417dfea15746596f51f313ef231fb9ecb1d02fc) and plutus-apps (7c119373e0840f9a4e681754ab5aed5ad69a3827)

```
Error:
    Problem with module re-exports:
      - The module 'Data.Aeson.Extras'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'Plutus.V1.Ledger.Ada'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'Plutus.V1.Ledger.Slot'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
      - The module 'Plutus.V1.Ledger.TxId'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
    In the stanza library
```

### Steps to reproduce the behavior

Seriously get rid of these form fields what is the point.

### Actual Result

jumanji

### Expected Result

avocado

### System info

NixOS

**Comment by koslambrou** [comment]
Not a bug. If you're using `plutus-apps`, you shouldn't try to update `plutus` to the latest version. We depend on `cardano-node` and `cardano-ledger` which use a specific commit hash from `plutus`. Therefore, we need to stay aligned. We only update `plutus` once there's a new version of `cardano-node`
