### ISSUE TITLE
Links for Plutus source code returning 403 Forbidden.

### ISSUE THREAD

**Issue by PiotrNap** [input-output-hk/plutus-apps#333]
### Summary

Today I wanted to preview some of the source code by clicking on `source` link on Plutus haddock site, but it appears to me like some of them are forbidden? 

### Steps to reproduce the behavior

1. Go to https://playground.plutus.iohkdev.io/doc/haddock/plutus-ledger/html/Ledger.html#v:toPubKeyHash
2. Click on `source`.

### Actual Result

See the '403 Forbidden' error.

### Expected Result

Being able to preview the source code.

### System info

Browser: [Version 1.36.97 Chromium: 98.0.4758.102 (Official Build) beta (64-bit)](https://brave.com/latest/)

**Comment by koslambrou** [comment]
I'm not getting the `403 Forbidden` after clicking on the link you provided.

**Comment by PiotrNap** [comment]
Yep. Looks like it's working fine now. I'll close this one. Thanks!
