### ISSUE TITLE
Adversary Actions in ContractModel report a validation error.

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/plutus-apps#346]
### Summary

Hi, in this paragraph in the documentation it reads:

https://playground.plutus.iohkdev.io/doc/plutus/tutorials/contract-testing.html#testing-only-via-contract-endpoints

    One way to mitigate this problem is to add additional ‘attack’ endpoints to the contract under test, that carry out a 
    variety of conceivable attacks. Our contract model would then model these attack actions as no-ops, to represent the fact that 
    the attacks fail; our tests would then check that the attacks fail in all circumstances, and with all parameters.
    
I have tried to do this noop approach with a simple NFT contract where an adversary tries to mint more than one of the same TokenName here:

https://gitlab.homotopic.tech/plutus/contracts/nft/-/blob/18398d676c1082342a45fdfad1103f5edc827045/test/Plutus/ContractModel/NFT.hs

This doesn't work though, since the validation failure kills the contract instance and fails the test anyway.

Log here:

https://gitlab.homotopic.tech/plutus/contracts/nft/-/jobs/2929

### Steps to reproduce the behavior

https://gitlab.homotopic.tech/plutus/contracts/nft

lc/adversary branch

### Actual Result

Error

### Expected Result

no error

### System info

NixOS

**Comment by MaximilianAlgehed** [comment]
You need to catch the errors in the attacker `Contract` endpoint. The assumption is that crashing endpoints is bad.

**Comment by MaximilianAlgehed** [comment]
Also, your properties appear to be failing because the slot numbers don't match between the model and the emulator - fixing this will help with some failures.

**Comment by koslambrou** [comment]
Closing. Reopen if the problem persists.
