### ISSUE TITLE
Pab Nami Demo client throws TypeError: EC is not a constructor

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/plutus-apps#357]
### Summary

Following the pab-nami [readme](https://github.com/input-output-hk/plutus-apps/blob/e70c5cba7ac055ce17be4076a3395366ea3159e9/plutus-pab-executables/demo/pab-nami/README.md) results in a blank white screen when visiting the frontend application page.  Console logs TypeError: EC is not a constructor

### Steps to reproduce the behavior

1. Follow the pab-nami [readme](https://github.com/input-output-hk/plutus-apps/blob/e70c5cba7ac055ce17be4076a3395366ea3159e9/plutus-pab-executables/demo/pab-nami/README.md) 

### Actual Result

Console logs `TypeError: EC is not a constructor`

### Expected Result

Page loads UI elements. No error is logged.

### System info

OS: Ubuntu 20.04.3 LTS
Riased against: e70c5cb

**Comment by sorki** [comment]
What's your checked-out version of `pab-nami`?

I vaguely remember having issues with more recent (`>3.0`) nami versions, the one that worked:
```
$ git -C plutus-pab-executables/demo/pab-nami/client/lib/nami-wallet/ status
HEAD detached at 2.3.6
```

**Comment by jonathanfishbein1** [comment]
@sorki thank you that works
