### ISSUE TITLE
SigningProcess seems to not effect the ScriptContext in the emulator

### ISSUE THREAD

**Issue by Yasuke** [input-output-hk/plutus-apps#373]
### Summary

When the signing process is set (like in the Spec.MultiSig module of the use-cases-testsuit). It doesn't seem the signatures are added to the transaction.

In the latest plutus, after looking at the Spec module of use-cases it looks like the reason for this is needing to adopt a newer signing API.

### Steps to reproduce the behavior

1. clone plutus-apps
2. run `nix-shell`
3. cd into the plutus-use-cases repo
4. `cabal repl plutus-use-cases-test`
5. `ghci> import Test.Tasty`
6. `ghci> import Spec.MultiSig`
7. `ghci> defaultMain tests`
8. wait for test to fail

### Actual Result

2 out of 3 tests failed (0.01s)

is the output from my machine

### Expected Result

I expect the tests will pass once the update to the new signing api is complete.

### System info

OS: NixOS
Plutus: 4127e9cd6e889824d724c30eae55033cb50cbf3e

**Comment by sjoerdvisscher** [comment]
The `SigningProcess` code looks old to me and I think it should be removed. Do you need it for something?
