### ISSUE TITLE
Work with withdrawals on Plutus level

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus-apps#395]
### Describe the feature you'd like

At the moment `toCardanoTxBody` ignores the field `txWithdrawals` although it would be great to be able to work with withdrawals.
Also testing framework in emulator ignores this fields and always sets it to empty list for `TxInfo`. 
So we can not test the scripts that rely on this feature.

**Comment by ak3n** [comment]
I suppose it's similar to #93.

Citing @koslambrou (can you confirm it please?):

> This is something that should be part of the transaction creation library plutus-ledger-constraints. However, we're planning a complete rewrite of this library. Thus, attaching metadata to transactions would be done in this rewrite.

**Comment by anton-k** [comment]
Yeah, it looks similar. Only asks for other fields.
To solve this problem I had to create the fork of `toCardanoTxBody`.
I wonder for a quick fix can we pass some auxiliary arguments to set up the fields that are missing on Plutus TX
(stake withdrawal, certificates, metadata)?
