### ISSUE TITLE
Chain Index questions and improvement proposals

### ISSUE THREAD

**Issue by kk-hainq** [input-output-hk/plutus-apps#4]
## Area
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries

## Describe the feature you'd like

1. ~~We should write documentation for setup, API, use cases, customization, and more. A good start is to add `openapi3` support to the RESTful endpoints, similar to https://github.com/input-output-hk/plutus/pull/3807.~~ Moved to #129.

2. ~~We should improve error handling. For example, a wrong socket path is not handled at the moment. The program does not even crash; it just hangs! We sometimes experienced unexpected corrupted DB as well.~~ Moved to #69.

3. We should package the ChainIndex CLI with a Cardano Node with Docker/Nix. We already have a raw Docker image that may or may not be helpful for upstream. A more appropriate upstream setup is to build the Docker image with Nix, using `devcontainer.nix` as an example.

4. ~~Why are redeemers stored together with scripts? For our security work, we want to track all scripts hence all rows in the script table. At the moment, we have to get a row and deserialize it as a `Script` to tell if it is a script or redeemer. Therefore, we have to fetch and check all scripts and redeemers when we experiment with a new transpiler or something. The redeemers are simply dropped in that scenario. For our dApp work, we care a lot about redeemers but barely need scripts in any way. Our suggestion is to have two separate tables for them.~~ Moved to #70.

5. Why are transactions (`ChainIndexTx`) stored in full in the database? We think it is better to strip them down to save disk usage. For instance, we should only store hashes in the transactions with the actual values already stored in the script/datum tables. Else we end up storing duplicated data for each transaction interacting with a known script. We suspect there are still redundant data elsewhere as well.

6. Make the DB more queriable if possible. For example, to get all transactions of a script in a single query. For now, we would have to fetch then filter on all transactions on the client-side.

7. ~~We should extend the configuration file to let users decide what they want to track and store. For example, we only care for Alonzo's data for our current security work. The ability to store data by era would likely be helpful. For dApp work, we mainly care for transactions that interact with our protocol. The ability to not store irrelevant data would be excellent.~~ Moved to #73.

8. Add an extension/customization interface for developers to structure their caches/UTXO pools for faster queries and UTXO discovery. Not all logic can be well represented in config files, while maintaining forks is generally painful for end developers. It would then be nicer to customize the DB scheme, sync logic, effects structure, and more in Haskell. Maybe we can port tight code in `app` to `src` to keep everything in `app` application-specific. We can then gradually expand our extension/customization interface in `src` for developers to import and call in `app`. `chainSyncHandler` in `app/Main.hs` is already a good start!

9.  We should write benchmarks for both resource usage and query performance. We have been working with fully synced chain index instances for both the mainnet and testnet, and a simple query may take several seconds at times. We also had to restart the chain index instances occasionally as it consumes more memory with time. This behaviour might suggest memory leaks over long-running periods. These were our low-traffic local experiences as well. We fear it will not scale for high-traffic user requests over the Internet, especially when a dApp endpoint might require several API calls to the Chain Index to have enough data to serve the user. Caching helps, but every performance improvement is still significant.
 
10. Write more tests.

11. We should host standard DB snapshots.

## Describe alternatives you've considered

We have been customizing the chain index to our needs, but it is prone to upstream changes. I guess the more people can share and have in upstream, the better as well.

## Additional context / screenshots

We have several people who are willing to help with all these proposals. Just assign us the proposals that you approve.

**Comment by kk-hainq** [comment]
@j-mueller @silky @sjoerdvisscher Sorry for the random tagging but what should we prioritize next? We have two drafts in #71, #72 that can proceed if you think they make sense. We are ready to work on anything well-scoped enough too.

**Comment by sjoerdvisscher** [comment]
@kk-hainq I think item 1 and in particular Swagger support would be really helpful!

**Comment by kk-hainq** [comment]
@sjoerdvisscher Sure, I'll try to get the Swagger thing done this week.

**Comment by kk-hainq** [comment]
While many issues are still relevant, we have been following another direction rendering this content outdated in nature. Will just open more issues when needed.
