### ISSUE TITLE
nix-shell fails with error: attribute 'fetchTree' missing, at /home/yasuke/plutus-apps-again/shell.nix:18:11

### ISSUE THREAD

**Issue by Yasuke** [input-output-hk/plutus-apps#412]
### Summary

When running nix-shell to use plutus-apps, an error occurs preventing us from getting into a shell with all the required software and libraries.

### Steps to reproduce the behavior

1. Clone `plutus-apps`
2. go to root directory
3. run `nix-shell`

### Actual Result

error: attribute 'fetchTree' missing, at /home/yasuke/plutus-apps-again/shell.nix:18:11

### Expected Result

I would expect to be dropped into a nix-shell and able to use/run the various libraries, and software.

### System info

OS: Nix-OS
plutus-apps: 343a6e60adff4ca97df9f5a9052ce27745f6c480

**Comment by ak3n** [comment]
What's your `nix --version`?

It seems that `fetchTree` is a part of nix flakes that was introduced in Nix 2.4.

**Comment by Yasuke** [comment]
Thanks, after updating my version (was 2.3.xx) and enabling flakes, nix-shell works no problem.
