### ISSUE TITLE
Work with withdrawals on Plutus level

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus-apps#439]
### Describe the feature you'd like

I'd like to set withdrawals on plutus TX. At the moment there is no way to do it and our project needs it.
There is no fields in Plutus TX to specify staking withdrawals. 

I've checked the `toCardanoTxBody` it also indicates that Plutus TX does not have this feature, 
as also working with credentials:

```haskell
-- unused:
         , txMetadata = C.TxMetadataNone
         , txAuxScripts = C.TxAuxScriptsNone
         , txWithdrawals = C.TxWithdrawalsNone
         , txCertificates = C.TxCertificatesNone
         , txUpdateProposal = C.TxUpdateProposalNone  
```

This code is from plutus-apps repo but I guess it's more plutus related because we need to add the fields
to Plutus TX to specify withdrawals in TX. I guess it works like minting we need an extra field that contains
a list of withdrawals and it's empty when no withdrawals are used.

**Comment by anton-k** [comment]
It's for both repos. Because we can not fix it in plutus-apps alone. If the Tx type is defined in plutus then it needs to be fixed too. As for now it does not has fields to setup withdrawals, certificates and metadata.

**Comment by michaelpj** [comment]
> If the Tx type is defined in plutus then it needs to be fixed too

It isn't any more.

**Comment by anton-k** [comment]
Great I was not aware of that. Then closing
