### ISSUE TITLE
PAB Contract Usage Questions

### ISSUE THREAD

**Issue by tbidne** [input-output-hk/plutus-apps#444]
Hello, I have some questions regarding `Contract` usage that I did not see answered anywhere in the docs / code.

1. What is the story on `Contract` lifetimes / persistence?
   1. Should we expect `Contracts` to be long-lived, in some sense? How about persistence / resuming?
   2. It seems possible for a `Contract` to become "out of sync" if, say, another transaction spends that `Contract`'s `UTxO`. How should this be handled?
2. What is the scalability like? That is, is it expected to have many (thousands?) of contracts running simultaneously, and are there any performance issues to be aware of?

I'm happy to assist in documenting these questions somewhere, if there is an appropriate place.

Thanks!

**Comment by koslambrou** [comment]
> 1. Should we expect `Contracts` to be long-lived, in some sense? How about persistence / resuming?

It all depends what you're doing inside a `Contract`. If you're not calling any "blocking" actions, then the contract terminates. By using blocking actions and recursion, you can make the `Contract` long-lived.

> 2\. It seems possible for a `Contract` to become "out of sync" if, say, another transaction spends that `Contract`'s `UTxO`. How should this be handled?

There's still work to be done on that front. When you say "Contract's UTXOs", I suppose you're talking about UTXOs that are used as input to a submitted transaction. In that case, the Contract will simply (I _think_) fail when submitting the transaction using the wallet backend. Not sure if there would be any retries by the wallet backend? @ak3n Can you confirm this?

> 2\. What is the scalability like? That is, is it expected to have many (thousands?) of contracts running simultaneously, and are there any performance issues to be aware of?

There is known scalability problems when having thousands contract instances running simultaneously in the PAB. This is future work to be addressed.

> I'm happy to assist in documenting these questions somewhere, if there is an appropriate place.

Any documentation would go in the `doc` package, which would be deployed in `plutus-apps.readthedocs.io/`. Ideally, we would have a "Explaining the Contract Monad" section explaining how all this works (a "Explain PAB workflow" would also be good"). A "Known issues" section would also be valuable. We plan to add those in the medium term once we have some time available. If you feel up to the task, feel free to open a PR.

**Comment by ak3n** [comment]
I'm closing the issue, if you don't mind, as the questions were answered.
