### ISSUE TITLE
PAB Return Values

### ISSUE THREAD

**Issue by tbidne** [input-output-hk/plutus-apps#445]
In the same vein of #444, I would like to clarify the situation wrt "returning" data from the PAB. That is, given some PAB API, how do we return data to consumers of this API? The contract endpoints themselves do not return anything as the API is [hardcoded](https://github.com/input-output-hk/plutus-apps/blob/b999f7d09a1ec8b471a776a71bcbee9dbe81ea93/plutus-pab/src/Plutus/PAB/Webserver/API.hs#L37) to return `()`.

From what I can tell, it appears the answer is to use the `Contract`'s `Writer` instance to append "state". Then users can observe this state as `cicCurrentState.observableState` via the `status` endpoint (irrelevant fields omitted):

```json5
/* api/contract/instance/<contractInstanceId>/status */
{
  "cicCurrentState": {
    "observableState": <state>
  }
}
```

Is this indeed the expected usage? Is this documented anywhere? Thanks!

**Comment by koslambrou** [comment]
Yeah, this is under documented.

That's right, looking in the status endpoint is the current way to get data from a contract instance.

**Comment by ak3n** [comment]
I'm closing this as an answered question if you don't mind.

**Comment by tbidne** [comment]
Yes that makes sense, thank you!
