### ISSUE TITLE
create-script-context fails with `DeserialiseFailure`

### ISSUE THREAD

**Issue by mkoura** [input-output-hk/plutus-apps#448]
### Summary

`create-script-context` fails with `DeserialiseFailure`:
```
create-script-context --generate-tx test_minting_context_equivalance_ci0_tph_dummy_tx.signed --out-file test_minting_context_equivalance_ci0_tph_script_context.redeemer --cardano-mode --testnet-magic 42
```

> create-script-context: DecoderFailure (LocalStateQuery HardForkBlock (\': * ByronBlock (\': * (ShelleyBlock (ShelleyEra StandardCrypto)) (\': * (ShelleyBlock (ShelleyMAEra \'Allegra StandardCrypto)) (\': * (ShelleyBlock (ShelleyMAEra \'Mary StandardCrypto)) (\': * (ShelleyBlock (AlonzoEra StandardCrypto)) (\'[] *)))))) Query (BlockQuery (HardForkBlock (\': * ByronBlock (\': * (ShelleyBlock (ShelleyEra StandardCrypto)) (\': * (ShelleyBlock (ShelleyMAEra \'Allegra StandardCrypto)) (\': * (ShelleyBlock (ShelleyMAEra \'Mary StandardCrypto)) (\': * (ShelleyBlock (AlonzoEra StandardCrypto)) (\'[] *))))))))) ServerAgency TokQuerying BlockQuery (QueryIfCurrent (QS (QS (QS (QS (QZ GetUTxOWhole))))))) (DeserialiseFailure 3 "expected map len")\n'

### Steps to reproduce the behavior

1. generate dummy redeemer file, result looks like

> {"fields":[{"list":[]},{"list":[]},{"map":[{"k":{"bytes":""},"v":{"map":[{"k":{"bytes":""},"v":{"int":0}}]}}]},{"fields":[{"fields":[{"fields":[{"int":42}],"constructor":1},{"fields":[],"constructor":1}],"constructor":0},{"fields":[{"fields":[],"constructor":2},{"fields":[],"constructor":1}],"constructor":0}],"constructor":0},{"map":[{"k":{"bytes":""},"v":{"map":[{"k":{"bytes":""},"v":{"int":0}}]}}]},{"list":[]},{"list":[]},{"list":[]},{"fields":[],"constructor":1}],"constructor":0}

2. use the dummy redeemer to generate a dummy Tx
3. derive the correct redeemer from the dummy Tx - while running the corresponding `create-script-context` command, it fails with `DeserialiseFailure`

### Actual Result

`create-script-context` fails with `DeserialiseFailure`

### Expected Result

The correct redeemer is derived from the dummy Tx.

### System info

OS: Fedora 35
Plutus apps: `fdb0eec477fc0f99f5edfdbc11c041dbd35ca6bb`

**Comment by james-iohk** [comment]
I am using input-output-hk/cardano-node@73f9a746362695dc2cb63ba757fbcabb81733d23, which is a bit older.
input-output-hk/cardano-node@65422ff373f2f88a563afa746a9a16d211ffdc7c doesn't sync on testnet for me.

**Comment by ak3n** [comment]
@mkoura does it work with `2b1d18c6c7b7142d9eebfec34da48840ed4409b6`? That's the cardano-node's version stated in `plutus-apps/cabal.project` that you mentioned in the issue (`fdb0eec477fc0f99f5edfdbc11c041dbd35ca6bb`).

**Comment by mkoura** [comment]
It still doesn't work with node master of 1.35.0-rc4, which are the node versions that need to be tested.

```
create-script-context --generate-tx test_context_equivalance_ci0_lwh_dummy_step2_tx.signed --out-file test_context_equivalance_ci0_lwh_script_context.redeemer --cardano-mode --testnet-magic 42
```

> DecoderFailure (LocalStateQuery HardForkBlock (\': * ByronBlock (\': * (ShelleyBlock (ShelleyEra StandardCrypto)) (\': * (ShelleyBlock (ShelleyMAEra \'Allegra StandardCrypto)) (\': * (ShelleyBlock (ShelleyMAEra \'Mary StandardCrypto)) (\': * (ShelleyBlock (AlonzoEra StandardCrypto)) (\'[] *)))))) Query (BlockQuery (HardForkBlock (\': * ByronBlock (\': * (ShelleyBlock (ShelleyEra StandardCrypto)) (\': * (ShelleyBlock (ShelleyMAEra \'Allegra StandardCrypto)) (\': * (ShelleyBlock (ShelleyMAEra \'Mary StandardCrypto)) (\': * (ShelleyBlock (AlonzoEra StandardCrypto)) (\'[] *))))))))) ServerAgency TokQuerying BlockQuery (QueryIfCurrent (QS (QS (QS (QS (QZ GetCurrentPParams))))))) (DeserialiseFailure 14 "decodeNS: invalid index 5")
