### ISSUE TITLE
Trying to create a minimal console PAB application

### ISSUE THREAD

**Issue by agocorona** [input-output-hk/plutus-apps#462]
I'm trying to create a minimal console PAB program for various purposes. Using the GuessGame example, running in the testnet.

I deployed the cardano node, the cardano wallet and the chain index following the [README](https://github.com/input-output-hk/plutus-apps/blob/7fb0e73765502b9876a78a5d80e993161823a54f/plutus-pab/test-node/README.md)

The console program includes this relevant snippet which contains the whole idea:

```haskell
main=  do
  handlers <- testnetHandlers
  let walletid= fromJust $ decode $    "\"17abbab9d64a5e1f8b267da9eda630d5de9c969c\""

  r <- Core.runPAB def handlers $ do
       cid  <- activateContract (Wallet walletid) Lock
       callEndpointOnInstance  cid "lock" LockParams{secretWord="42", amount= Ada.adaValueOf $ fromIntegral 1000} -- ,lockIndex=0}
  
  liftIO $ print ("RESULT=",r)
  
  tempty <-newEmptyMVar
  takeMVar tempty

testnetHandlers :: MonadIO m => m (EffectHandlers (Builtin GuessGameContracts) (AppEnv GuessGameContracts))
testnetHandlers= liftIO $ do
    config <- decodeFileThrow "pab-config.yml"
    def <-  defaultConfig
    (trace , switchboard) <- setupTrace_ def "pab"

    let ccaTrace = convertLog PrettyObject trace
    -- (trace :: Trace IO (PrettyObject (AppMsg (Builtin a))), switchboard)

    return $ appEffectHandlers BeamSqliteBackend config (toPABMsg ccaTrace) ( handleBuiltin)
    where
    -- toPABMsg :: Trace m (LM.AppMsg (Builtin a)) -> Trace m (LM.PABLogMsg (Builtin a))
    toPABMsg = LM.convertLog LM.PABMsg


```
The lock endpoint is an slight modification of the one of the classical guessgame example, with additional traces

```haskell
lock :: AsContractError e => Promise () GameSchema e ()
lock = endpoint @"lock" @LockParams $ \(LockParams secret amt) -> do
    logInfo @Haskell.String $ "Pay " <> Haskell.show amt <> " to the script"
    let tx         = Constraints.mustPayToTheScript (hashString secret) amt
    logInfo @Haskell.String "SUBMITTING"
    ledgerTx <- submitTxConstraints gameInstance tx
    logInfo @Haskell.String $ "TRANSACTION=" <>  Haskell.show ledgerTx
    void $ awaitTxConfirmed $ getCardanoTxId ledgerTx
    logInfo @Haskell.String $ "Paid " 
```

If I invoke the lock endpoint with a wallet which hasn't enough funds, the program rightly detect that circunstance:

```
[pab:Info:1] [2022-05-15 20:12:20.41 UTC] Initialising contract Lock with ID 2d9c4d19-a678-49c0-9b19-447aa19189a4
[pab:Info:1] [2022-05-15 20:12:20.42 UTC] Activated instance 2d9c4d19-a678-49c0-9b19-447aa19189a4 on W0c2317b
[pab:Info:16] [2022-05-15 20:12:20.43 UTC] 2d9c4d19-a678-49c0-9b19-447aa19189a4: "Pay Value (Map [(,Map [(\"\",1000000000)])]) to the script"
[pab:Info:16] [2022-05-15 20:12:20.43 UTC] 2d9c4d19-a678-49c0-9b19-447aa19189a4: "SUBMITTING"
[pab:Warning:16] [2022-05-15 20:12:20.44 UTC] WalletClientError "FailureResponse (Request {requestPath = (BaseUrl {baseUrlScheme = Http, baseUrlHost = \"localhost\", baseUrlPort = 8090, baseUrlPath = \"\"},\"/v2/wallets/0c2317b3ba9e5d7f351df5122d13a3c488672a82/transactions-balance\"), requestQueryString = fromList [], requestBody = Just ((),application/json;charset=utf-8), requestAccept = fromList [application/json;charset=utf-8,application/json], requestHeaders = fromList []), requestHttpVersion = HTTP/1.1, requestMethod = \"POST\"} (Response {responseStatusCode = Status {statusCode = 403, statusMessage = \"Forbidden\"}, responseHeaders = fromList [(\"Transfer-Encoding\",\"chunked\"),(\"Date\",\"Sun, 15 May 2022 20:12:20 GMT\"),(\"Server\",\"Warp/3.3.17\"),(\"Content-Type\",\"application/json;charset=utf-8\")], responseHttpVersion = HTTP/1.1, responseBody = \"{\\\"message\\\":\\\"I can't process this payment as there are not enough funds available in the wallet. I am missing: coin: 999.000000 tokens: [] \\\",\\\"code\\\":\\\"not_enough_money\\\"}\"})"
```
But if I use an account with enough money, the program does not progress, it stay locked  at `submitTxConstraints gameInstance tx`

```
[pab:Info:1] [2022-05-15 20:15:21.10 UTC] Initialising contract Lock with ID 03a9eda2-9b93-443d-96de-c861495ecf8f
("RESULT=",Right Nothing)
[pab:Info:1] [2022-05-15 20:15:21.12 UTC] Activated instance 03a9eda2-9b93-443d-96de-c861495ecf8f on W17abbab
[pab:Info:16] [2022-05-15 20:15:21.12 UTC] 03a9eda2-9b93-443d-96de-c861495ecf8f: "Pay Value (Map [(,Map [(\"\",1000000000)])]) to the script"
[pab:Info:16] [2022-05-15 20:15:21.12 UTC] 03a9eda2-9b93-443d-96de-c861495ecf8f: "SUBMITTING"
```

[pab-config.yml](https://github.com/input-output-hk/plutus-apps/blob/7fb0e73765502b9876a78a5d80e993161823a54f/plutus-pab/test-node/testnet/pab-config.yml) is the one of the repo with the last lines uncommented to allow synchronization.

What I'm missing?

**Comment by agocorona** [comment]
I know that this is not a bug and therefore it has no priority. I´m involved in a Catalyst project that makes use of the internals of the PAB. I don't know where to ask it in a more apropiarte place, since it is about the internals of the PAB and not many people except the developers of it know how it works. This kind of questions are of general interest for developers who wan to know how the open source code of the PAB works.

**Comment by koslambrou** [comment]
A good place to ask questions is in the [Cardano StackExchange](https://cardano.stackexchange.com).

Your issue is a known problem with the PAB on testnet.

`submitTxConstraints` submits the transaction in the Cardano blockchain and waits for the transaction to be confirmed. The reason it blocks is because your PAB is not completely synced on testnet. Completly syncing on testnet takes a lot of time. I suggest for the time being to set the `pabRollbackHistory` to 1 and `pabResumeFrom` to a recent point in order to sync faster.

**Comment by agocorona** [comment]
Thank you @koslambrou .
Actually  my code does not include the synchronization.  I don't find the place in the standard PAB code where that synchronization takes place. There is a section where [contracts running previously are restarted](https://github.com/input-output-hk/plutus-apps/blob/e51f57fa99f4cc0942ba6476b0689e43f0948eb3/plutus-pab/src/Plutus/PAB/Run/Cli.hs#L165-L190) that makes a lot of sense for me, but I don't  see where the synchronisation takes place.
I don't  get the reason why a synchronisation is necessary in the PAB. Maybe because the rollbacks?. Fon now, I have a very limited knowledge of the Ouroboros protocol.

**Comment by koslambrou** [comment]
It's in the `Plutus.PAB.Core.ContractInstance` module and submodules. There's `BlockchainEnv` where we store information from the blockchain such a status of transaction and transaction outputs. In the long term, this syncing should be moved elsewhere (like the chain-index), but for now, the PAB needs to sync some information from the network. That's why it's blocking when waiting for the tx to be confirmed.

**Comment by agocorona** [comment]
Thans a lot. 
It is indeed called in my code by Core.runPAB  which calls [initialiseEnvironment](https://github.com/input-output-hk/plutus-apps/blob/65220a0fe507367fed8dedf438fd96103de770b9/plutus-pab/src/Plutus/PAB/Core.hs#L203) set in appEffecHandlers which call  [startNodeClient](https://github.com/input-output-hk/plutus-apps/blob/700c58222db34ad9ccbf0745ca4593fd70f1a275/plutus-pab/src/Plutus/PAB/App.hs#L131) which initializes the event handler [runChainSync which set processChainSyncEvent](https://github.com/input-output-hk/plutus-apps/blob/4c60896dff0c31a98395ba6e6791433cd61a25e3/plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs#L68).
The PAB example receive such events  and [print blocks](https://github.com/input-output-hk/plutus-apps/blob/4c60896dff0c31a98395ba6e6791433cd61a25e3/plutus-pab/src/Plutus/PAB/Core/ContractInstance/BlockchainEnv.hs#L81)  and slots that are being synchronized in runChainSync but my code receives nothing.. I'm trying to understand why. My config is the same than the PAB example.

**Comment by agocorona** [comment]
Thanks @ak3n 
Ops,  I used the same pab-config.yml, of the pab example, but my program is in a different path and the socket path was relative to the location of the example. I pointed to the right path and now my program synchronizes.... Sorry. 

I close the issue.
