### ISSUE TITLE
Chain-index servant client function for `getTx`, `getTxOut` and `getTxs` is not exposed

### ISSUE THREAD

**Issue by gege251** [input-output-hk/plutus-apps#484]
### Summary

We are depending on this feature for some of our tooling, but with the latest master, these functions are not exposed. The actual function exists, so I wonder if it was just forgotten.

### Steps to reproduce the behavior

Trying to use `getTx`, `getTxOut` and `getTxs` from the `Plutus.ChainIndex.Client` module:
https://github.com/input-output-hk/plutus-apps/blob/e51f57fa99f4cc0942ba6476b0689e43f0948eb3/plutus-chain-index-core/src/Plutus/ChainIndex/Client.hs#L5-L20

### Actual Result

Not in scope: ‘Plutus.ChainIndex.Client.getTxOut’

### Expected Result

These functions work as they used to.

### System info

Plutus apps version: e51f57fa99f4cc0942ba6476b0689e43f0948eb3

**Comment by ak3n** [comment]
@gege251 done 👌

**Comment by gege251** [comment]
Awesome, thank you!
