### ISSUE TITLE
```nix-shell``` launched from this repository causes the haskell-language-srver VSCode extension not to work properly

### ISSUE THREAD

**Issue by HarmonicPool** [input-output-hk/plutus-apps#487]
### Summary

I can't get to work with the ```hls``` features while writing plutus as mentioned in the [VSCode repository issue](https://github.com/haskell/vscode-haskell/issues/614)

![Screenshot from 2022-05-29 16-02-40](https://user-images.githubusercontent.com/96301444/170873076-0122ec44-a4e8-4317-be09-476a57395226.png)

### Steps to reproduce the behavior

```bash
cd $PLUTUS_APPS_DIR
nix-shell
```
then in the generated environment:
```
code $myProject
```

### Actual Result

the extension doesn't work

### Expected Result

the generated environment allows me to work using the ```haskell-language-server``` features

### Describe the approach you would take to fix this

see [this issue](https://github.com/haskell/vscode-haskell/issues/614)

### System info

```lsb_release -a```
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
```

**Comment by hasufell** [comment]
Your logs from the [vscode-haskell issue](https://github.com/haskell/vscode-haskell/issues/614#issuecomment-1140476472) indicate that nix sets up HLS 1.5.1.0, which is outdated.

**Comment by HarmonicPool** [comment]
Well that's unfortunate since I should be using the last release

![nix-shell-outdate-hls](https://user-images.githubusercontent.com/96301444/170885732-6779240d-13c9-459b-8fb9-e785e8a24984.png)

Is there something I'm doing wrong, or that I can do inorder to get the haskel-language-server v1.7.0.0?

**Comment by hasufell** [comment]
Well, I have no investment in nix. I've never used plutus-apps with it. But I've developed smart contracts with just using cabal. That should work fine with the appropriate `cabal.project`. I usually follow https://github.com/input-output-hk/plutus-starter/blob/main/cabal.project

**Comment by HarmonicPool** [comment]
> Well, I have no investment in nix. I've never used plutus-apps with it. But I've developed smart contracts with just using cabal. That should work fine with the appropriate `cabal.project`. I usually follow https://github.com/input-output-hk/plutus-starter/blob/main/cabal.project

setting up the project without ``nix``` solves the problem

**Comment by zmrocze** [comment]
hm, I don't have this issue with hls 1.5.1, nix and vscode.
Did hls have the time to compile everything? there is progress status in the bottom stripe in vscode.
Also maybe there is a compile issue earlier? As one can often get plutus-tx plugin errors ([GHC Core to PLC plugin error](https://cardano.stackexchange.com/questions/459/haskell-ide-inlinable-error-help)).

**Comment by HarmonicPool** [comment]
yes I have lots of "GHC Core to PLC plugin error" and I have all the GHC-options specified in the [plutus docs > troubleshooting > plugin errors](https://playground.plutus.iohkdev.io/doc/plutus/troubleshooting.html#plugin-errors)

onestly I got used to them since when running ```cabal repl``` or ```cabal buld``` everything goes fine and any other error is showed with more priority in vscode

```hls``` is compiled since I can use it by hand in the shell

**Comment by ak3n** [comment]
We have switched to `nix develop` with newer versions of hls. Please re-open if there will be any problems with it.

**Comment by Dr-Mazen-Khaddaj** [comment]
@ak3n can you elaborate?
