### ISSUE TITLE
Possible to break out quickcheck-dynamic?

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/plutus-apps#538]
### Describe the feature you'd like

Hi, quickcheck-dynamic is really good standalone, doesn't require any plutus dependencies or any non-hackage dependencies. It might be worth releasing it separately from this project so that it can be versioned independently and used by other third party tools that do not use the PAB for effects.

**Comment by ak3n** [comment]
Thanks for the issue.

Indeed, it's a good idea. You can find it here https://github.com/input-output-hk/quickcheck-dynamic. It should be published on hackage soon.
