### ISSUE TITLE
Documentation for quickcheck-dynamic

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/plutus-apps#539]
### Describe the feature you'd like

Going through the quickcheck-dynamic code there seems to be a lot of things which are hard for me to decipher. Such as 

```
data ChoiceType = Angelic | Demonic
  deriving (Eq, Show)
```

As well as the `DynLogic` type itself, is there a paper that faithfully represents these types from which quickcheck-dynamic was implemented? If so, can we cite it as a reference? Or is this nomenclature unique to quickcheck-dynamic? If so, can the algebra be explained in more detail?

**Comment by ak3n** [comment]
It's got its own repo now — https://github.com/input-output-hk/quickcheck-dynamic. You may ask these questions there. Thanks!
