### ISSUE TITLE
Remove freer from plutus-ledger

### ISSUE THREAD

**Issue by locallycompact** [input-output-hk/plutus-apps#545]
### Describe the feature you'd like

Hi, we'd like to be able to reuse the types from plutus-ledger to use with other third party transaction construction libraries, since they make a lot of sense, but plutus-ledger brings in dependencies that are out of scope for that purpose, such as freer, just to define openapi orphans for freer types.

https://github.com/input-output-hk/plutus-apps/blob/main/plutus-ledger/src/Ledger/Orphans.hs 

For situations in which we don't want freer or openapi, but do want to use the types in this library, can we move this orphan somewhere else?

**Comment by ak3n** [comment]
Implemented in #900.
