### ISSUE TITLE
Build create-script-context with Nix

### ISSUE THREAD

**Issue by james-iohk** [input-output-hk/plutus-apps#580]
### Describe the feature you'd like

To be able to build [create-script-context](https://github.com/input-output-hk/plutus-apps/blob/main/plutus-example/app/create-script-context.hs) with Nix. This will enable use in the [cardano-node-tests](https://github.com/input-output-hk/cardano-node-tests) suite. 

### Describe alternatives you've considered

Although some of us have dependencies set up correctly for building this with cabal, @mkoura has been unable to use this approach, see https://github.com/input-output-hk/plutus-apps/issues/448. Nix is the only viable way with that test automation framework.

**Comment by ak3n** [comment]
Well, it's possible to build it with `nix build -f default.nix plutus-apps.haskell.packages.plutus-example.components.exes.create-script-context`.

I suppose there is a desire to call it within a nix-shell?

**Comment by james-iohk** [comment]
Yes, I should have been more specific, cardano-node-tests uses nix-shell.
