### ISSUE TITLE
Chain index not synchronizing on testnet

### ISSUE THREAD

**Issue by rynoV** [input-output-hk/plutus-apps#589]
### Summary

When running `plutus-chain-index start-index --network-id 1097911063` to start syncing with the testnet (starting with a fresh database file), synchronization won't complete. After a while of syncing it gets to close to 100%, then jumps back to somewhere in the 70% range, and this process repeats.

Here's the last logs demonstrating what's happening:

[pci-logs.txt](https://github.com/input-output-hk/plutus-apps/files/9095850/pci-logs.txt)

My config file:

```json
{
  "cicPort": 9083,
  "cicSocketPath": "testnet/node.sock",
  "cicAppendTransactionQueueSize": 30000,
  "cicSecurityParam": 2160,
  "cicDbPath": "/tmp/chain-index.db",
  "cicNetworkId": {
    "contents": {
      "unNetworkMagic": 1097911063
    },
    "tag": "Testnet"
  },
  "cicStoreFrom": {
    "unBlockNo": 0
  },
  "cicSlotConfig": {
    "scSlotLength": 1000,
    "scSlotZeroTime": 1596059091000
  }
}
```

### Steps to reproduce the behavior

1. `nix build -f default.nix plutus-chain-index`
2. `result/bin/plutus-chain-index start-index --network-id 1097911063 --db-path $CHAIN_INDEX_PATH --socket-path $CARDANO_NODE_SOCKET_PATH --config pci-config.json`
  - `$CHAIN_INDEX_PATH` is a path to a file that doesn't exist yet
4. Wait for sync to get close to 100%

### Actual Result

Sync never finishes, just loops, see above.

### Expected Result

Sync finishes.

### Describe the approach you would take to fix this

Don't think I can fix this myself, but I'm guessing this is caused by the recent testnet hardfork.

### System info

`plutus-apps`: https://github.com/input-output-hk/plutus-apps/commit/0c2b6ad3807fe86a4596483ed2a4b53f98a912ad
OS: Arch Linux x86_64
Kernel: 5.18.10-arch1-1

**Comment by koslambrou** [comment]
Yeah, for testnet, you need to use the `next-node` branch which contains the updated chain-index for Vasil HF. Once HF happens on mainnet, `next-node` will be merge to `main`.

**Comment by rynoV** [comment]
That seems to have worked, thanks!
