### ISSUE TITLE
Update cardano-node.sh

### ISSUE THREAD

**Issue by jeromecovington** [input-output-hk/plutus-apps#593]
### Describe the feature you'd like

Script should be updated to v1.35.1 soon.

### Describe alternatives you've considered

These lines should be updated. I think these are the new build numbers to use but I need to set up a node using the updated script to verify.

- https://github.com/input-output-hk/plutus-apps/blob/main/scripts/cardano-node.sh#L12
  - `cardano-node-1.35.1-linux.tar.gz`
- https://github.com/input-output-hk/plutus-apps/blob/main/scripts/cardano-node.sh#L27
  - `https://hydra.iohk.io/build/16622274`
- https://github.com/input-output-hk/plutus-apps/blob/main/scripts/cardano-node.sh#L34
  - `https://hydra.iohk.io/build/16607585`

**Comment by ak3n** [comment]
@koslambrou do we even use `scripts`? I haven't found any usages in the repo. It seems everything is orchestrated with nix.

**Comment by koslambrou** [comment]
Nice find @ak3n. I was wondering the same thing. 
Can you update it as part of https://github.com/input-output-hk/plutus-apps/pull/616?
