### ISSUE TITLE
Discrepancy between `plutus-apps` and `cardano-ledger` on handling values.

### ISSUE THREAD

**Issue by VictorCMiraldo** [input-output-hk/plutus-apps#604]
### Summary

The ledger implementation seems to always add a 0 lovelace entry to values, as seen [here](https://github.com/input-output-hk/cardano-ledger/blob/0726ec1fb2bbb3cf434aa46d3501109e2143de35/eras/alonzo/impl/src/Cardano/Ledger/Alonzo/TxInfo.hs#L317). Yet, `plutus-apps` doesn't add this entry to values. In fact, [this](https://github.com/input-output-hk/plutus/blob/master/plutus-ledger-api/src/PlutusLedgerApi/V1/Value.hs) module never mentions that restriction anywhere.
As a result, the following script can distinguish whether we're running on the emulator or on-chain:

```
validate _ _ _ scriptCtx = adaSymbol `Map.member` txInfoMint (txInfo scriptCtx)
```

That script will be equivalent to `validate _ _ _ = True` on-chain, but `validate _ _ _ = False` on the emulator.
I wonder whether this is a bug in `plutus-apps` or whether the ledger just happen to add that entry to values, which seems not to change the semantic of values in any way. It depends on what the specification is and would be great to know more.

### Steps to reproduce the behavior

See the script example above.

### Actual Result

Script fails on the emulator.

### Expected Result

Script succeeds on the emulator.

### System info

n/a

**Comment by ak3n** [comment]
>Given that there is a PR to match the cardano-ledger behavior, it looks like it is the case that all values should contain an entry with 0 lovelace. Hence this was a bug in plutus-apps.

Yes, indeed, turned out it's the intended implementation. Thanks a lot for finding it!

>If not, is the ledger code supposed to be considered the specification?

Yes, it's the specification, and we are planning to switch fully to `cardano-ledger`. The first step will be is to reimplement `mkTxInfo`.

> or at least which parts of the emulator rely on the actual ledger code

Currently we use the ledger validation rules as you may observe in `Ledger.Validation`.

**Comment by VictorCMiraldo** [comment]
Thanks @ak3n!

> Currently we use the ledger validation rules as you may observe in Ledger.Validation.

That is reassuring; we were a little concerned about the validity of the tests that rely on the `plutus-apps` interface. 

> and we are planning to switch fully to cardano-ledger.

Do you have an ETA on this?

**Comment by ak3n** [comment]
> Do you have an ETA on this?

Can't say anything about the full transition but we are planning to change the behaviour of `mkTxInfo` in a week or two. If it's important we might raise the priority and continue the transition.
