### ISSUE TITLE
Why PlutusV2 does not have `TypedValidator`?

### ISSUE THREAD

**Issue by KristianBalaj** [input-output-hk/plutus-apps#622]
### Describe the feature you'd like

PlutusV1 has `TypedValidator` available. And I'm wondering why PlutusV2 does not have it, just `Validator`?

**Comment by ak3n** [comment]
Thanks for the issue!

It's already in the backlog but was not implemented yet. Marked as `Tracked`.

**Comment by ak3n** [comment]
Please check `next-node` branch. Implemented in #666.
