### ISSUE TITLE
Question: why are lookups needed?

### ISSUE THREAD

**Issue by klntsky** [input-output-hk/plutus-apps#674]
### Describe the feature you'd like

We are exploring PAB design space in [CTL](https://github.com/Plutonomicon/cardano-transaction-lib/). Initially we modeled our APIs on Plutus (because we wanted a drop-in replacement). But now we want to check if it is possible to simplify the API.

So the question we have is: what motivates separation of lookups from constraints? How it compares to a hypothetical implementation that asks the user for just a script, instead of a script and a hash in two different places?

**Comment by ak3n** [comment]
The main design of the constraints library was to be able to use the same constraints on-chain + off-chain. Which means some datatypes can't be used on-chain (like Validator or any other datatypes which isn't compatible with Plutus), so we use lookups to get these datatypes off-chain. Lookups are also used to reduce the size of Plutus scripts by providing the minimum set of arguments that are required by the on-chain part in the data constructors.

**Comment by klntsky** [comment]
Thanks! Looks like these motivations do not apply to us, because we are dealing with offchain only.
