### ISSUE TITLE
ScriptLookups for PlutusV2 validator?

### ISSUE THREAD

**Issue by bjing** [input-output-hk/plutus-apps#689]
### Describe the feature you'd like

Looks like `ScriptLookups` only supports `slTypedPlutusV1Validator`. Is there not V2 support yet or is it done in a different way, i.e. no longer using `ScriptLooksups`?
```
data ScriptLookups a

Constructors

ScriptLookups 
  slMPS :: Map MintingPolicyHash MintingPolicy
  slTxOutputs :: Map TxOutRef ChainIndexTxOut
  slOtherScripts :: Map ValidatorHash (Validator, LedgerPlutusVersion)
  slOtherData :: Map DatumHash Datum
  slPaymentPubKeyHashes :: Set PaymentPubKeyHash
  slTypedPlutusV1Validator :: Maybe (TypedValidator a)
  slOwnPaymentPubKeyHash :: Maybe PaymentPubKeyHash
  slOwnStakePubKeyHash :: Maybe StakePubKeyHash
```
Thanks!

**Comment by koslambrou** [comment]
In the `next-node` branch, typed validators support PlutusV2 scripts.

**Comment by bjing** [comment]
@koslambrou thank you very much! I was only using the v1.0.0-alpha release.

**Comment by bjing** [comment]
@koslambrou I just realised in the `next-node` branch, in the field `slTypedValidator       :: Maybe (TypedValidator a)`, `TypedValidator` is actually a Plutus V1 typed validator. [Code link](https://github.com/input-output-hk/plutus-apps/blob/next-node/plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs#L137-L138)

But I'd like that field to point to a TypedValidator of Plutus V2 type.  So looks like my original request still stands.

**Comment by bjing** [comment]
@koslambrou thanks for the pointer, however, on line 137 [here](https://github.com/input-output-hk/plutus-apps/blob/next-node/plutus-ledger-constraints/src/Ledger/Constraints/OffChain.hs#L137-L138), the type `TypedValidator` is hardcoded to `Versioned PV1.Script` in `Plutus.Script.Utils.Typed`. I can't change this relationship without having to change the source code of plutus-apps.

Would you mind enlighten me what I'm missing?

**Comment by bjing** [comment]
@koslambrou would you mind keeping this issue open till it's resolved for me? (I'm not sure if this is how you guys determine whether you keep an issue open or closed).
