### ISSUE TITLE
Plutus PAB chain index issue

### ISSUE THREAD

**Issue by pnjn10** [input-output-hk/plutus-apps#693]
### Summary

my goal is to deploy plutus smart contract into cardano testnet using PAB. For using PAB I have synced my testnet cardano node and wallet. Now when I was trying to sync chain index it sync's till 92% then it starts resyncing from 71.86%. I need help of you guys. Thankyou in advance.

reference I used to do:

YT video: https://www.youtube.com/watch?v=X6AyZIZ0vaE

github: https://github.com/input-output-hk/plutus-apps/blob/main/plutus-pab/test-node/README.md

### Steps to reproduce the behavior

1. Install cardano-node & cardano-wallet
2. cabal build plutus-pab-examples plutus-chain-index
3. ./start-testnet-node.sh
4. cardano-wallet serve \
    --testnet testnet/testnet-byron-genesis.json \
    --node-socket testnet/node.sock
5. cabal exec -- plutus-chain-index --config testnet/chain-index-config.json start-index

### Actual Result

chain index just simple pause syncing around 92% in first time of doing and in second time it started resyncing from around 71%

### Expected Result

chain index should to properly synced for further application

### Describe the approach you would take to fix this

I have deleted the whole data in plutus chain index db and then tried to resync it (stops around 92% then restarts syncing from around 71%)  

### System info

OS: [ubuntu 20.04]
RAM: [16 GB]
Disk Capacity: [512.1 GB]

**Comment by pnjn10** [comment]
warra support

**Comment by francolq** [comment]
Hi! We had the same issue, we did a workaround by replacing the chain index with blockfrost. It is implemented in this PR:
https://github.com/input-output-hk/plutus-apps/pull/655

**Comment by james-iohk** [comment]
Plutus-apps no longer uses the `testnet` node version because that network is being decommissioned.
This integration test shall be reconfigured to use one of the replacement testnets: `preview` `pre-prod`
See here for all networks and their configs: https://book.world.dev.cardano.org/environments.html

**Comment by pnjn10** [comment]
thankyou @james-iohk i have changed my configuration to pre-production and now its working!

but during the pab db migrate i faced below issue can you please help

token-pab: SQLite3 returned ErrorNotADatabase while attempting to perform prepare "SELECT name, sql from sqlite_master where type='table'": file is not a database
![Screenshot from 2022-09-08 17-23-59](https://user-images.githubusercontent.com/112864571/189280516-92b7f81f-db40-4f05-af95-cde3c678ac86.png)

**Comment by pnjn10** [comment]
It was my mistake I have changed my db config data. Just kept db config data as it is and now its working! thankyou all
