### ISSUE TITLE
`calculateDelta` doesn't correctly account for minimum ada requirement in tests

### ISSUE THREAD

**Issue by MaximilianAlgehed** [input-output-hk/plutus-apps#735]
### Summary

The `caluclateDelta` function in `Plutus.Contract.Test.MissingLovelace` doesn't correctly account for the amount of Ada that is unaccounted for in a `ContractModel` test due to min Ada.

### Steps to reproduce the behavior

Run the `Spec.Auction` contract model tests:
```
$> cabal repl plutus-use-cases-test
> import Test.QuickCheck
> import Spec.Auction
> quickCheck prop_Auction
```

### Actual Result

```
Actions 
 [Init,
  WaitUntil (Slot {getSlot = 97}),
  Bid (Wallet 3) 2000000,
  Bid (Wallet 3) 2000001]
Expected funds of W[1] to change by
  SymValue {symValMap = fromList [], actualValPart = Value (Map [(,Map [("",2000001)]),(363d3944282b3d16b239235a112c0f6e2f1195de5067f61c0dfc0f5f,Map [("token",-1)])])}
but they changed by
  SymValue {symValMap = fromList [], actualValPart = Value (Map [(,Map [("",655202)]),(363d3944282b3d16b239235a112c0f6e2f1195de5067f61c0dfc0f5f,Map [("token",-1)])])}
a discrepancy of
  SymValue {symValMap = fromList [], actualValPart = Value (Map [(,Map [("",-1344799)])])}
Expected funds of W[3] to change by
  SymValue {symValMap = fromList [], actualValPart = Value (Map [(,Map [("",-2000001)]),(363d3944282b3d16b239235a112c0f6e2f1195de5067f61c0dfc0f5f,Map [("token",1)])])}
but they changed by
  SymValue {symValMap = fromList [], actualValPart = Value (Map [(,Map [("",-655202)]),(363d3944282b3d16b239235a112c0f6e2f1195de5067f61c0dfc0f5f,Map [("token",1)])])}
a discrepancy of
  SymValue {symValMap = fromList [], actualValPart = Value (Map [(,Map [("",1344799)])])}
Test failed.
```

### Expected Result

The tests pass!

### Describe the approach you would take to fix this

1. Turn on the tests in `plutus-use-cases-test` with more than 10 runs of `QuickCheck`
2. Adjust the implementation of `calculateDelta` to correctly account for the delta due to minimum ada.
3. ...
4. Profit!

Step 2 is a bit tricky but essentially the issue is that it needs to account for the fact that we don't know where all the ada goes, so it should probably simply say "the value could have gone anywhere" and introduce a wide band of uncertainty.

### System info

N/A

**Comment by MaximilianAlgehed** [comment]
ping @ak3n

**Comment by koslambrou** [comment]
@MaximilianAlgehed Should we close this?

**Comment by MaximilianAlgehed** [comment]
Yes.
