### ISSUE TITLE
Cannot use nix shell on macOS 

### ISSUE THREAD

**Issue by awkure** [input-output-hk/plutus-apps#82]
## Summary

When trying to access nix shell from my macOS machine, I get "too many open files" error. 

```
...
derivation: w6y44qg0j1hhyvaz32vkas3gyyzc9klz-network-info-lib-network-info-0.2.0.10-config.drv
required (system, features): (x86_64-darwin, )
1 available machines:
(systems, maxjobs, supportedFeatures, mandatoryFeatures)
(x86_64-linux, 1, big-parallel, kvm, )
Failed to find a machine for remote build!
derivation: f5f64wn9x75z7gbxbx9h8y0nw4zf1b2k-network-lib-network-3.1.2.2-config.drv
required (system, features): (x86_64-darwin, )
1 available machines:
(systems, maxjobs, supportedFeatures, mandatoryFeatures)
(x86_64-linux, 1, big-parallel, kvm, )
error: opening directory '/nix/store/g47vrfhwv20kprd9dbzfdd4ik8agsiy2-network-lib-network-3.1.2.2-config': Too many open files
```

I've tried increasing open fds limit by 4, but the problem persists:

```
> sysctl kern.maxfiles kern.maxfilesperproc
kern.maxfiles: 49152
kern.maxfilesperproc: 24576
```

So I expect that the root of this issue is somewhere else. I've added sandbox paths as was suggested in README and the packages remain unbuildable with the same error. I've even tried clean nix installation, but does not seem to be helping either. 

## Expected behavior

The packages are able to build.

## System info (please complete the following information):

- OS: macOS Big Sur
- Version: 11.6
- Nix version: 2.4 yet downgrading it to 2.3.16 does nothing helpful in this case
- Current master at `406f5f951358c1d44d31b1c5ba5f35b393eed195`

**Comment by ak3n** [comment]
That's interesting. I don't have such a problem.

Can you please share your `cat .config/nix/nix.conf` and `nix --version`?

In my case:
```
sysctl kern.maxfiles kern.maxfilesperproc
kern.maxfiles: 12288
kern.maxfilesperproc: 10240
```

**Comment by awkure** [comment]
Sure

```
> cat ~/.config/nix/nix.conf
experimental-features = nix-command flakes ca-references
builders = @/etc/nix/machines
max-jobs = auto 
keep-outputs = true
sandbox = true
extra-sandbox-paths = /System/Library/Frameworks /System/Library/PrivateFrameworks /usr/lib /private/tmp /private/var/tmp /usr/bin/env

trusted-substituters = ...
```

I've tried both nix versions 2.4 and 2.3.16

**Comment by ak3n** [comment]
Similar to mine but I have `sandbox = false`. Have you tried to turn it off?

**Comment by awkure** [comment]
No, unfortunately turning it off is not of help. This issue is no longer relevant since I solved it by setting up a cloud machine for sole purpose of writing plutus, closing it.

**Comment by omefire** [comment]
I am facing the same issue, was there every any solution found to it?

**Comment by mbrgm** [comment]
Same issue. Any solutions besides using a cloud host? Setting `sandbox = false` did not help.
