### ISSUE TITLE
Unable to build plutus pab

### ISSUE THREAD

**Issue by Vivek205** [input-output-hk/plutus-apps#85]
## Summary
I have installed the repo using nix-shell and tried running `cabal build plutus-pab`. 
I'm getting the below error.

```txt
Warning: Requested index-state 2021-10-20T00:00:00Z is newer than
'hackage.haskell.org'! Falling back to older state (2021-10-19T23:39:06Z).
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: cardano-crypto-class (user goal)
[__0] rejecting: cardano-crypto-class-2.0.0 (conflict: pkg-config package
libsodium-any, not found in the pkg-config database)
[__0] fail (backjumping, conflict set: cardano-crypto-class)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-crypto-class
```

## Steps to reproduce

- Clone the repo
- `nix-shell`
- `cabal update
- `cabal build plutus-pab`

## Expected behavior
Expected to start the Plutus PAB server.

## System info (please complete the following information):

- OS: macOS BigSur
- Version 11.6
- 404af7ac3e27ebcb218c05f79d9a70ca966407c9

## Screenshots and attachments

![image](https://user-images.githubusercontent.com/26110173/140692567-5fd579db-cba5-48a2-abdc-e96c5e1f561e.png)

**Comment by ak3n** [comment]
What's your nix config? (`cat ~/.config/nix/nix.conf`) Is sandbox enabled? Can you please try with `sandbox=false`? Or check that `which cabal` is actually from `/nix/store/...`.

**Comment by Vivek205** [comment]
The issue was with the pkg-config and the libsodium. 
I have added the libsodium path to `PKG_CONFIG_PATH` variable, then the build went through successfully. 

Closing this issue.
