### ISSUE TITLE
Documentation clarification for recent test PAB

### ISSUE THREAD

**Issue by AdamMachera** [input-output-hk/plutus-apps#88]
## Summary
I'm following instruction of release v2021-11-05  for PAB
1. cabal build -> success
2. cabal build plutus-pab-local-cluster cardano-node cardano-wallet -> success
3. cabal exec plutus-pab-local-cluster -> success
4. I was able to hit localhost with curl to run integration tests
5. cabal run plutus-pab -- psgenerator -> I'm getting:
cabal: The run command is for running executables, but the target 'plutus-pab'
refers to the library plutus-pab from the package plutus-pab-0.1.0.0.

I was able to run:
cabal run plutus-pab-test-psgenerator src/Plutus/PAB/Run

and it generates something that might indicate success

```
The following purescript packages are needed by the generated code:

  - purescript-enums
  - purescript-prelude
  - purescript-profunctor-lenses

Successfully created your PureScript modules!
[INFO] Slot 0: TxnValidate 8cc29ae699b906e31bbb8b3e55eea772477cd9aeb7154ce8526752f6f986a31a
```
6. I'm stuck at this point:
```
[nix-shell:~/plutus-apps]$ cabal run plutus-pab -- migrate
cabal: The run command is for running a single executable at once. The target
'plutus-pab' refers to the package plutus-pab-0.1.0.0 which includes the
executable 'tx-inject', the executable 'sync-client', the executable
'plutus-uniswap', the executable 'plutus-pab-test-psgenerator', the executable
'plutus-pab-setup', the executable 'plutus-pab-local-cluster', the executable
'plutus-pab-examples', the test suite 'plutus-pab-test-light', the test suite
'plutus-pab-test-full-long-running' and the test suite 'plutus-pab-test-full'.

```

7. Also I checked this point:
```
[nix-shell:~/plutus-apps]$ cabal run plutus-pab -- all-servers
cabal: The run command is for running a single executable at once. The target
'plutus-pab' refers to the package plutus-pab-0.1.0.0 which includes the
executable 'tx-inject', the executable 'sync-client', the executable
'plutus-uniswap', the executable 'plutus-pab-test-psgenerator', the executable
'plutus-pab-setup', the executable 'plutus-pab-local-cluster', the executable
'plutus-pab-examples', the test suite 'plutus-pab-test-light', the test suite
'plutus-pab-test-full-long-running' and the test suite 'plutus-pab-test-full'.
```

Please let me know if I'm doing something wrong.

My git status returns:
[nix-shell:~/plutus-apps]$ git status
HEAD detached at v2021-11-05

**Comment by ak3n** [comment]
Thanks for the issue!

Please try `cabal run plutus-pab-examples -- migrate` and `cabal run plutus-pab-examples -- all-servers`.

The idea behind README is that it describes the interface of some `plutus-pab` but there is no default plutus-pab. There is an example called `plutus-pab-examples` but the idea is that you need to create your own PAB that will respect the aforementioned commands.

**Comment by AdamMachera** [comment]
Thanks for reply.
