### ISSUE TITLE
Will state machines be adapted for Plutus V2?

### ISSUE THREAD

**Issue by jonathanfishbein1** [input-output-hk/plutus-apps#883]
https://github.com/input-output-hk/plutus-apps/blob/20ac87dc4d0bd969840168bd84c063f3a6f78887/plutus-contract/src/Plutus/Contract/StateMachine/OnChain.hs#L40

**Comment by berewt** [comment]
We're progressively migrating everything to V2, so yes. We don't have a release date yet though.

**Comment by berewt** [comment]
It's done!
