### ISSUE TITLE
Cannot Run nix-shell on M1 Mac in v1.0.0

### ISSUE THREAD

**Issue by trevinwisaksana** [input-output-hk/plutus-apps#892]
### Summary

Hi I'm trying to run nix-shell on my M1 MacBook Pro using the v1.0.0 which is [latest version](https://github.com/input-output-hk/plutus-apps/releases/tag/v1.0.0) at this time of writing. However, I get this error while trying to do so:

```         
zsh: segmentation fault  nix-shell
```

I've attempted to reinstall nix but to no avail. I followed the installation tutorial found [here](https://github.com/renzwo/cardano-plutus-apps-install-m1).

Does any one have any suggestions on what I could do to fix this? Thanks!

### Steps to reproduce the behavior

1. Clone the v1.0.0 repository
2. Run nix-shell in the plutus-apps directory using an M1 Mac

### Actual Result

```         
zsh: segmentation fault  nix-shell
```

### Expected Result

It should start a nix-shell environment.

### System info

This is the setup I'm using on my nix.conf:

```
build-users-group = nixbld

substituters        = https://hydra.iohk.io https://iohk.cachix.org https://cache.nixos.org/
trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

system = x86_64-darwin
extra-platforms = x86_64-darwin aarch64-darwin

sandbox = false
extra-sandbox-paths = /System/Library/Frameworks /System/Library/PrivateFrameworks /usr/lib /private/tmp /private/var/tmp /usr/bin/env
experimental-features = nix-command
extra-experimental-features = flakes
```

**Comment by kelizarov** [comment]
Try to call with `GC_DONT_GC=1 nix-shell` it might be the flakes that causing this.

**Comment by trevinwisaksana** [comment]
Awesome! Got it to work. Thanks!
