### ISSUE TITLE
Solve contention problem: Singleton UTXO. Reference Utxo by contract not by address

### ISSUE THREAD

**Issue by anton-k** [input-output-hk/plutus-apps#9]
## Area

[X] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[X] *Other* Any other topic (Playgrounds, etc.)

### The problem

I'm sure being a core developer you are aware of it. For those who don't here is sad description of affairs:

We have big problem with contention. UTXO that holds datum is often associated with the state of the app.
And we imagine that it's single App in the blockchain. We even create a dedicated token to it so that user can find it
and we should check that it's spent to itself and properly updated.

Conceptually it's a single app that user interact with. Contrary on the blockchain (level of implementation)
we emulate this with tricks like dedicated miniting token, checking that token is spent to itself.

So the user thinks about it as an app that is identifier by the ScriptHash, but it's attached to UTXO
and we identify it by the concrete token, and we check that it's spent to itself. UTXO has to carry a value.

Concurrency in blockchain is handled when we put many TXs on the block. We can have hundreds of them.
So it seems that many users can interact with a single App and be happy. 
Yet this is not the case. Because conceptual model breaks on the implementation level. 
App is attached to the UTXO which is referenced by address, and TX changes that address.
That means that user A and user B submit TX_A and TX_B and both reference to the App state by the same address.
But first TX which succeeds overrides the UTXO address making the second TX invalid.

This brings dramatic impact on the APPs. We are reduced to only one TX per block, which is suffocating for real world apps.

We need to devise workaraunds. But TX-size is limited and we have workaraound-logic that drain the TX-space, 
for bridging the gap between concept and implementation.

### We need a solution to survive

This TX-size limit of 16 kb and the need to implement the logic of workarounds is suffocating and 
it's hard to do anything real on blockchain like this. 

### Proposed method

I think the core of the problem is inability to reference the App by it's ScriptHash. The need to reference it by ref to UTXO which is not even used in validation logic and going to change unexpectedly based on which user submits TX first. 
We need to devise some valid method for that that is built in the Plutus. 

Here is my idea, maybe you will have even better ones. Let's discuss that before it's too late.

### Proposal:  Singleton contract output

Singleton contract can have only one UTXO that can be identified by it's script hash. 
Globally on block chain there should be only one such UTXO. Every write to it overrides it.
It can be  identified by the ScriptHash since there is 1-to-1 correspondence to it. 
It can be enforced by it's special type.

Users should be able to reference this singleton by script hash alone.  and this brings together concept of DApp state and the implementation for it. No need for dedicated token, no need for logic to check that it's spent to itself. No need for processing TXs in batch to avoid contention.

Singleton contract output can be referenced by Script hash. this way we can update it multiple times per block,
this saves enormous amount of trouble we are having now as a team and I'm sure many other teams are fighting with that.

If we want several such apps in the wild we can parametrize them by TxOutRef (trick used in NFT) and use it only once. Not all the time.

### Another proposal: global table of contracts (reference contracts by hashes)

According to our data most space used in TX (~ 90%) is space  for scripts or contracts in the inputs. We can reduce that if we
substitute them for hashes. Let's say user allocates contract on blockchain and pays for the space. Then User can use hash to the contract instead of the whole body. This way we can save almost all space. 

This solution is cool that it does not sacrifices the purity of blockchain. In case of so called singleton UTXO
we update inplace the datum. In this case there is no need to update in place. We save on input contracts.

## Describe alternatives you've considered

We considered creation of App state and association it with NFT. 
we need logic that consumes TX-space to check the NFT and to check spending to itself all the time we use it.

Still it does not solve the problem of single action per block.

To mitigate problem of single action per block we create a special logic that accumulates actions and executes them in batch mode. This is non trivial action and it consumed all the space in TX. We do it only to find that we can **execute single action** in such a **list of actions**.  It all took enormous amount of R&D and hitting our heads against the wall :(

We need something better than that. Your input is very welcome. Proposed solution can have shortcomings that I'm not aware of.
but let's not skip it as not so important issue. We can say that mathematically it can be shown that this stuff is the same.
And we can reduce one to another given infinite amount of space in TX and infinite small time for block confirmation.
We have neither of them. 

We take a lot of efforts to make workaround to build very simple apps that do not work on the given limitations.

## Additional context / screenshots

![](https://image.freepik.com/free-photo/hitting-head-into-wall_102671-5385.jpg)

**Comment by koslambrou** [comment]
Closing as this feature (reference inputs) will be available in the next hard-fork. `plutus-apps` is currently working on updating it's codebase to support it, but might take some time.
