### ISSUE TITLE
Secure PAB endpoint

### ISSUE THREAD

**Issue by bhoudebert** [input-output-hk/plutus-apps#90]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[X] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

Using and developing around PAB is really fine/sweet but I cannot understand my way around when it comes to auth/sign the endpoint offers by PAB. During tests we all use the simulator and or direct wallet id through eg curl which is fine but after that?

If these endpoints were receiving a Tx I would assume signed tx with auto reject by PAB.

Am I missing something here as the json sent by PAB is not signed (did not saw any mention on source code either)? I might have seen some part are still using mock maybe that is the reason<

Eg: regarding pab example lock/guess, if I know the wallet pub id of the other player I can play his place.

Feel free to advise me otherwise as I am quite new on Cardano.

**Comment by ak3n** [comment]
Thanks for the issue!

If I understood correctly, the answer is the PAB node relies on the wallet backend to sign and to submit the transactions.

**Comment by bhoudebert** [comment]
Thanks for the reply.

From documentation PAB seems directly called and the wallet backend is not involved (yet) instead a simple id is used to match the wallet. Later on I am agree with you the wallet is used to do everything.

But before, to reach PAB, a simple rest call triggers the whole mechanism.

eg from starter to keep it simple:
```
curl -H "Content-Type: application/json" \
  --request POST \
  --data '{"amount":{"getValue":[[{"unCurrencySymbol":""},[[{"unTokenName":""},90]]]]},"secretWord":"eagle"}' \
  http://localhost:9080/api/contract/instance/$INSTANCE_ID/endpoint/lock
```

Anyone can call lock on `my` wallet with a simple call (brutforce, id discover etc.). As there is no real Tx before PAB signing is not so clear.

So either:
- PAB is missing a part of wallet signing in the endpoint payload (maybe PAB should discuss internally with cardano-wallet?)
- If PAB is not to be called directly security is in a weird place as user will not allow him to forge Tx (meaning allowing PAB to know the private key) --> I do not assume at all it is a possibility
- I am lacking knowledge of something

In my mind I would expect something like a uniq code/signature tx passing through from endpoint to pab/wallet to chain to ensure user is at the origin of the call (like real tx sign). Mostly because at some point malicious people could run PAB like it is today without any verifications.

**Comment by bhoudebert** [comment]
I might have found something from digging https://github.com/input-output-hk/plutus/blob/master/notes/smart-contract-backend/scb.md

Still do not know if code has to change (except not using emulator part)

**Comment by bhoudebert** [comment]
I found a smiliar issue so I propose to close this one and see in https://github.com/input-output-hk/plutus-apps/issues/59
