### ISSUE TITLE
docs miss information on which plutus-apps tag to use.

### ISSUE THREAD

**Issue by aleeusgr** [input-output-hk/plutus-apps#906]
### Summary

Presumably at the time of the writing only latest checkout was used

### Steps to reproduce the behavior

1. git clone plutus-starter (see CONTRIBUTING.md for docs)
2. Follow [this page](https://plutus-apps.readthedocs.io/en/latest/plutus/tutorials/basic-apps.html) and add first code block to src/
3. ./scripts/test fails with error:

### Actual Result

```
src/MyModule.hs:18:64: error:
    Module `Plutus.Contract' does not export `getParams'
   |
18 | import Plutus.Contract (Contract, Endpoint, Promise, endpoint, getParams, logInfo, selectList, submitTxConstraints,
   |                                                                ^^^^^^^^^
```

### Expected Result

no errors

### Describe the approach you would take to fix this

I would supply the docs with newer code,
or dig when the docs were written and which git checkout was latest then.

### System info

Linux nixos 5.15.82 #1-NixOS SMP Thu Dec 8 10:28:45 UTC 2022 x86_64 GNU/Linux

**Comment by berewt** [comment]
Thanks for the report. Yes, unfortunately, since the Babbage era `plutus-starter` isn't up to date, updating it is on our backlog and it should be resolved in a near future.

**Comment by berewt** [comment]
Unfortunately, there won't be a fix in a near future for this, as we have decided to rework plutus-starter instead of just updating it (see #971). There's a working nix environment for plutus-apps v1.1 in a [dedicated branch of plutus-starter](https://github.com/input-output-hk/plutus-starter/tree/nicolas/plutus-apps1.1), but the provided CI and tests scripts have not been updated.

**Comment by aleeusgr** [comment]
From my research for [Developer Experience Working Group](https://github.com/input-output-hk/Developer-Experience-working-group) it follows that there is a gap in the docs that is significant and needs to be fixed somehow:
E.g. if I am a new developer on Cardano, odds are I am starting at Cardano Develper Portal and I end up [here](https://plutus-apps.readthedocs.io/en/latest/plutus/howtos/getting-started.html), but then I face a dead end.

Thank you!
