### ISSUE TITLE
Add an export of mustSatisfyAnyOf

### ISSUE THREAD

**Issue by iaverypadberg** [input-output-hk/plutus-apps#95]
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like

I would like for the plutus team to add in an export of ```mustSatisfyAnyOf``` to Ledger.Constraints. I would like to use it in a StateMachine but cannot because it is not exported.

**Comment by ak3n** [comment]
Thanks for the issue!

**Comment by silky** [comment]
@iaverypadberg Next time, please do consider making a PR yourself; you can see [here](https://github.com/input-output-hk/plutus-apps/blob/main/CONTRIBUTING.adoc) for how to set up a development environment :)

We would welcome your contributions!
