### ISSUE TITLE
Test node integration test failure

### ISSUE THREAD

**Issue by volodyad** [input-output-hk/plutus-apps#98]
I have run tutorial in the file plutus-apps/plutus-pab/test-node/README.md

 at the step 
```
  > curl -H "Content-Type: application/json" -v -X POST -d \
    "{\"caID\":{\"tag\":\"IntegrationTest\"},\"caWallet\":{\"getWalletId\":\"$WALLET_ID\"}}" \
    localhost:9080/api/contract/activate
```

it show PAB logs and do not proceed farther
```
[pab:Info:276] [2021-11-10 10:04:56.18 UTC] 3e612ac5-dacd-403f-8905-3b0bea0e9483: "Starting integration test"
[pab:Info:276] [2021-11-10 10:04:56.18 UTC] Initialising contract IntegrationTest with ID 3e612ac5-dacd-403f-8905-3b0bea0e9483
[pab:Info:276] [2021-11-10 10:04:56.18 UTC] Activated instance 3e612ac5-dacd-403f-8905-3b0bea0e9483 on W88cc0e4
```
after few minutes it shows
```
Current block: 100000. Current slot: 27243687
Current block: 200000. Current slot: 33116605
```

Additional details

 ```
  > cd $PLUTUS/plutus-pab/test-node/
    cabal exec -- plutus-pab-examples --config testnet/pab-config.yml migrate
  ```
migrate runs immediately and do not show anything in console log, how to check that migrate finished successfully?  could it be the reason?

Cardano node is built from master branch because of the issue https://github.com/input-output-hk/plutus-apps/issues/86

**Comment by ak3n** [comment]
@volodyad great! How long did it take to succeed?

**Comment by silky** [comment]
Fyi @volodyad , running the `migrate` command completes immediately; that just sets up the database schema.

**Comment by volodyad** [comment]
> @volodyad great! How long did it take to succeed?

15-30 minutes, next invocations runs fast
